### ISSUE TITLE
Jet mismatch in mint:ut

### ISSUE THREAD

**Issue by eglaysher** [urbit/urbit#1009]
Currently, Urbit will not start with the mint jet disabled, as several files will nest-fail on a `~|` or `~&`.

These include `%/mar/txt/hoon`, `%/lib/tester/hoon`, `%/lib/cram/hoon`, and I gave up after commenting those out.

**Comment by ohAitch** [comment]
None of those should be on the critical path to boot? `mar/txt` might make future revisions fail, but I would expect you to still get a functioning dojo prompt first.

That said, if the `~&`/`~|`s in question are in wet gates, I would not be surprised if urbit/arvo#568 was a jet-only issue.

**Comment by cgyarvin** [comment]
Probably some of these are fixed on the research branch.  We'll just have
to fix them the way we fixed the others, by firing up Truffle.

You can't boot without compiler jets anyway, because you need at least the
partial memoization (memoization ignoring the worklist) the jets provide.
Otherwise you'll spin forever.  The Truffle urbit does partial memoization
but no other jet propulsion of ++ut, making it ideal for testing semantics.

**Comment by joemfb** [comment]
Known mismatches where fixed in #1353 and #1380, future mismatches are made impossible by #1422
