### ISSUE TITLE
nest bail: fail on type error

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#1024]
When passing in a noun of an invalid type to `u3wfu_nest()`, which is called by Hoon's `+nest`, the jet calls `u3m_bail(c3__fail)`, which escapes virtualization and kills the Urbit process.

I believe these should be replaced with `u3m_bail(c3__exit)` since a type error in the sample of `+nest` is a deterministic Nock error.

**Comment by joemfb** [comment]
The "bug" was that `bail: fail` explicitly aborted the process. This is no longer the case; it kills the whole event, which is replaced with an error report. This is trivially verifiable, just `(bex (bex 128))` in `:dojo`.

Furthermore, it's perfectly legitimate for a jet to fail in cases where it could plausibly exit. The latter must be not only deterministic, but exactly equivalent to the crash conditions in the nock it's replacing, otherwise it represents a jet mismatch. The former just says "nope, couldn't do that".
