### ISSUE TITLE
Build failure on CentOS 7

### ISSUE THREAD

**Issue by ngzax** [urbit/urbit#1077]
On a brand new instance of CentOS 7 (after yum upgrade), I tried building with the Linuxbrew method and got when trying to run urbit:

"urbit: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: no such file or directory"

Using the "fedora / redhat" instructions and received: 

"meson encountered an error in file meson.build, line 281, column 0:invalid version of a dependency, needed libcurl >=7.35.0 found 7.29.0."

**Comment by mdecerbo** [comment]
I also encountered the libcurl issue. I solved that by installing an up-to-date curl in /usr/local by hand and making the following change to `meson.build`:

```
*** meson.build.orig	Thu Nov 29 17:10:11 2018
--- meson.build	Thu Nov 29 20:44:33 2018
***************
*** 280,282 ****
  # We expect these libs to supplied with the distribution
! curl_dep = dependency('libcurl', version: '>=7.35.0')
  
--- 280,282 ----
  # We expect these libs to supplied with the distribution
! curl_dep = [ meson.get_compiler('c').find_library('curl', dirs: [ '/usr/local/lib' ]) ]
```

**Comment by joemfb** [comment]
It looks like #1119 might have a fix for this issue.

**Comment by Richardn2002** [comment]
> It looks like #1119 might have a fix for this issue.

okay,now the error changes to

urbit: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

...

**Comment by Richardn2002** [comment]
> It looks like #1119 might have a fix for this issue.

Fixed.
It's very likely my own fault.I recalled that when I first installed brew,no commands continued to work on my instance.It was because brew's libs messed up with the system's original ones and caused tons of relocation errors.So I removed the line
`export LD_LIBRARY_PATH=....`
in .bash_profile required by brew myself.
So now urbit can't find brew-installed up-to-date libs.
I add back 
`export LD_LIBRARY_PATH=$LINUXBREWHOME/lib`
then urbit works.
