### ISSUE TITLE
Urbit fails at boot with c3_rand getentropy: Function not implemented

### ISSUE THREAD

**Issue by abliss** [urbit/urbit#1155]
```
 build/urbit -c comet1
~
urbit 0.7.0
boot: home is /home/abliss/proj/urbit/comet1
loom: mapped 2048MB
boot: installed 256 jets
fetching https://bootstrap.urbit.org/urbit-0.7.0.pill to comet1/.urb/urbit.pill
boot: loading comet1/.urb/urbit.pill
arvo: time: ~2019.1.18..02.54.22..7179
c3_rand getentropy: Function not implemented
```

**Comment by abliss** [comment]
under strace:
```
14697 open("/usr/lib/ssl/cert.pem", O_RDONLY) = -1 ENOENT (No such file or directory)
14697 getrandom(0x7ffc9c139ff0, 64, 0)  = -1 ENOSYS (Function not implemented)
```

**Comment by abliss** [comment]
It does not appear to be attempting to use libent, despite that I've pulled the latest master and run `scripts/bootstrap && scripts/build`. Is there a way to trigger a clean build?

**Comment by joemfb** [comment]
It looks like the syscall feature test in `libent/src/meson.build` needs to use `cc.run` instead of `cc.link`

**Comment by abliss** [comment]
Yeah, something like that. Except compiler.runs() actually seems to work. I'm trying to work out how to get meson to actually check the return code. compiler.run().returncode() doesn't seem to work right...

**Comment by joemfb** [comment]
Interesting, I wonder if the compiler object didn't have that method in meson 0.29. Maybe libent needs to simply fallback to `/dev/urandom` if the meson version is 0.29.

**Comment by abliss** [comment]
No, it works fine now, not sure what I was messing up before. I sent a PR to libent. Thanks.

**Comment by mrdomino** [comment]
urbit/libent#3 opened along with #1157.

**Comment by nlongname** [comment]
I know this is years later, but I'm getting exactly the same issue:

`./urbit -c mycomet
~
urbit 1.2
boot: home is /home/nlongname/urbit/mycomet
loom: mapped 2048MB
lite: arvo formula 79925cca
lite: core 59f6958
lite: final state 59f6958
boot: downloading pill https://bootstrap.urbit.org/urbit-v1.2.pill
c3_rand getentropy: Function not implemented`

Running Ubuntu 16.04 on an Acer C720 chromebook. Linux kernel 3.8.11, just as above.

**Comment by abliss** [comment]
@nlongname did you configure and build from source on that machine? you won't be able to run the pre-built binaries since they are configured on a machine with a newer kernel.

**Comment by joemfb** [comment]
FYI, with the from meson to nix, libent was brought into the monorepo (at `pkg/ent`). It's designed to configure the entropy source at build time, so you'd have to install nix and then build urbit locally for it work properly on an older kernel.

However, it might be better to wonder if we also configured the entropy source on startup (checking for `ENOSYS` on `getentropy()`, falling back to `/dev/urandom`). @mrdomino, what do you think?

**Comment by mrdomino** [comment]
Oh gosh, my past decisions are all coming back to me at once aren't they.

Possible solutions in order of my preference:

   1. Leave stuff as-is and let folks hotwire in /dev/urandom support on
   their own if they want to. (Folks who are interested in hotwiring: if I'm
   not mistaken, you can do this by just deleting everything except lines 44
   to 58 of pkg/ent/ent.c.)
   2. Screw it, just use /dev/urandom everywhere, why did I spend all this
   effort trying to support this random syscall (pun completely intentional)
   in the first place?
   3. The thing you mentioned about detecting at runtime whether the
   syscall works or not.

Justification for that ordering is: A, Linux 3.x is kinda old now and
nobody else provides official support for it anymore. B, I start to feel
much less like we're buying anything by using getentropy if there's any
additional runtime complexity added.

On the other hand, I can't remember why I cared so much about using
getentropy at the time and /dev/urandom is clearly fine for this purpose,
so you could very easily convince me to just go with approach 2 and rip the
whole shim out.

**Comment by nlongname** [comment]
> @nlongname did you configure and build from source on that machine? you won't be able to run the pre-built binaries since they are configured on a machine with a newer kernel.

I don't really know what I'm doing, so it's been a process of trial-and-error. When the pre-built binaries didn't work I built from source. When that didn't work, I tried the hotwire (pretty much exactly what @mrdomino said) and that worked. It seemed easier than messing around with configuration, but I could be wrong about that.

Personally, I'm not sure it's really worth changing anything; I'm totally satisfied having the issue and fix publicly documented so it's fairly obvious what to do if anyone else runs into it.

**Comment by mrdomino** [comment]
Yay, I'm glad that worked!

**Comment by mrdomino** [comment]
@joemfb thoughts?

**Comment by zalberico** [comment]
Based on the comments in this thread I think we're good to close. If that's not the case, I can reopen it and write up an issue for what we specifically want to change.
