### ISSUE TITLE
building on ubuntu: ModuleNotFoundError: No module named 'pip._internal'`

### ISSUE THREAD

**Issue by msiqu** [urbit/urbit#1242]
Just tried to install the latest urbit after the latest breach and I'm having dependencies issues with python (I think). Below is the error I get when I run: `sudo -H pip3 install --upgrade pip`

> Traceback (most recent call last):
>  File "/usr/local/bin/pip3", line 7, in <module>
>    from pip._internal import main
> ModuleNotFoundError: No module named 'pip._internal'`

Anyone else had this issue and solved? This is a ubuntu18.04 2GB VPS.

**Comment by jglukasik** [comment]
Hey @msiqu , I just tried installing Urbit on a fresh VPS host, running Ubuntu 18.04

I followed the install procedure at https://urbit.org/docs/getting-started/installing-urbit/#ubuntu-or-debian , copied here for reference:

<details>
<summary>Expand install docs...</summary>

```
# Bash

sudo apt-get update
sudo apt-get install g++ git libcurl4-gnutls-dev libgmp3-dev libncurses5-dev libsigsegv-dev libssl-dev make openssl pkg-config python python3 python3-pip python3-setuptools zlib1g-dev ninja-build
sudo -H pip3 install --upgrade pip
sudo -H pip3 install meson

git clone https://github.com/urbit/urbit
cd urbit
./scripts/bootstrap
./scripts/build
sudo ninja -C ./build/ install
urbit
```
</details>

Everything worked fine for me? I did have to enable swap space though.

Some ideas:
1. Did you copy the entire `apt-get install` line correctly? And did it install everything without errors?
2. Does running ` python3 -m pip install --user --upgrade pip` work, instead of the `sudo -H pip3..` command? Kinda a shot in the dark here, but it seems to have fixed a similar problem discussed [in this thread](https://github.com/pypa/pip/issues/5373#issuecomment-460214265)

**Comment by jtobin** [comment]
(Going to close this one as there's been no further update.)
