### ISSUE TITLE
hapten.arvo.network seems to be pointing to a random IP address

### ISSUE THREAD

**Issue by msutherl** [urbit/urbit#1257]
1. Go to http://hapten.arvo.network/
2. Points to 157.230.156.109:80

The IP address of the machine ~hapten is running on: 35.184.224.193

**Comment by jtobin** [comment]
This seems weird.  Really seems like there shouldn't be anything funny going on, but the story checks out:

```
jtobin@castor:~$ dig hapten.arvo.network

[..]

;; ANSWER SECTION:
hapten.arvo.network.    300     IN      A       157.230.156.109
```

```
jtobin@castor:~$ ping hapten.arvo.network
PING hapten.arvo.network (157.230.156.109): 56 data bytes
64 bytes from 157.230.156.109: icmp_seq=0 ttl=54 time=164.056 ms
```

```
urb@hapten:~$ curl -s http://checkip.dyndns.org/ | sed 's/[a-zA-Z<>/ :]//g'
35.184.224.193
```

**Comment by jtobin** [comment]
Worth noting: if you just hit `http://hapten.arvo.network` in a browser, you'll see the text "I am here."  Using HTTPS will give you a cert warning.

**Comment by joemfb** [comment]
FWIW, this means that either someone typed `:dns|ip .157.230.156.109` *on* ~hapten, or someone with GCP credentials manually created this record. This isn't really an urbit or arvo issue, although we don't any process setup for retracting bad bindings.

On the current network, the fix is to just run `:dns|ip .35.184.224.193` on ~hapten.

**Comment by jtobin** [comment]
> This isn't really an urbit or arvo issue

*say no more*

**Comment by msutherl** [comment]
Didn't get a chance to chime in. @joemfb is correct.
