### ISSUE TITLE
lighter-than-eyre branch bail oops upon type printing from an ap-lame

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#1276]
```
[! gall: %timer: call: %wake: type mismatch  [%ap-lame %timer %wake]]
Assertion '!"hija-tcsetattr"' failed in vere/term.c:1217

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 663.
Abort trap: 6 (core dumped)

**Comment by loganallenc** [comment]
@joemfb Cited you in this for visibility.

**Comment by joemfb** [comment]
I think this is just the intermittent, spurious terminal assertion failure in terminal hijack/lojack.

Were you running urbit directly, or via `make test` or some other new staging mechanism?

**Comment by loganallenc** [comment]
Running urbit directly.

**Comment by joemfb** [comment]
Is the crash reproducible?

**Comment by joemfb** [comment]
This might prove useful: https://linux.die.net/man/3/explain_tcsetattr

**Comment by loganallenc** [comment]
Nope.

**Comment by philipcmonk** [comment]
I'm running into the same problem, except it's "loja-tcsetattr-1: Interrupted system call".  It happens when I resize the window while output is happening, about 1 in 20 times.  I resize very often in my tmux flow (with C-b z).  I'd like to attach explain_tcesetattr.  How can I install libexplain in the context for the build?

**Comment by philipcmonk** [comment]
FWIW, the nvi folks fixed a similar problem by retrying on `EINTR`: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=189266

**Comment by jtobin** [comment]
Not sure why merging the linked PR didn't close this one.
