### ISSUE TITLE
How does this compile let alone produce the desired answer

### ISSUE THREAD

**Issue by baudtack** [urbit/urbit#1366]
A hoon school student turned this in when asked to write a gate that would apply a new aura to an atom.

```
|=  a=@
@ub=a
```

Looking at this I have no idea how it compiles, let alone actually produces a binary version of the atom.

**Comment by matildepark** [comment]
Wait, so `@[type]=` is irregular syntax alongside the ` quote irregular syntax?

**Comment by philipcmonk** [comment]
Ha, never seen that before.  `(ream '@ub=a')` verifies that this is indeed `^=`.  This is similar to the "feature" that allows ``=+  [a=@ub b=@ux]=`[@ @]`[5 6]  -``.  This is bad style, consider `^-` instead of `^=`.  This may have been introduced as part of the change to allow syntax like ``=/  b=@ub  `@`5  a``.  It probably shouldn't be allowed.  For extra fun, try ``=@ub=`@`5``.

Basically, `ktts` occupies an awkward zone between "apply a face to a value" and "cast to a type".  I think it should be used only for the first, but we currently allow it to take any skin, but not any spec.  It also has a more lax parser than eg `=/`, which also takes a skin but doesn't parse `@ub`.

**Comment by philipcmonk** [comment]
@matildepark `@` syntax is irregular syntax for specifying the type of an atom, not types in general.  So, `@ud` is a decimal atom, `@da` is an atom representing an absolute date, etc.

**Comment by matildepark** [comment]
Apologies, was speaking too imprecisely.

**Comment by joemfb** [comment]
This is an artifact of the new `skin` face control system, which is incomplete and inconsistent. I assume this was not intentional, and is just an overly-accepting parser in front of an overly-general system. But even if it was intentional, I don't think it should be supported.

Also, this doesn't just concern atoms and auras:

```
> $:|=(a=^ ^=a)
[0 0]
> (ream '|=(a=^ ^=a)')
[%brts p=[%bsts p=term=%a q=[%base p=%cell]] q=[%ktts p=[%base base=%cell] q=[%wing p=~[%a]]]]
```

**Comment by ohAitch** [comment]
Dupe of #1344? I wonder if this is way more recent than `=/` given we're seeing multiple reports

**Comment by joemfb** [comment]
Yeah, this is a dupe. These were introduced in cgy's last round of language changes, which were released at the beginning of 2019.

**Comment by baudtack** [comment]
Closed as dupe of 1344
