### ISSUE TITLE
Blank Host/Name Notebooks

### ISSUE THREAD

**Issue by techieAgnostic** [urbit/urbit#1390]
Somehow got myself into a state where I can't see the names or hosts of Notebooks Im subscribed too, and can't click them to be taken there.

The posts still show up in recent, sans Name but showing the host, and the urls they lead to have the correct information, however the breadcrumb trail in landscape is just blank.

Here are some screenshots:

Subscription list + error I get when clicking unsubscribe
![issue](https://user-images.githubusercontent.com/12219560/61915772-18f45180-af9a-11e9-9009-5b2f488019c8.png)

How they look in the Recent tab
![issue2](https://user-images.githubusercontent.com/12219560/61915793-29a4c780-af9a-11e9-9fdb-ffc81facd3f2.png)

**Comment by ixv** [comment]
It looks like this happens when the files associated with the notebook are deleted directly from clay rather than through the publish API.

I'm currently working on this, but in the meantime there are some dojo commands you can run to fix your state.

In the case that it's a subscription, if you know the host and notebook name you can run
`:publish &publish-action [%unsubscribe ~ship-name %notebook-name]`

if you don't know them, you can run `:publish %print-state` and try to decipher the output. Or post it here and I can help you.

In the case that its one of your own notebooks, you can run
`:publish &publish-action [%delete-collection %notebook-name]`

**Comment by ixv** [comment]
Closing this since it applies to the previous version of publish.
