### ISSUE TITLE
Fix ++to ++by etc types properly

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#1470]
`++  ju  |_  (tree (pair * (tree)))` instead of `|_ (jug)` or at least `|_  (map * (set))` is utterly unacceptable from a documentation standpoint, and something more comprehensive than aa88831 should be done about it long-term.

**Comment by zalberico** [comment]
Im going to close this as unplanned. If I'm wrong and this is important we can tag it as future, but from the thread I'm not convinced it's useful to keep around as an open issue. @belisarius222 for context.

**Comment by joemfb** [comment]
This issue is a good complaint about some core data structures in the stdlib, and I'd hate to lose track of this. It obviously hasn't been a high priority, but it's perfectly legitimate. If you're going to close things like this, can you add a summary issue to track them? Or maybe use some kind of tagging scheme so that they don't completely disappear?

**Comment by zalberico** [comment]
When something is precise enough that I think I can frame a new summary issue around it I'll do that and link back, when it's more of a good idea/suggestion but is unplanned or needs more r&d I'll tag it with `lazarus` so we can easily surface these if one day we want to bring them back from the dead. 🕯️
