### ISSUE TITLE
history pruning support in clay

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#1525]
As discussed in urbit/arvo#598, perhaps preferrable simpler alternative to sophisticated mechanism like "eyre-gall bridge" would be having blob storage support in clay with support for pruning of history. 

Near term this is very important to get urbit app development from the ground, as it lost pace after it has been discovered current clay architecture is unable to sustain distribution of UI blobs without messing up ships. Plato has been in limbo ever since, as there is currently no way to distribute it the urbit way, and even then no way to update UI without bloating clay. 

What I would like to have:
- Ability to store blobs inside clay
- Ability to prune history (As an Urbit app designer, I would like to keep major revisions of the UI, but discard bugfixes revisions)
- Ability to delete nodes from clay (or at least advancing history to the last file version with 0 size)
- The last point could be considered in light of users wanting certain clay nodes to just be gone, 
  including their name. I can imagine in many cirumstances even metadata would be considered sensitive. 

Maybe we can have some discussion going on this, and once the dust settles on new Ford and Clay, we could eye and least implementing a working prototype, at the very least fixing the bug which currently prevent storing "large" (as in MBs) files.

**Comment by joemfb** [comment]
The underlying issue in question was not any intrinsic limitation of %clay, it was just stack-overflows (first in the runtime's unifying equality, then in unoptimized encryption gates used by ames). The former was fixed in urbit/urbit#948; the latter was reported in urbit/arvo#740 and fixed in urbit/arvo#756.

Clay has "blob" support, insofar as it persists arbitrary typed data, controlled by a mark file -- that could be (and often is) as simple as an arbitrary atom. (It also happens to be implemented in terms of an arbitrary blob store, and a simple synchronization protocol for the same.)

As it stands, this issue is a request that history-manipulating operations be added to %clay.

**Comment by joemfb** [comment]
#3139 is highly relevant.

**Comment by joemfb** [comment]
This support was added in #5408.
