### ISSUE TITLE
Double blank newline required between block-quote and headers

### ISSUE THREAD

**Issue by rmariani** [urbit/urbit#1558]
Udon won't render unless there's two blank newlines between a closing ``` and a `# Header`.

**Comment by jfranklin9000** [comment]
You mean this?

    ```
    code
    ```
    # header

This works.  Here is output from the **udon** parser:

<img width="1183" alt="code-header" src="https://user-images.githubusercontent.com/15039850/63663953-3def0680-c78a-11e9-80aa-7fa676e11d34.png">

The opposite case doesn't:

    # header
    ```
    code
    ```

```
[%bad-block-structure %head 1 1]
[%err [~ u=[p=3 q=1]]]
```

(`p=3` due to `;>` line that I'm not showing)

In fact, anything following a header without a blank line errors out.

(I thought there was an issue that was exactly this case but I can't find it.)

**Comment by matildepark** [comment]
#1543, #1541, etc. (Though requiring newlines between headers and content isn't strictly a bug, just a style enforcement.)
