### ISSUE TITLE
Can't get udon to render

### ISSUE THREAD

**Issue by jfranklin9000** [urbit/urbit#1563]
1. Create comet

1. Sign in with browser

1. click Okay! to enter Landscape

1. Load `http://localhost:8080/~~/static.udon`
![static-udon](https://user-images.githubusercontent.com/15039850/52173818-eab35900-2750-11e9-9bbb-9d3ccdca09f4.png)

1. Load `http://localhost:8080/~~/static.html`
![static-html](https://user-images.githubusercontent.com/15039850/52173823-01f24680-2751-11e9-9ecf-36ded813b830.png)

1. Load `http://localhost:8080/~~/static/` or `http://localhost:8080/~~/static`
![static](https://user-images.githubusercontent.com/15039850/52173824-12a2bc80-2751-11e9-8274-4d561b041545.png)

4 was expected, 5 was.. dunno, 6 was not expected.

Then I tried
```
dojo> |mount %
dojo> |serve %home
```
but got the same results.

How do I get the udon parser to run?

**Comment by matildepark** [comment]
This issue is based on a pre-Eyre-rewrite interaction pattern for serving web content, and thus is obsolesced (as of June 2019, in fact).

You can currently serve content by poking `%file-server` with the folder on your `%home` desk and the endpoint you'd like to attach it to:

```
:file-server &file-server-action [%serve-dir /'~example' /app/example %.y]
```

In which `/'~example'` is the endpoint you're serving it on, `/app/example` is the location of the files, and `%.y` is whether or not it is public.

This, itself, is at time of writing affected by #3047.
