### ISSUE TITLE
$% buccen not consistent about always-present faces

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#1656]
(Feel free to put a better title there.)

Consider:

```hoon
> %.  f+5
  |=(a=$%([%f x=@] [%b x=@]) +(x.a))
6

> %.  f+5
  |=(a=$%([%f x=@] [%b x=@ y=@]) +(x.a))
-find.x.a
find-fork-e
```

In the first case, changing the `%b` to `x=^` causes the function definition to nest-fail, so the compiler _knows_ that `x.a` will always be `@`.

Why does that not hold true for the second case? I'd expect it to either fail or succeed on both consistently.

I guess because it just looks at the type of the `+.a` as a whole instead of the faces individually?

Would love for the second case to work if types actually line up, but also happy to take suggestions on how to avoid going into `?-` cases just to access `x.a`...

**Comment by ohAitch** [comment]
Yeah, it looks at the type of +.a as a whole: in the second the _axes_
don't line up, x is +.a in the %f case and +<.a in the %b one. You need the
?- bc you can't actually access "just" x without reading -.a

It should work fine for e.g. [%f x=@ ~]

**Comment by philipcmonk** [comment]
Yeah, it's not just the type of the result that has to line up.  The generated nock has to be identical, which means the axes have to be the same.

**Comment by Fang-** [comment]
> It should work fine for e.g. [%f x=@ ~]

```hoon
> %.  f+[5 ~]
  |=(a=$%([%f x=@ ~] [%b x=@ y=@]) +(x.a))
6
```

Huh, neat.

I was gonna suggest a (probably unacceptable) version of `$%` that pads all types with `~`s so that the axes line up, but you'd still need to pad all your nouns with the `~`s too. That's not clean at all!

So whenever I have a `+$ action-on-path $%([%a =path] [%b =path =@ud] [%etc =path =@p])` I'll need to get path from every set of axis-identical options separately? That's less bad already, but still feels very anti-fun.

**Comment by ohAitch** [comment]
I mean, if it's truly in every option, you probably just want a 
`+$  action-on-path  [=path action=$%([%a ~] [%b =@ud] [%etc =@p])]` 
instead?

**Comment by ohAitch** [comment]
(I can see some interesting cases coming up with `$<`, but even there you probably want to refactor the data structure to have a second outer `$%`, even if it's just an `each`)

**Comment by Fang-** [comment]
@ohAitch ah, so basically an `+$ action-with-path [=path rest-of-the-action]` wrapper? Seems... pretty straightforward, I think that might work!

**Comment by Fang-** [comment]
Wait, that's exactly what you said. I read that as a gate somehow. Oops!

**Comment by belisarius222** [comment]
While it is possible to access some field that comes after a tag in a tagged union if all forks have that field in the same axis, I think it's a bad practice to rely on that.  Instead, you should use one of two patterns:

1) If the contained type should be independent of the tag, then move that field out of the union. If there's just one field that can vary, confine the union to the tag itself, instead of using a $%.  Your example would then be [?(%f %b) x=@].

2) If the contained types happen to share a field in the same location but differ in other ways, then do a pattern match before accessing the field, even if it's not strictly required.  This makes your code less brittle.  It falls under the category of avoiding abstracting incidental similarities, which I think is very important.  Never trust a cute abstraction.

Just because two data structures share a field doesn't mean that field should be interpreted the same way.  It also doesn't mean you should rely on that field being in the same spot forever, so if you write code that does depend on that, you'll just have to remove the abstraction later.

For example, the $icebreaker datatype might look like [name=@t length=@ud draft=@ud nuclear=?], while an employee datatype might look like [name=@t salary=@ud start-date=@da].  Sure, they both have a .name at axis 2, but we shouldn't rely on that, since these two types will vary independently.  Next month we'll have to factor the employee's .name field into [first=@t last=@t middle=@t], and our clever +with-name mold builder gets deleted.

—
~rovnys-ricfer
https://urbit.org

**Comment by ohAitch** [comment]
Yup! I think furthermore I'd push for an explicit `[=action =path]` in most cases over the three word name, but I can see keeping them together under one wing being useful occasionally.

**Comment by Fang-** [comment]
Very fair @belisarius222! My use case is much more tightly related than your example, but I feel you on not relying on it regardless. `[x=@ rest-of-the-type]` seems obvious in hindsight, and is probably the superior solution for me.

Closing, unless someone wants to argue that we should actively make the first case from the issue OP fail to compile.
