### ISSUE TITLE
Star sync hiccup

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1697]
```
; ~batten is ok
sync succeeded from %kids on ~batten to %base
[%bad-block-structure %head 1 1]
[%err [~ u=[p=17 q=1]]]
[%bad-block-structure %head 1 1]
[%err [~ u=[p=17 q=1]]]
[%bad-block-structure %head 1 1]
[%err [~ u=[p=19 q=1]]]
[%bad-block-structure %head 1 1]
[%err [~ u=[p=19 q=1]]]
> :publish &publish-action [%serve %the-new-era]
>=
sync succeeded from %base on ~minder-folden to %kids
sync failed from %base on ~minder-folden to %home
please manually merge the desks with
|merge %home ~minder-folden %base

error code: %mate-conflict
[p=~minder-folden q=%base]
[p=~minder-folden q=%home]
[%ud p=5]
/app/chat/js/index/js
```

**Comment by joemfb** [comment]
This is a merge conflict between %home and %base (ie, there are changes on your %home desk that didn't come from your %base desk, plus new changes on your %base desk. The changes are in conflict with each other, so clay doesn't know how to automatically combine them).

The merge can be forced (by telling clay to choose the changes from one side or the other). The file in question is the web-chat JS bundle, so there shouldn't be any issues just choosing the version on %base (ie, the new OTA update). To do that:

 ```
|merge %home our %base, =gem %that`
```

**Comment by custom-jonathan** [comment]
Did that and got this:

```
> |merge %home our %base, =gem %that
>=
merged with strategy %that
```

**Comment by custom-jonathan** [comment]
UPDATE: Seems I posted a little early. It's still spinning on ```<<behn>>``` and giving me stuff like this:

```
> |merge %home our %base, =gem %that
>=
merged with strategy %that
[ %gall-pulling-20
  526
  [~ u=[p=~winter-paches q=/collection/the-new-era]]
  [~ u=[i=/g/sys/req/~winter-paches/publish/13 t=~[/a/~minder-folden/~winter-paches/g/ge/publish //ames]]]
]
[%canceling-cancel [i=//http-server/0v11.mooek/83/28 t=~]]
[%tang /~minder-folden/home/~2019.9.5..19.47.43..bb3a/sys/zuse ~ragsur-moppem]
```

I'll update when behn stops.

**Comment by vvisigoth** [comment]
Closing this as it seems resolved (even though that %gem nuked all of ~minder's userspace)

**Comment by joemfb** [comment]
`%that` discards state above and beyond the individually-conflicted files? That's a huge problem! And I'm sorry, @custom-jonathan, for leading you astray.

In the meantime should `:publish` use another desk for posts? We often need to be able to force-merge to get back to a working state.

**Comment by custom-jonathan** [comment]
S'all good @joemfb. I had a copy of that directory downloaded to my laptop so it was a _relatively_ easy fix.

**Comment by philipcmonk** [comment]
Yes, %this and %that are as described here: https://urbit.org/docs/learn/arvo/clay/#merging.  Like git's "theirs" merge strategy, not the "--theirs" conflict-resolution option to the "recursive" merge strategy.  Obviously, it would be nice if we had the other version as well, but that's less important than what we have now because what we have is simpler and really can't go wrong.

You should be able to access the old files if you know what version number it was or what time it was.  If you know the version number was, say, 50, use:

```
|mount /=home/50 %home-version-50
```

And it'll show up in your pier at home-version-50.  If you want what was there six hour ago, try:

```
|mount /=home/(scot %da (sub now ~h6)) %old-home
```

I should warn you that although I just tried and these work for me, I don't think anybody's used this feature in years.
