### ISSUE TITLE
Anonymous ship rebooting & general azimuth usability

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#1698]
I have spent some time trying to change keys of my planet today. With the limited time I had, I walked away with the impression this part of Urbit have become much more complex than it used to be. 

I realize what I am going to write below is more of a rant than a real issue, so you are free to close it. 

* * * 
Basically for any Urbit identity manipulations you need to spend money per ETH tx. That's the price we pay in exchange for strong tamper-proof storage guarantees for Urbit identities. So far so good. But it used to be than general promise of Urbit-style computing was to eradicate accumulating complexity at the user level as much as possible. Now, maybe one could consider key management as not really part of daily urbit usage routine (but clearly identity as it stands is the heart of Urbit). 

There is an additional layer of complexity mastering of which we asks of Urbit users, on top of everything, and that is all the cruft of centralized ETH gateways. Maybe in the far distant future 
there will be a way to obtain ETH tokens just like that but for now I was asked for my photo and id card, or asked to pay 10x the market rate (and still requiring my credit card number). 

Please don't dismiss this with "we will send you a little ETH", since this is not a central issue.
I am more concerned that for the foreseeable future we have for better or worse made Urbit absolutely reliant on the user having access to ETH ecosystem. Of course all this was expected since the bets were placed on azimuth being the way forward, but my feeling is that it is turning out to be much less user friendly than I imagined.

All this is subjective, and maybe in XXI century everyone has ETH stashed in the back pocket, but I missed on this particular revolution and for now the identity vultures are circling around me, while I just wanted to get my ship back. 

I don't know what is the sentiment up there, but I for one would appreciate some thinking towards do we really want for Urbit to stay this way; I remember originally blockchain thing was 
supposed to be proviso for the transition period, where Urbit is too fragile to store the crucial data , but on the other hand I have never seen any clear plan how do we go back. For instance, what would it take for us to say Urbit is finally ready. Is there some clear line before us?
I imagine according to some, ETH might be ahead of us for a very long time (billions spent, much larger user base, regular code reviews etc.)
* * *

In the meantime, I will just use another fresh ship, and *try* to get some ETH somewhere.

**Comment by galenwp** [comment]
You correctly point out the compromise here: if we want identity to be cryptographically real, we need a system for registering it that's reasonably secure. ETH appears to be the most secure general-purpose blockchain. Unfortunately, that means we end up with user experience issues like you describe. 

Ultimately, we care about the user experience more than anything. That's the point of this whole 'reinvent computing' thing anyway. We want the experience to be incredibly simple. So, how can it be improved?

Splitting that question apart, I think there are two important issues here — what should we have done, and what should we do going forward. I'll try to answer both.

What we should have done, or rather, what I wish we had done (ignoring all practical constraints) is  to simply populate the wallet of every ship we issued initially with enough ETH to perform a bunch of transactions. This is the cost of using the Ethereum chain — and I don't like the idea that we simply offloaded those issues onto everyone else. 

The more practical take, I think, is that we simply didn't understand them deeply enough or communicate them well as a part of the transition. This is something that could have been much better documented. And, in some cases, it's true that 'we'll just send you a little bit of ETH' was our way around this. It's clearly not a sustainable solution. But we often take those options since we're also trying to build an entire stack. It's tough to pay attention to everything.

So, what do we do?

I think we can correct the second mistake mentioned above — and try to thoroughly document how to make this process as easy as possible. But let's dig in to a few longer term solutions.

Eventually, it's nice to imagine Urbit being entirely self-hosting. That is, the Azimuth registry should simply be something like an Arvo-native chain of some kind. But that's (a) a reasonably large project on its own and (b) gated on Arvo being truly secure, which is also quite a large project. This gets discussed around the office from time to time. It's definitely possible — but it's a ways off.

In a world where we still use ETH, I think this can be made much simpler for anyone buying a new planet. That is, whoever you buy the planet from should (as a matter of course) populate the planet wallet with enough ETH for quite a number of key rotations. If I buy a planet for $10, $2 of that could show up in my wallet to cover future gas costs. (This ignores potential regulatory issues, of which there are probably many.)

Cycling your keys should be much more rare than it is today. We, of course, can't predict how often you may need to do it for security reasons. But at the moment we still see people going through the 'individual breach' because of stability issues we'd really like to resolve. 

Lastly, we have a wholly redesigned Bridge that has a 'gas tank' function that covers some of these costs *in specific cases*. This appears to be the norm — albeit an incredibly annoying one — that we tried to follow. Looked at from a broader perspective, the cost of onboarding people into the network is worth it to us. We do want people to use the system. 

Others may have better ideas, and I'd be glad to hear them. We really do care about making the user experience straightforward. But I do think living on Urbit today is a bit like living in California in the 1760s. There are lots of things about it that are uncomfortable.

**Comment by joemfb** [comment]
Entirely apart from the greater strategic and architectural questions pertaining to Azimuth, the current setup can be really confusing in some basic ways. Several people (some already familiar with Urbit) have run into issues and simply deleted the pier and tried to boot a new one, without cycling their keys or individually breaching. The simple existence of a key file makes it natural to assume that such an action would be valid.

What's more, we know boot into a fully-functioning ship, regardless of whether we're able to communicate over the network. When someone wrongfully tries to boot a ship that's previously been booted in an era, there's no indication that they've done something wrong. Even worse, while they won't be able to talk to any ships they previously talked to, they *will* be able to talk to new ships. The old approach with tickets (and without userspace in the pill), whatever its faults, didn't have either of these problems.

The basic problem is that Azimuth, while correct and meaningful in and of itself, contains insufficient data to validate or contraindicate that a given point/ship/keypair is in state where it can correctly be used to boot a new pier. That's a determination that can only be made from historical ames state. Specifically, the criteria is this: has this keypair already been used to boot a ship, and, if not, is it discontinuous with the last one that has? Storing this network state in Azimuth would have solved this problem, but at the unacceptable cost of a) much tighter coupling between Urbit and Ethereum and b) dramatically data state in Azimuth.

The best thing to do (IMO) would be to contact one's sponsor during pre-boot validation and confirm that the keypair can be used to boot a new ship. This was planned, but pushed off due to a variety of technical difficulties. The next best thing to do might be to (sadly) remove userspace from the pill. If one booted a ship in an invalid scenario (per the criteria above), that ship would simply never finish booting.

**Comment by ohAitch** [comment]
To compromise slightly on removing userspace from the pill: removing the userspace _desk metadata_, while still pre-populating the blob store, would enable the desired "only ever start a ship off its parent's HEAD revision of %kids / if the parent agrees to provide that" flow, while still avoiding transferring large quantities of data over ames. (Especially if directory entries are themselves in the blob store, but that's a secondary concern)

Possibly you could even keep it physically around entire for use by galaxies and comets, but discard  that during early boot for ticketable ship classes…

**Comment by philipcmonk** [comment]
Of course, we aren't actually smart enough to recognize that they already have the blobs, so we send them anyway (unless we ourselves sent them those blobs).

**Comment by ohAitch** [comment]
Oof, not so much a gitlike sync negotiation protocol then? I stand corrected.

**Comment by joemfb** [comment]
I think this falls under "pull-requests welcome!" ;)

**Comment by njarboe** [comment]
I know this is a pretty old issue, but I have been trying to boot up an old planet that I was using before the ETH tie in, and have have also found it difficult to get it booting. I need to get it gassed up and figure out how ether works. I have my points full info, so I should be able to figure it out eventually, but would like to check out the new OS1 and use my old planet for the Hoon School.

**Comment by philipcmonk** [comment]
Tlon still has records for people who never claimed their assets on ethereum, we should be able to help you if you email support@urbit.org.
