### ISSUE TITLE
Notebook formatting 

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1711]
When I try to make headers, I've been trying `## header` to make an H2 header, and I get an error return. But when I use `;h2:` it works, but I can't get all h1 through h6 to work using the `;Hn:` formatting either.

**Comment by jfranklin9000** [comment]
`# headers` need a blank line following them.  This is considered a bug in the Udon parser.

I just tried headers using Sail and they worked for me:

<img width="845" alt="headers" src="https://user-images.githubusercontent.com/15039850/64552113-31c38700-d2fc-11e9-8bf5-bcdf83914074.png">

(I used `|static` instead of the Publish app to test this.)

**Comment by custom-jonathan** [comment]
Two enters after the header, then? I've been doing the header, then hitting enter once. That's my problem?

**Comment by jfranklin9000** [comment]
Correct.

```
# header
this is a parser error

# header

this is ok
```

**Comment by custom-jonathan** [comment]
Just tried this out and it worked:

```
;h1: How does this one work?

;h2: How about this one?
;h3: A single line break?
;h4: This is a fourth header
;h5: This is a fifth header
;h6: This is a sixth header.
And some normal text just for shits and giggles.
```

**Comment by jfranklin9000** [comment]
Right, Sail headers (`;h1: header`) don't need a trailing blank line, Udon headers (`# header`) do.

**Comment by vvisigoth** [comment]
Going to close this because it's a known issue.
—
~poldec-tonteg
http://urbit.org
