### ISSUE TITLE
Slow syncing %clay files between fake ships

### ISSUE THREAD

**Issue by yosoyubik** [urbit/urbit#1796]
I have a fake ~zod and ~marzod running the same gall app. 

When committing a change to a file in clay (a tile JS file, currently at revision 145) with %base mounted, the sync happens fast there, but on ~marzod, it can take up to couple of minutes, getting stuck showing`«behn»` at this point in clay: 
`sync succeeded from %kids on ~zod to %base` 
and another minute or two here: 
`sync succeeded from %base on ~marzod to %kids`
until the sync happens in %home and the new version of the app starts running again.

I've tried reloading clay and washing gall, and restarting the piers but with no effect. This happens after some time, initially the syncing time was relatively fast (couple of seconds?)

**Comment by belisarius222** [comment]
Cross-ship Clay syncing is indeed slow, partly because we don't compare filesystem hashes and partly because Ames is slow.  I've actually been using the initial file sync as my primary benchmark for new Ames.  So far, it seems like new Ames is somewhere between marginally faster and twice as fast, which will help a little with this issue.

Comparing file hashes could also speed up syncing — don't send a file if the other side already has the hash.  I think it's nontrivial because Clay stores hashes of diffs sometimes too... I don't recall all the details, but it might not be as straightforward as it might seem.

—
~rovnys-ricfer
https://urbit.org

**Comment by yosoyubik** [comment]
Thanks @belisarius222. My solution has been to create new piers; it got very tedious waiting so long just to check a small frontend change. Very much looking forward to new Ames (I'll open a bottle of champagne when it arrives (: )

**Comment by philipcmonk** [comment]
The hashes are always of the actual content, not of diffs. Iow, if [%direct
A] is the same content as [%delta B %direct C], then their hash will be the
same and we'll only store one copy (whichever we saw first).

Currently our algorithm is basically "assume they have all the blobs that
were used in earlier commits on this desk and send them any new ones in the
new commit(s)". Incidentally, this is a reason we can't naively purge
foreign desk caches from clay in response to memory pressure.

The only hard part of sending only the needed blobs is that it turns the
action of "send a clay subscription update" from being one atomic action to
being a state machine with potentially multiple round trips. This isn't
that scary, but it's delicate work, and if it doesn't work right (what if
an event in the state machine crashes, say because of a ctrl-c?) it breaks
OTA updates, which could force a breach. I was dreading doing it until we
got the ph testing framework. Now I'm pretty confident you could build 5 or
6 tests that would cover the interesting cases.

**Comment by joemfb** [comment]
Closing in favor of #1489
