### ISSUE TITLE
Boot failure

### ISSUE THREAD

**Issue by kennyrowe** [urbit/urbit#1866]
Getting the below boot sequence after trying to retore `web` folder.

urbit 0.9.1
boot: home is /root/new_urbit/sicdev-pilnup  
loom: mapped 2048MB
lite: arvo formula 3b5d8a18
lite: core 52824d18
lite: final state 52824d18
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/672.481.280
boot: installed 262 jets
work: play 276293
---------------- playback starting----------------
pier: replaying events 276292 through 276316 
Assertion '(0 == u3to(u3a_fbox, *pfr_p)->nex_p) || (u3to(u3a_fbox, u3to(u3a_fbox, *pfr_p)->nex_p)->pre_p == (*pfr_p))' failed in noun/allocate.c:478

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: stream closed
pier: work exit: status 0, signal 6

**Comment by joemfb** [comment]
That assertion failure means that the memory image (checkpoint) was corrupted. The fix is to replay your event-log:

- remove the old checkpoint (the entire `sidev-pilnup/.urb/chk` directory)
- start urbit

The entire event-log will be replayed from scratch, and a new checkpoint created when finished.
