### ISSUE TITLE
Http fail

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#1900]
I'll preface this with I'm at a hotel where ports and connections can be super wonky, but I don't know enough to diagnose the issue.

I'm getting this in my client:

```
[%chat-hook-quit /mailbox/~dopzod/urbit-help]
%chat-hook-resubscribe
http: fail (5, 504): connection failure
```
Don't know if it's a hotel wifi issue, or what, but figured I'd put it here in case it's relevant.

**Comment by philipcmonk** [comment]
That says that your subscription to urbit-help died, so it resubscribed.  The most common way for that to happen is if you're offline for more than 20 messages.  At that point, ~dopzod quits queueing them up for you and just wants you to resubscribe.  If nothing's broken, then this is not a problem.

**Comment by joemfb** [comment]
The subscription relevant messages are

```
[%chat-hook-quit /mailbox/~dopzod/urbit-help]
%chat-hook-resubscribe
```

But this is a debug printf from the http-client i/o driver:

```
http: fail (5, 504): connection failure
```

It just means that an http request failed because the underlying connection failed. Whatever app/vane made the http request will get a 504 response, but currently gets no detail about the type of failure (which is why that printf is still present).

**Comment by jtobin** [comment]
I'll close this as I don't think it's an issue *per se*.
