### ISSUE TITLE
Chat messages in landscape duplicating on the sender's side.

### ISSUE THREAD

**Issue by sdubyam** [urbit/urbit#1985]
https://i.imgur.com/pGs3c1r.png
https://i.imgur.com/EH1iB7b.png

**Comment by sdubyam** [comment]
Issue is that I created a moon, balbel-dinruc-somlus-savlev, which is getting messages duplicated in the landscape chat, and new messages are calling back old messages from other senders and relisting (see images).  I created and installed three moons today on 3 separate computers, one has no issues in chat and it's perfectly normal. two have this issue with comments echoing / duplicating in a strange way.  

This happens in multiple chat rooms.

Interestingly, I do not see the messages come also in via the dojo as I usually do.

**Comment by matildepark** [comment]
Yes, I've noticed this (but didn't file x_x sorry) and it's not so much that they're duplicated being sent as the diffs being sent to the front-end are being appended as if new messages? If you refresh your browser the duplication doesn't persist, and they're not being sent twice.

My gut guess is it's something in the reducer between pending messages and incoming diffs. The "if the message you just got was a message we already have in pending state on the front-end, remove from pending state and append it as a fresh message" but it's then appending the diff with your message *again* if another message comes in. 

Your "other senders relisting" part could also be comorbid with how chat backlogs on the live network are a little broken, since our Chat changes thus far haven't been OTA'd and scrolling up just repeats the latest messages or gives an underflow error.

But, I also haven't tested. cc @loganallenc

**Comment by sdubyam** [comment]
On planet chat window (normal):

https://i.imgur.com/ZXFrRd8.png

on problematic moon chat window:

https://i.imgur.com/0vIMAE5.png

**Comment by sdubyam** [comment]
Actually with refresh it fixed the urbit-help chat but the messages from my planet into a chat room created by my planet are still duplicated on my moon's browser for that chat room.

**Comment by sdubyam** [comment]
Ah, and after refresh, I am still getting two of everything everyone says in /urbit-help
