### ISSUE TITLE
Multiple Content-Length Headers being returned from vere

### ISSUE THREAD

**Issue by bmavity** [urbit/urbit#2003]
Howdy, all. When trying to query my fake zod's landscape login endpoint, I was getting some parsing errors in node/postman. After further investigation, it turns out vere is returning 2 content-length headers, which causes a lot of clients to fail.

When running:
`curl http://localhost:8080/~/login -X POST -H "Content-Type: application/json" -d '{"password": "lidlut-tabwed-pillex-ridrup"}' -D -`

The output is:
```
HTTP/1.1 200 ok
Date: Fri, 29 Nov 2019 17:23:18 GMT
Connection: keep-alive
Content-Length: 1817
Server: urbit/vere-0.9.2
content-length: 1817
content-type: text/html
```

**Comment by ohAitch** [comment]
I think you mean content-length

**Comment by joemfb** [comment]
It's being explicitly set in %eyre, and again in the http i/o driver (via libh2o). The former is correct, the latter is necessary to avoid `transfer-encoding: chunked`, IIRC. We should just filter out the first in the i/o driver to work around libh2o's quirks. Ie, this should be fixed in `vere/http.c`.
