### ISSUE TITLE
Chat subscription event error

### ISSUE THREAD

**Issue by xiphiness** [urbit/urbit#2070]
This was after joining a few channels, not quite sure how to reproduce.

```
%chat-hook: got ack for nonexistent subscription
[p=~paldev q=%chat-hook]: /backlog/~paldev/nopub/0
wire=[i=%~.out t=[i=~.~paldev t=[i=~.chat-hook t=/backlog/~paldev/nopub/0]]]
  out
{ [p=[wire=/permissions ship=~sarpen-laplux term=%permission-store] q=[acked=%.y path=/updates]]
  [p=[wire=/mailbox/~risruc-habteb/watering-hole ship=~risruc-habteb term=%chat-hook] q=[acked=%.y path=/mailbox/~risruc-habteb/watering-hole]]
  [p=[wire=/mailbox/~paldev/books ship=~paldev term=%chat-hook] q=[acked=%.y path=/mailbox/~paldev/books]]
  [p=[wire=/invites ship=~sarpen-laplux term=%invite-store] q=[acked=%.y path=/invitatory/chat]]
  [p=[wire=/mailbox/~dopzod/urbit-help ship=~dopzod term=%chat-hook] q=[acked=%.y path=/mailbox/~dopzod/urbit-help]]
  [p=[wire=/mailbox/~paldev/nopub ship=~paldev term=%chat-hook] q=[acked=%.y path=/mailbox/~paldev/nopub]]
}
crud: %hole event failed
```

With repeated ``crud: %hole event failed``. After making knob for %hole loud, I get:

```
crud: %hole event failed
bail: exit
%failed-jack
[%failed-take %g]
[ %failed-swim
  %g
  %g
  [ ~
    / use
      permission-hook
      ~sarpen-laplux
      out
      ~paldev
      permission-hook
      permission
      chat
      ~paldev
      nopub
      write
  ]
]
[%swim-take-vane %g %unto]
[%failed-slym-in %g]
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.749 3].[1.760 10]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.751 3].[1.760 10]>
[ %gall-take-failed
  / use
    permission-hook
    ~sarpen-laplux
    out
    ~paldev
    permission-hook
    permission
    chat
    ~paldev
    nopub
    write
]
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.753 3].[1.760 10]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.754 3].[1.760 10]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.755 3].[1.760 10]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.756 3].[1.760 10]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.756 7].[1.759 9]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.758 15].[1.758 53]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[643 5].[668 16]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[645 5].[668 16]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[649 5].[668 16]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[650 5].[668 16]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[659 5].[668 16]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[660 5].[668 16]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[666 5].[668 16]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[667 7].[667 43]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.179 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.181 7].[1.222 14]>
wire=/out/~paldev/permission-hook/permission/chat/~paldev/nopub/write
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.182 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.183 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.184 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.185 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.186 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.189 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.192 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.204 7].[1.222 14]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.205 9].[1.212 17]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.208 9].[1.212 17]>
/~zod/home/~2019.12.6..13.37.47..40ec/sys/vane/gall:<[1.210 9].[1.212 17]>
[ %already-acked
  %permission-hook
  [ i=%~.out
      t
    [i=~.~paldev t=[i=~.permission-hook t=/permission/chat/~paldev/nopub/write]]
  ]
  [p=~paldev q=%permission-hook]
  /permission/chat/~paldev/nopub/write
]
```

**Comment by philipcmonk** [comment]
Looks like it got a response for the "backlog" subscription when that had
already ended and it had switched to the main "mailbox" subscription. Did
this happen just once, or does it happen on a regular basis?

**Comment by joemfb** [comment]
I've got this too, but for different mailboxes. It's ongoing. I've tried leaving and joining again, without improvement (maybe related to #2068?).

**Comment by philipcmonk** [comment]
Is there any more to the error?  Maybe "got ack for nonexistant subscription".  Does it give you more info if you run `|knob %hole %loud`? (turn it off with `|knob %hole %soft`)

**Comment by joemfb** [comment]
They're all identical:

```
crud: %hole event failed
bail: exit
%failed-jack
[%failed-take %g]
[ %failed-swim
  %g
  %g
  [ ~
    / use
      permission-hook
      ~master-morzod
      out
      ~ship-redacted
      permission-hook
      permission
      chat
      ~ship-redacted
      mailbox-redacted
      read
  ]
]
[%swim-take-vane %g %unto]
[%failed-slym-in %g]
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.749 3].[1.760 10]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.751 3].[1.760 10]>
[ %gall-take-failed
  / use
    permission-hook
    ~master-morzod
    out
    ~ship-redacted
    permission-hook
    permission
    chat
    ~ship-redacted
    mailbox-redacted
    read
]
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.753 3].[1.760 10]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.754 3].[1.760 10]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.755 3].[1.760 10]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.756 3].[1.760 10]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.756 7].[1.759 9]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.758 15].[1.758 53]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[643 5].[668 16]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[645 5].[668 16]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[649 5].[668 16]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[650 5].[668 16]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[659 5].[668 16]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[660 5].[668 16]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[666 5].[668 16]>
/~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall:<[667 7].[667 43]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.179 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.181 7].[1.222 14]>
  wire
/ out
  ~ship-redacted
  permission-hook
  permission
  chat
  ~ship-redacted
  mailbox-redacted
  read
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.182 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.183 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.184 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.185 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.186 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.189 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.192 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.204 7].[1.222 14]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.205 9].[1.212 17]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.208 9].[1.212 17]>
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.210 9].[1.212 17]>
[ %already-acked
  %permission-hook
  [ i=%~.out
      t
    [ i=~.~ship-redacted
        t
      [ i=~.permission-hook
        t=/permission/chat/~ship-redacted/mailbox-redacted/read
      ]
    ]
  ]
  [p=~ship-redacted q=%permission-hook]
  /permission/chat/~ship-redacted/mailbox-redacted/read
]
  /~master-morzod/home/~2019.12.6..17.59.05..f1cc/sys/vane/gall
  <[1.211 9].[1.212 17]>
```

**Comment by joemfb** [comment]
FWIW, I get updates from and can post to this channel, interspersed with these crashes.

**Comment by philipcmonk** [comment]
(was looking at this via email and didn't see @xiphiness's edit above)

These are two separate issues, though possibly from the same cause.  It sounds like the "got ack for nonexistent subscription" crash happened once on `%chat-hook`, and then now it's crashing repeatedly on receiving an already-acked subscription to `%permission-hook`.

I wish I knew what caused the two separate acknowledgments to arrive.  I don't know any way to induce that, it's supposed to be impossible.  However, I've been thinking it should probably be considered possible, since Gall may need to kill a subscription that hasn't even been acked yet but the message has been given to ames.  If the message is eventually received by the other ship, then it'll give another ack, which we should ignore (or maybe bounce back with a `%leave`?).

Since all that's happening here is that we're receiving a positive acknowledgment for a subscription where we've already received a positive acknowledgment, I think it's acceptable to no-op.

**Comment by joemfb** [comment]
I have an even more basic question. This is the trace of a crashed %hole card, not the trace of the %hear card that preceded it. Why is that resulting in a move to %gall? Shouldn't we be just nack'ing if this is a forward flow, and performing a two-way kill if it's a backward flow?

... @belisarius222,

**Comment by philipcmonk** [comment]
I thought maybe it was performing a two-way kill and we were crashing while handling that, but yeah, it's actually a positive acknowledgment to Gall.

Can you run `|verb` and see what happens before it crashes?

**Comment by joemfb** [comment]
Looks like you're right:

```
["" %unix p=%hole //ames ~2019.12.10..08.32.39..2cb4]
["|" %pass [%a %d] [%flog /qos] [i=//ames t=~]]
[ "|"
  %give
  %a
  %done
  [i=/g/sys/way/~botter-nidnul/permission-hook/watch t=~[/g/use/permission-hook/~master-morzod/out/~botter-nidnul/permission-hook/permission/chat/~botter-nidnul/extreme-urbiting/read /d //term/1]]
]
["||" %give %g [%unto %watch-ack] [i=/g/use/permission-hook/~master-morzod/out/~botter-nidnul/permission-hook/permission/chat/~botter-nidnul/extreme-urbiting/read t=~[/d //term/1]]]
["" %unix p=%crud //ames ~2019.12.10..08.32.39..2cb4]
["|" %pass [%a %d] [%flog /crud] [i=//ames t=~]]
crud: %hole event failed
```

If I'm reading it correctly, `+ap-specific-take` doesn't check for the `%watch-ack` error case.

Also worth noting, I turned on various `|ames-verb` levels, including `%msg, but none of them printed anything for these %hole cards.

**Comment by philipcmonk** [comment]
The ones I'd think might print something are `%msg` and `%snd` (prints acknowledgments).

Our `%hole` handling is a little subtle.  Basically, in `+on-hear-shut-packet`, if it's a fragment we send it to the message sink (receiver), but if it's an ack we send it to the message pump (sender, so it knows to maybe send another fragment).  In `+run-message-sink`, after running the message sink exactly as though it were a `%hear`, we translate any `%boon` into a `%lost` and bounce any `%plea` into a nack.

However, as this comment correctly indicates, we don't specially handle the failing case in `+run-message-pump`, so we crash in the same place.

https://github.com/urbit/urbit/blob/69c2f5517cd6fa6b70b684eb32b07368d473bfd4/pkg/arvo/sys/vane/ames.hoon#L1887-L1889

Ultimately, this means if you consistently crash while handling an acknowledgment, the flow is stuck in this way (at least you get a useful stack trace, though).  Is there anything else we could do?  Ames gives you a guarantee that you'll get `%done`s in order, so if you won't take the `%done`, it can't keep going, right?

I'll PR a change to turn this crash into a no-op, but we should continue to think if there's any other way to handle this, and if not, then make sure we don't consistently crash while handling acknowledgments (which shouldn't be too hard, since the gall code isn't too big, and user code is in a +mule).

**Comment by joemfb** [comment]
User code can still `bail: fail`, but that's a larger conversation for another time.

I misread `+ap-specific-take`, it correctly branches on `p.sign`. So it seems that %ames is not correctly sending `[%done (some *tang)]` as a result of this %hold card. It should be, right? We already crashed trying to handle this %watch-ack, so the %hole card should be propagating the error.

**Comment by joemfb** [comment]
I re-read that card definitions and understand now. The error in %done is the remote naxplanation, not a channel to inform us of our own crash. I think you're right, the only thing to do here is no-op. 

Is there any way for the peers to disagree about the cardinality of subscriptions? The duct is uniquely identified on each side, so it would seem that the repeated %watch-ack shouldn't imply duplicated remote subscriptions, just erroneous duplicate gall-level acknowledgement.

**Comment by philipcmonk** [comment]
Yeah, there can only ever be zero or one subscription per duct/ship/target-app, so either it's there or not.  If we know we have a subscription on a duct/ship/target-app (even if it's not acked yet), we don't let you create another one (this is the "subscribe wire not unique" error).  So the only way I can think of this happening is if subscriptions get started and stopped in quick succession.

My best guess is that a `%kick` somehow arrived while we had an unacknowledged subscription open.  It's not clear what's the right solution to this.  We can't assert when we receive a `%kick` that we have an acknowledged subscription because we might not have a subscription at all -- it's not uncommon for multiple `%kick`s to come in on the same subscription, since several things can independently trigger a `%kick`.

Arguably a kick on an unacknowledged subscription implies a negative watch-ack, though probably it actually implies a positive watch-ack followed by a kick.

I think the most confusing part of this flow is the potential for interaction between different lifetimes of a subscription -- a kick or acknowledgment meant for one lifetime can hit another.  These lifetimes are often one right after the other because we immediately resubscribe.  I suspect the thing to do is require the same uniqueness conditions, but internally add a nonce to each new iteration of the subscription (included in the gall-internal wire), so if an answer comes back to a previous iteration of the subscription, we can recognize that.  I think this will also solve the theoretical "spurious multiple negative acks" situation that @belisarius222 and I identified a while back, though we haven't seen any examples in the wild (unless this is one).

The PR as written is fine and should solve the problem.  I'll try to add this nonce soon, which should eliminate these conflicts.
