### ISSUE TITLE
eth-watcher fail

### ISSUE THREAD

**Issue by kennyrowe** [urbit/urbit#2099]
Getting `eth-watcher failed` when booting a new ship for the first time. Not able to connect to the network.

Using current version 0.10.1
%base-hash 0v1m.7thj6.bt9f0.kecmn.psn12.t5nic.mev4p.oe12v.erhcb.b9ddc.of4bg

```
eth-watcher failed; will retry
%build-thread-error
ford: %core on /~dalten/home/0/ted/eth-watcher/hoon failed:
%plan failed: 
ford: %core on /~dalten/home/0/lib/ethio/hoon failed:
ford: %plan failed: 
ford: %ride failed to compute type:
ford: %slim failed: 
nest-fail
/~dalten/home/0/lib/ethio/hoon::[231 5].[232 58]>
/~dalten/home/0/lib/ethio/hoon::[230 3].[234 54]>
/~dalten/home/0/lib/ethio/hoon::[229 3].[234 54]>
/~dalten/home/0/lib/ethio/hoon::[228 3].[234 54]>
/~dalten/home/0/lib/ethio/hoon::[227 3].[234 54]>
/~dalten/home/0/lib/ethio/hoon::[10 1].[235 3]>
/~dalten/home/0/lib/ethio/hoon::[7 1].[235 3]>
/~dalten/home/0/lib/ethio/hoon::[5 1].[235 3]>
/~dalten/home/0/lib/ethio/hoon::[4 1].[235 3]>
/~dalten/home/~2019.12.14..21.18.23..b533/sys/vane/ford:<[4.828 18].[4.828 59]>
```

**Comment by kennyrowe** [comment]
```
> +trouble
[ [%base-hash 0v1m.7thj6.bt9f0.kecmn.psn12.t5nic.mev4p.oe12v.erhcb.b9ddc.of4bg]
  [%home-hash 0v1m.7thj6.bt9f0.kecmn.psn12.t5nic.mev4p.oe12v.erhcb.b9ddc.of4bg]
  [%our ship=~dalten point='9632' life=[~ 1] rift=[~ 1]]
  [%sponsor ship=~ten point='160' life=[~ 4] rift=[~ 1]]
  [%dopzod ship=~dopzod point='4608' life=~ rift=~]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by pimato** [comment]
https://github.com/urbit/urbit/issues/2100

**Comment by faso** [comment]
Same thing here

**Comment by mclucario** [comment]
Same here.

**Comment by ngzax** [comment]
same. i am getting lots of eth-watcher fails on both my planet and star.

**Comment by vvisigoth** [comment]
@philipcmonk @belisarius222 do we need these piers or do we have a lead on this bug ?

**Comment by matildepark** [comment]
I think it’s pretty reproducible. Booting a fresh ship would do it. I believe PM said a fresh pill would fix it going forward, but I don’t know how to solve the issue for people already running into this.

**Comment by kennyrowe** [comment]
I tried a few experiments trying to restore older versions of `ethio.hoon` and `eth-watcher.hoon` but that didn't work. Might try and just remove the last commit to `eth-watcher` that added a nonce function.

**Comment by philipcmonk** [comment]
This solves it for me:

```
|wipe-ford
|start %goad
```

I'll push a fixed pill soon which will fix this for new people.  People who booted into this broken state should run the above two commands.

This is a ford cache problem.  @belisarius222, why doesn't ford recognize that a change to zuse should invalidate its cache?  Why doesn't it throw away it's cache when it gets reloaded?  Also, why doesn't ford say that all apps depend on zuse/arvo/hoon?

**Comment by pimato** [comment]
@philipcmonk :

<img width="470" alt="Bildschirmfoto 2019-12-17 um 00 40 44" src="https://user-images.githubusercontent.com/5337809/70952283-0fad7380-2066-11ea-9a80-d6db7f393b6d.png">

**Comment by philipcmonk** [comment]
whoops, needs a percent argument.  How about this:

```
|wipe-ford 100
|start %goad
:goad %go
```

**Comment by belisarius222** [comment]
Ford certainly should say that all apps depend on sys/hoon.hoon, sys/arvo.hoon, and sys/zuse.hoon.  I'd be pretty surprised if it doesn't, since those files are in the "reef" that Ford uses as the initial compilation subject for %core builds.

I'm not sure we need to throw away old cache lines when Zuse reloads, since Ford's dependency tracking system should know that anything that depended on Zuse now has a changed dependency.  The "cache promotion" logic that uses old cache lines as new ones should recognize this just like any other changed dependency and not propagate the cache.

Maybe there's a bug in this logic.  The error was from rebuilding a live build, and for some reason clearing the cache fixed it.  Failure to propagate a change to Zuse could exhibit this behavior, since cached build results built with old Zuse would still show up as valid.

Clearing the cache on +load shouldn't be strictly necessary unless we change Ford in a way that will break referential transparency — most don't.  It's probably safer, though, as long as clearing the cache doesn't cause bail:meme on |reload.

—
~rovnys-ricfer
https://urbit.org

**Comment by philipcmonk** [comment]
has it ever been the case that changing zuse.hoon caused all your apps to reload?  If that's supposed to have been happening, then it's been a bug this whole time

**Comment by belisarius222** [comment]
Yes, that should happen... so you're right, this is broken.  

—
~rovnys-ricfer
https://urbit.org

**Comment by philipcmonk** [comment]
adding %wipe 100 to goad crashes in ford on line 1791, probably on rebuilding the apps.  If I take away the !. in ++reduce, the crash is on the ?< in +apply-blocks.

**Comment by belisarius222** [comment]
Looks like somehow Ford thinks a build blocked on a sub-build that was already completed and in the build graph. The assertion is there as a sanity check that this never happens, and I've never seen it throw before (although maybe that's just because of the !.).

I'll look into this after the ames packet queue bug.

—
~rovnys-ricfer
https://urbit.org

**Comment by joemfb** [comment]
I think crashes in %drip updates from %clay invalidate those kinds of assumptions.

**Comment by belisarius222** [comment]
Yeah, I think you're right.  I think I'll go ahead and add some code to Ford to clear the build graph on +load and whenever Hoon, Arvo, or Zuse change.  That should be dumb and safe, which are probably good adjectives for this part of the system.

—
~rovnys-ricfer
https://urbit.org
