### ISSUE TITLE
bail: meme error

### ISSUE THREAD

**Issue by ryjm** [urbit/urbit#2108]
Getting a `bail: meme` error on start whenever i try to spin up ~littel-wolfur now. Tried on both my DO instance and locally. 

Not sure if this is enough information to debug - I was getting tons of `crud: %hole` errors before this started happening. 

![image](https://user-images.githubusercontent.com/2065299/70953840-ce529f00-2038-11ea-90b8-ed88ce5c21ea.png)

**Comment by joemfb** [comment]
@ryjm, we're properly detecting memory pressure, and trying to reclaim space by compacting/deduplicating, but running out of memory while doing so ... This is surprising to me, I would've expected the ~500MB of working memory to be more than enough for this compaction.

If you email support@urbit.org, we can coordinate delivery of your pier so that I can look further.

**Comment by vvisigoth** [comment]
Yeah, that is interesting. Email us.

**Comment by joemfb** [comment]
Closing in favor of #4182
