### ISSUE TITLE
Is ok, still trying

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2155]
![image](https://user-images.githubusercontent.com/51895363/71860175-74814a00-30b7-11ea-90ab-1a5e8b15aea1.png)
This is non-stop in my client.

**Comment by Fang-** [comment]
This is generally expected behavior when serving data to many peers (hosting a chat, for example). If it can't get a new message out to them within 30(?) seconds, then it'll print "not responding", but then switch back to "is ok" as soon as they ack it. Sometimes ships are slow, sometimes people are offline... those 30 secs are pretty easy to hit.

**Comment by custom-jonathan** [comment]
That makes a lot more sense. Thought it was a problem; now I'll adjust my experience accordingly!

**Comment by matildepark** [comment]
Another verbosity issue, but this specific issue is a non-issue.
