### ISSUE TITLE
%ames-crash-on-packet-from

### ISSUE THREAD

**Issue by risruc-habteb** [urbit/urbit#2156]
Experiencing many errors in my stream, especially
`%ames-crash-on-packet-from`
and 
```
%failed-jack
[%lal %a %d]
[%failed-take %a]
[%failed-swim %a %$ ~]
[%swim-call-vane %a %soft]
[%failed-slym-in %a]
```
and 
```
eth-watcher failed; will retry
%false-start
nest-fail
/~risruc-habteb/home/0/ted/eth-watcher/hoon:<[12 5].[12 26]>
/~risruc-habteb/home/0/ted/eth-watcher/hoon:<[12 1].[29 3]>
/~risruc-habteb/home/0/ted/eth-watcher/hoon:<[11 1].[105 3]>
/~risruc-habteb/home/0/app/spider/hoon:<[308 21].[308 34]>
```

It's likely I've screwed something up myself, as I'm on the correct base hash and my sponsor is ~marzod.
I'm happy to personal breach, but thought to ask first.

Here's a somewhat longer log including +trouble output.
https://hastebin.com/tehadapaso.rb

**Comment by philipcmonk** [comment]
The `%ames-crash-on-packet-from` is probably due to old keys because of the eth-watcher crashes.

Since your base hash is correct, most likely for some reason your apps didn't get correctly reloaded.  If that's the case, you can probably run `:goad %go` to reload all your apps, and then wait five minutes to see if eth-watcher still crashes.  If that command fails, try `:goad %force`.

**Comment by risruc-habteb** [comment]
`:goad %go` did not work, but` :goad %force` did.
thank you.
