### ISSUE TITLE
Ford crashes during new publish state transition

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#2180]
When I try to `|commit %home` the files in the branch `ixv/publish-remix` into a ship based on master, which has already existing publish notebooks something crashes. These crashes do not happen if the ship does not have a notebook.

In the change, publish does the following things in the on-load arm:
- kills old ford builds
- kicks old subscribers
- leaves old subscriptions
- moves old publish files
- creates groups for notebooks
- creates invite store entry
- subscribes to permission-store, and invite-store
- reads from clay
- sends invites to old subscribers

It seems the problematic part of this is the killing of old ford builds.

Something about these crashes is non-deterministic, because over the course of many reproductions it crashes differently.

The first crash is this: https://pastebin.com/FSBVs6fJ
The second crash is this, and this one happens over and over again: https://pastebin.com/xuggUpBN
The third crash is this: https://pastebin.com/KgD0RKmF

The third one is interesting because it appears to be depending on an old version of the publish sur file.

**Comment by philipcmonk** [comment]
Publish makes heavy use of Ford's ability to include dependencies.  @belisarius, want to take a look at this?

**Comment by belisarius222** [comment]
Yeah, I'm taking a look at this tonight.

**Comment by Fang-** [comment]
@ixv We got an (nondeterministic) compilation success upon committing the new publish files, which proceeded to run the `+on-load`. This resulted in the following output:

```hoon
error in %publish
%load-failed
! /ct/~zod//~2000.1.1/web/publish
/ct/~zod//~2000.1.1/web/publish
error in %publish
%arvo-response
! /~zod/home/0/lib/default-agent/hoon:<[63 3].[63 5]>
! "unexpected system response %f to %publish on wire /post/urbit-only-exclusive-tweets/hilarious-guy-computing-from-boston-freaks-out-when-he-sees-urbit-explicit-language"
! /~zod/home/0/lib/default-agent/hoon:<[62 3].[63 5]>
! /~zod/home/0/app/publish/hoon:<[306 7].[306 28]>
! /~zod/home/0/app/publish/hoon:<[305 5].[339 7]>
! /~zod/home/0/app/publish/hoon:<[304 5].[339 7]>
! /~zod/home/~2020.1.14..16.26.07..02c8/sys/vane/gall:<[1.207 9].[1.207 47]>
```

(With the `error in %publish` and everything below it repeating a bunch of times.)

Looking at `/app/publish`, we can see `+on-load` calls out to `+our-beak` to build the scry paths it uses. It has access to `+our-beak`, but it lives inside a `|_` that you aren't initializing prior to calling `+our-beak` out of it. This is the class of issue that I have previously run into in #2147 (and other out-of-band cases).

(This really should give a warning of some sort I feel, but there's probably lower language-level things preventing that...)

We're still investigating the nondeterministic ford errors, but just a heads up that your current code won't work correctly even without those.

**Comment by ixv** [comment]
Oh yeah, that's already fixed. I forgot to push it, my bad. Should be good now.

**Comment by belisarius222** [comment]
Still narrowing this down, but it appears to be a bug in Ford's cache promotion logic that deletes a provisional sub-build, thinking it's orphaned, when in fact it's a real part of the build.  The sub-build gets deleted from `builds.state` but then gets run anyway.  This violates the invariant that we only ever run builds that are stored in the state, so `+reduce` crashes when trying to apply the build result.

I'm not yet sure why Ford deletes this sub-build.  I'm going to print out the provisional build tree that gets copied from the previous build to see if I can figure out how it decides to delete the build but still try to run it.

The sub-build is a `%plan` of a `$scaffold` sourced from `/lib/publish/hoon`, in multiple builds that rebuild when `/lib/publish/hoon` and `/sub/publish/hoon` change in a Clay commit.  There are a bunch of `:publish` post and comment files that get rebuilt because the renderers responsible for rendering those files import the `:publish` `/sur` and `/lib` files.  This means those files should indeed get built, meaning the bug is that the `%plan` build of `/lib/publish/hoon` gets deleted in `+gather` after being enqueued to be run.

This problem does not happen every time, which makes me suspect Ford's cache sometimes holds onto the sub-build in question, preventing this bug from manifesting.  The order of subscription updates from Clay also varies, which should be fine semantically, but obscures the source of this bug's nondeterminism somewhat.

**Comment by philipcmonk** [comment]
If you're having trouble tracking down exactly when it goes wrong, this is the kind of bug which can be profitably debugged with #2163.  You can rewind and put in printfs to bisect.

**Comment by belisarius222** [comment]
We can reliably trigger the failing event, but the complexity is in the intra-event Ford build-gathering semantics.

**Comment by belisarius222** [comment]
I was wrong earlier.  The %core build that depends on the missing %plan build depends on two different versions of it: one with a scaffold parsed from the old source, and one with a scaffold parsed from the new source.

The bug is not that we're deleting the old %plan build; that's correct, since it is in fact an orphaned provisional sub-build.  The bug is that after deleting it, we're still trying to run it for some reason.

Now we're looking into why we're gathering the old build to be run.

**Comment by ixv** [comment]
resolved in the OTA work
