### ISSUE TITLE
Dojo code entered in landscape chat does not show result in landscape

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#2257]
I have seen multiple times when someone enters code into their landscape chat properly preceeded by # and they see the output but no one else sees the output.

We just saw an instance of this in /hoontards but I have seen it else where. The command that we used most recently was

#(trim 1 "abcde")

**Comment by Fang-** [comment]
I've observed this before. I think the issue here is that, while the chat-store does [fill in the result](https://github.com/urbit/urbit/blob/master/pkg/arvo/app/chat-store.hoon#L188) for you, this happens _after_ the chat-hook has already [sent](https://github.com/urbit/urbit/blob/master/pkg/arvo/app/chat-hook.hoon#L134) the no-result-included version of your message off to whatever place you're sending it to.

As such, the fix is to make the chat-hook use `/lib/chat/eval.hoon` on any `%code` message without a result. We'll try and get this in soon!

**Comment by somlus-savlev** [comment]
Thanks!

**Comment by matildepark** [comment]
Fixed in #2258, but since it was merged to os1-rc, not master, it didn't auto-close this issue.
