### ISSUE TITLE
Error when trying to join a chat

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2506]
**Describe the bug**
In messaging, I enter a chat name and click 'Join Chat' but nothing happens. Opening the web inspector, it looks like there has been a js crash.

**To Reproduce**
1. Open Messaging
2. Click 'Join chat'
3. Enter '~dopzod/urbit-help'
4. Click 'Join chat'

**Expected behavior**
Seems like it should have just joined the chat.

**Screenshots**
<img width="1552" alt="Screen Shot 2020-03-14 at 9 33 17 AM" src="https://user-images.githubusercontent.com/1467211/76686358-f8841080-65d7-11ea-8c7f-4cabc83b9131.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser: Chrome 79.0.3945.130
 - Base hash: 0v8.rpvar.1t9h7.4es5r.irauk.niaqo.7do90.bpc1r.nihtd.ufdgt.8ehjl

**Comment by galenwp** [comment]
Entering ~/~dopzod/urbit-help seemed to work. If that's the preferred format for a non-group chat, the page should be updated to reflect this.

**Comment by matildepark** [comment]
That *is* the format for a non-group chat. The page being urbit.org? You’re right but I think we’re in the process of considering urbit-help as some sort of intro group or something. We can talk Monday and think on that and make adjustments …

—
~haddef-sigwen
https://urbit.org

**Comment by galenwp** [comment]
Well, then there are two problems:

- The join page doesn't make it clear what syntax is for what:
<img width="419" alt="Screen Shot 2020-03-14 at 9 56 35 AM" src="https://user-images.githubusercontent.com/1467211/76686659-48fc6d80-65da-11ea-93e6-0d806b34b00d.png">

- It just fails silently when you use the wrong syntax

Seems like we need to update the copy on the join page, and throw a user-level error.

**Comment by matildepark** [comment]
The user shouldn’t even have to think about the syntax and what it reflects on the back-end; they should be given a shortcode — which anyone in the group can get from the settings page — and just throw it in there.

I recall there being an error at one point but could be wrong; that’s easy to do as a handler for a rejected promise.

—
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
Replace ‘group’ with chat

—
~haddef-sigwen
https://urbit.org

**Comment by galenwp** [comment]
Well, one way or another, the instructions just have to be clear to a new user. I was just doing what I would normally do. Did the docs change?

**Comment by matildepark** [comment]
Added an issue at [docs/#820](https://github.com/urbit/docs/issues/820).

**Comment by galenwp** [comment]
Thanks!

**Comment by sipwex-barfus** [comment]
Hey y'all, came across this problem myself today as well thought I had run into another issue joining chats(which I had initially on 0.10.0 turned out to be unrelated star issues). I tried joining the chats as I had them pre-OS1 and kept getting the above error in the console. Read the above and figured it out. 

For what it's worth coming from a total "noob" I would imagine it would be easier from a UI perspective to be able to "select" an option for the type of chat(unmanaged group etc) so as to reduce the need to read/think about it from a user perspective. If there was an intuitive option/button to select the type you wish to join, the frontend could just add the prefix itself unless I'm missing something. Just figured to throw out the suggestion here in case it helps, feel free to ignore! 

Thanks again for all your hard work!

**Comment by jtobin** [comment]
I'll close this one in favour of the linked docs PR.
