### ISSUE TITLE
eth-watcher unable to complete successfully after boot on one (slow?) device

### ISSUE THREAD

**Issue by botter-nidnul** [urbit/urbit#2570]
After breaching ~botter-nidnul and booting up a fresh pier on my VPS I continued to get `eth-watcher still running; will restart` errors, was unable to update `+azimuth-block` past `6.784.800`, and `+trouble` showed `[%dopzod ship=~dopzod point='4608' life=~ rift=~]`.

Comets booted on this same VPS experience the same problem. Thinking there was a remote chance it was an AArch64 specific issue (this VPS is Cavium ThunderX based) I tried booting comets on my Raspberry Pi 4 and experienced no problems.

Then I moved an already booted pier that was up to date on azimuth-blocks to this VPS and eth-watcher runs fine without error, successfully updating the output of `+azimuth-block` as expected.

I've run ~botter-nidnul on this VPS for months, and I *think* the pier before the breach was booted on it. At least, I'd never previously experienced this problem.

My best guess as to the cause of the problem is the slowness of this VPS compared to the Raspberry Pi 4 (time to boot a `-F zod` on the VPS is about 50% greater than the RPi4, the raw clock speed of the ThunderX cores is faster than the RPi4 but the ThunderX doesn't do out-of-order execution) and that means it doesn't complete the initial block update before the timeout restarts eth-watcher.

So I assume this would be a problem experienced by other slow devices.

**Comment by philipcmonk** [comment]
That could indeed cause it.  We require it to finish in 5 minutes, which is sometimes impossible for slow machines or on flaky connections.

The 5 minutes is just that we check every five minutes so that we get breach notifications reasonably fast.  If we set that to 10 minutes, it would take an average of 5 minutes longer to get breach notifications.

What we should do is decouple these two timeouts.  Give it like 3 free passes where if it sees that it's still trying, it'll just let it go instead of restarting it.  That way it'll have 20 minutes to finish, and if it's still running then it's probably actually stuck.  Could make this configurable as well.  This shouldn't be too hard to add to app/eth-watcher.hoon.

**Comment by philipcmonk** [comment]
If you want to hack it for that specific ship, in app/eth-watcher.hoon in +wait, change `(add now time)` to `(add now (mul 2 time))`.  Or if that's not enough, multiply by bigger numbers.
