### ISSUE TITLE
Invite field won't list groups or ships

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#2657]
**Describe the bug**
When typing into the "invite" field (for example when creating a new chat) it doesn't give me any clickable options, so I can't really add anyone/anything here.

**To Reproduce**
1. Go to "new chat"
2. Type into the invite field
3. Nothing appears

**Expected behavior**
Groups and/or ship names appear, depending on what I type in.

**Screenshots**
![](https://user-images.githubusercontent.com/3829764/78285084-a83a0780-7520-11ea-9c13-d966cc4b8390.gif)

**Desktop (please complete the following information):**
 - MacOS 10.12
 - Latest Firefox
 - Base hash `0v2.iblp6...lu464`, matching latest. Hashes for `/app/chat` match between home and base, and I've `:goad %force`d already.

**Additional context**
In the browser console, `TypeError: e[1] is undefined` whenever I keypress in the invite field. ~palfun might have slightly borked metadata state (some groups are not rendering for me in the groups interface), but wouldn't expect that to fully kill the invite field.

**Comment by matildepark** [comment]
I flagged this in invite-search PR — I can fix …

— 
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
(Though note you can add whatever `@p` you typed by just pressing comma or Enter btw). It’s because it makes a set when it’s storing its index, to dedupe information … and searches through a non-existent index. I’m making a patch to use an array instead and just accept redundant info (as we now do with the group filter).

— 
~haddef-sigwen
https://urbit.org

**Comment by matildepark** [comment]
I also want to note that if you have no group associations in state, your Chat sidebar also won't work.
