### ISSUE TITLE
Chat-cli subscribe error on boot

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#2681]
Getting error `subscribe failed from %chat-cli on wire /invites` when booting for the first time.  Looks like invite-store no longer accepts this path but chat-cli still asks for it on boot.

Base hash: 4a6ue (mainnet pill) and eh7oh (solid pill for urbit-os-v1.0.11)

**Comment by matildepark** [comment]
@Fang- @loganallenc I feel like this got fixed somewhere but can't find the PR if it did.

**Comment by Fang-** [comment]
Uh, chat-cli subscribes on a sane path:

https://github.com/urbit/urbit/blob/39c707e596d2be0fc921d34ef765fb54b480b74b/pkg/arvo/app/chat-cli.hoon#L248-L250

But I'm guessing because of boot order shenanigans, the "invitatory" with that name hasn't been created when this happens, and invite-store rejects the subscription because of that. Seems like the same class of underlying issue as https://github.com/urbit/urbit/issues/2248#issuecomment-601639995 has.
