### ISSUE TITLE
group identity UI should be more accessible

### ISSUE THREAD

**Issue by syzygyzer** [urbit/urbit#2716]
I've been wondering for the past couple of weeks how to set my nickname, sigil color, etc in Landscape. I didn't ask anyone how to do so since that shouldn't be something that people need to ask about. After going to the groups screen for at least the 5th time trying to figure out where I need to click, I finally tried clicking on my sigil under Group Identity in the Groups interface, and discovered I could set my nickname there.

The fact that it took me so long to figure this out is evidence to me that it needs to be more obvious somehow. I don't have a suggestion on what to do, just relaying my experience. Perhaps no change is necessary.

I could be an outlier and clicking there is totally obvious to most people. To get some sense of this, I invite people to use :eyes: reaction on this post if you also had trouble finding this UI element the first time you went to look for it.

EDIT: This element has now completely vanished, see below https://github.com/urbit/urbit/issues/2716#issuecomment-612114147

**Comment by matildepark** [comment]
My initial thought is:  see #2714. Perhaps if it’s *our* sigil on mouseover, and it’s within a group, it has an additional “Edit Profile” button. @urcades @liamfitzgerald

— 
~haddef-sigwen
https://urbit.org

**Comment by urcades** [comment]
@matildepark Yes! Will update the design slightly to afford for this.

@syzygyzer It's not you — groups as it currently stands is actually an ancient organizational method that was derived straight from the earliest days of OS 1's design process — a lot has changed and been realized since then, and there will be pretty significant refactors to this interface in the near term, slated for a 1.1 quality of life interface improvement.

**Comment by syzygyzer** [comment]
I'm not sure whether to post this under a separate issue since it might be related to modifying your group profile. Before making this post I set my nickname in the Hoon School group. Now the Group Identity element has vanished!

![image](https://user-images.githubusercontent.com/51337059/79007112-82b48b80-7b28-11ea-8fa0-e055b607aac8.png)

This is using Brave btw.

I tried clearing my cache and loading from a different browser (Firefox) and its still gone.

**Comment by urcades** [comment]
Yeah, for some reason when one updates their Group ID, their identity gets sorted back into the list of other ships for some reason — I had meant to write up an Issue about this, but never got around to it.

A user's ID, edited or not, should be floated to the top or otherwise remain separate from the list of group participants.

**Comment by syzygyzer** [comment]
You're right, it is still in the list of users and it looks like I can still edit it.
