### ISSUE TITLE
++ put:in can be applied for a map

### ISSUE THREAD

**Issue by dominic22** [urbit/urbit#2745]
**Describe the bug**
I've regarded this problem when I refactored a set to a map, since I forgot to change ++put:in to ++put:by as it is described for maps. The problem is, that you can add values to the map but not able to get them by the key. After you delete an entry in the map you are able to select the latest entry by using the key.

**To Reproduce**

1. There is a a map called z1:
```
> =z1 (my [[0x12 3] ~])
> [n=[p=0x12 q=3] l=~ r=~]
```

2. Use put:in to add another value, instead of put:by.
```
> =z2 (~(put in z) 0x13 9)
> [n=[p=0x12 q=3] l=~ r=[n=[p=0x13 q=9] l=~ r=~]]
```

2.1. Select the first and valid entry in the map as expected.
```
> (~(get by z2) 0x12)
> [~ 3]
```

2.2. Select the new key, since it was wrongly added into the map. It returns null.
```
> (~(get by z2) 0x13)
> ~
```

3. Put another key using +put:in into the map. There are now 3 elements in the map.
```
> =z3 (~(put in z2) 0x14 19)
> [n=[p=0x12 q=3] l=~ r=[n=[p=0x14 q=19] l=[n=[p=0x13 q=9] l=~ r=~] r=~]]
```

4 Delete the first entry:
```
> =z4 (~(del by z3) 0x12)
> z4
> [n=[p=0x14 q=19] l=[n=[p=0x13 q=9] l=~ r=~] r=~]
```

4.1. Trying to get this entry is null which is as expected.
```
> (~(get by z4) 0x12)
> ~
```

4.2. Trying to select 0x13 returns null as well.
```
> (~(get by z4) 0x13)
> ~
```
4.3. But now it is possible to get 0x14, since it is at the head of the map.
```
> (~(get by z4) 0x14)
> [~ 19]
```

**Expected behavior**
There are several possible behaviors I would expect:
- A type error or something like that, when trying to apply a put:in for maps.
- The value will not be added to the map
- The value is able to get:by even if added by put:in

**Additional context**
urbit-v0.10.4

I don't think this is a urgent problem, but it took me quite some time to identify this problem in my code. :)

**Comment by belisarius222** [comment]
The short answer is that I think this is something the Hoon type system can't help with.  Hoon's type system is mostly structural, not nominative.  From its perspective, a map is just a tree of pairs, not uniquely identifiable as a type whose name is "map".  Since a set can also be a tree of pairs, there's some overlap between map functions and set functions.

It's not perfect overlap because maps have more constraints than sets: specifically the keys (heads) must all be unique, whereas in a set of pairs, two values could have the same head but different tails and that would be enough to ensure uniqueness.

One thing we've considered is expanding the aura system to types types other than atoms.  Then maybe the compiler could know that you shouldn't be able to call set functions on a map.  It's not a matter of active development, though.  Unfortunately I think this particular footgun is likely to stay around for a while.

—
~rovnys-ricfer
https://urbit.org

**Comment by belisarius222** [comment]
Closing as wontfix for the time being.
