### ISSUE TITLE
Setting chatroom as read is intermittently broken on iOS mobile

### ISSUE THREAD

**Issue by loganallenc** [urbit/urbit#2791]
**Describe the bug**
In some chatrooms the button to “set as read” doesn’t work. This is newly introduced by the OTA.

**Expected behavior**
The chatroom to be set as read.

**Smartphone (please complete the following information):**
 - Device: iPhone X

**Comment by liam-fitzgerald** [comment]
i've repro'd this on my phone and I believe it's related to #2784 . basically the subscription is dropped for whatever reason and the poke goes through, but the resultant update never arrives. You can see this for yourself by trying to send a message the next time the read button doesn't work, it'll hang forever at pending but on refresh will be there instantly, because the subscription has died.

**Comment by loganallenc** [comment]
If it’s due to the subscription, my existing Channel.js PR should fix it.

**Comment by liam-fitzgerald** [comment]
should be a dupe then, closing
