### ISSUE TITLE
loom: corrupt

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2798]
**Describe the bug**
In the midst of an OTA my urbit became unresponsive. I `kill -9`ed it, restarted it and hit the `tcsetattr` bug. Then it became unresponsive again, `kill`ed it, restarted and hit:

```
Assertion '!"loom: corrupt"' failed in noun/allocate.c:488

bail: oops
bailing out
Assertion failed: 0 (noun/manage.c: u3m_bail: 667)
pier: work error: end of file
pier: work exit: status 0, signal 6
```

**System (please supply the following information, if relevant):**
 - OS: Ubuntu 18.04.1 LTS
 - 10.4 / Not sure

**Notify maintainers**
I bet @joemfb has an idea about this. If there's any way I can recover, that'd be great.

**Comment by galenwp** [comment]
Worth mentioning: I think on my first restart my disk was full (too many core files). I kind of want to try replaying — but I'd like someone to tell me to do that first.

**Comment by joemfb** [comment]
@galenwp, I think I've figured this out, along with the issues you reported in #1981. 

First of all, you can definitely replay (once you free up some disk space). The basic issue here is that the u3 memory-image snapshots are fragile, and can be corrupted if we run out of disk space while updating them (I think during patch application). This is a long-standing bug, and that code definitely needs some attention.

But the relationship between this and the process hangs is more complicated ... Long story short, our terminal/logging implementation is stateful, relatively fragile, and not thread-safe. Our lmdb integration uses a worker thread to commit batches of events, and that worker thread uses the terminal/log to report errors. What's more, we retry in a loop in the terminal system on EINTR -- this fixed a bug where we used to crash when a terminal was resized at the same time as a message was printed. The combination of these factors appears to effectively create spin-locks on the same resource in two different threads, ie, deadlock.

I noticed the logging issue in the lmdb worker thread this week as part of my ipc-protocol changes. I fixed it on my branch because it's wrong, and suspected it could be related to the issues you've been having, but I didn't figure out the spin-lock until this morning.

I expect that hangs will go away after you replay, as long as you keep your disk from being full (or nearly). Replay is much faster on my branch, but it's still in an experimental state. I can backport fixes to the logging thread, but they shouldn't be necessary unless your disk is full.

**Comment by galenwp** [comment]
The disk is no longer full (~70% free after clearing cores).

Just delete the checkpoint and replay on the current branch? Or should I try your branch?

**Comment by joemfb** [comment]
Yeah, just delete the checkpoint and replay with v0.10.4.

I'll need to polish up my branch and push it somewhere today. You could stop the replay and switch if takes long enough to be worth the trouble.

**Comment by galenwp** [comment]
`pier: replaying events 1 through 11956776`

See you later!

**Comment by custom-jonathan** [comment]
I spent 4 days replaying my pier with the v0.10.4 branch and I'm back to where I was before the replay. My ship starts hanging up, and when I ctl+z I get the same `Assertion failed: 0 (noun/manage.c: u3m_bail: 667)` errors.

**Comment by joemfb** [comment]
@custom-jonathan, are you by any chance out of disk space? There's a recently discovered bug wherein that can lead to lockup.

**Comment by custom-jonathan** [comment]
I'm using 55.4% of 48.29GB on the droplet and 76% of memory usage. 0% swap usage. 

I'm getting a steady stream of `arvo: replacement event (for %hear) failed` and *tons* of `wire=/mailbox/` errors too for what it's worth. `ames` starts and then input becomes inactive. Only thing I can do is ctl+z.

But, as its first starting up I seem to be able to input something before the bug hits.

**Comment by joemfb** [comment]
@custom-jonathan, it sounds like the process is just getting swamped with bad ames packets, not actually hung. I bet if you wait after you type, your input will eventually appear. I think the best you can do for now is to let it run and ride it out. Improvements WRT to event prioritization and QOS are in development, but unfortunately not ready yet.

**Comment by custom-jonathan** [comment]
I'd let it replay for four days and that was after a full 24 hours of wonkiness. I went ahead and slapped the nuclear option. Life 15, here I come!

**Comment by joemfb** [comment]
```
~minder-folden reincarnation go <<brrrrrr>>
```

FYI, the `arvo: replacement event (for %hear) failed` issue is most likely caused by other ships sending you packets for an earlier life (due to those other ships being behind WRT to azimuth state), so you are likely to see it again after your breach.

**Comment by custom-jonathan** [comment]
Thanks for the heads up; I'll keep an eye out for it and now I know it's expected.

**Comment by sibwyl-batrep** [comment]
Getting the same error. %(
How can I help to solve that?..

**Comment by sibwyl-batrep** [comment]
Nah, replayed events and still
arvo: replacement event (for %hear) failed
and sometimes azimuth eth-tracker error

no chance in opening the landscape, but I can see messages in the console

at least there is no bailing out

**Comment by joemfb** [comment]
I have fixes as described above on a work-in-progress branch, but it's become very long-running, so I've additionally PR'd them in #2919.

**Comment by praxeo** [comment]
I had this issue and was able to "fix" it by removing the chk folder and restarting.
