### ISSUE TITLE
Landscape mistakenly reports unread chats

### ISSUE THREAD

**Issue by sopmep-malpub** [urbit/urbit#2818]
In my browser tab, Landscape is reporting unread chats but there are no channels showing any unseen messages.

I suspect this might be due to https://github.com/urbit/urbit/issues/2816 and that the unread chats are associated with a channel that is no longer visible to me.

I'm not sure how to replicate this behavior short of attempting to replicate the linked issue.

This behavior is consistent across both Chrome and Firefox.

**Comment by sopmep-malpub** [comment]
There are two chats that appear in my `;chats` that are not present in Landscape. These are:
* `~hiddev-dannut/hooniverse-chat-7224`
* `~hiddev-dannut/application-ideas-4946`

These chats pertain to the planet in the linked issue in the initial post.

They are still present in `;chats` after trying to `;leave` them. I'm guessing this is the reason for Landscape reporting unread messages.

**Comment by matildepark** [comment]
Hi!

This issue appears to be caused by our current non-implementation for archival content. If you leave a group by whatever reason, we still have its resources, but the sidebar only sorts our current group's content, so this is just non-visible. This issue is blocked, essentially, on devising and implementing an archival approach, which we'll talk about moving up and dealing with, if it doesn't get in the way of ongoing refactor work. 

For now, this is going to persist, and I'm sorry. If it's any consolation, it shouldn't be too long before we can move toward a proper fix here. If it really bugs you, you can manually go to the URL for those chats (eg. `~chat/room/~hiddev-dannut/hooniverse-chat-7224`) and leave them.
