### ISSUE TITLE
Cannot access landscape due to pow.cx / would like to specify port for landscape

### ISSUE THREAD

**Issue by ukd1** [urbit/urbit#2847]
I write software, and use pow.cx on my box to help me start / stop dev servers. It's doing some funky firewall stuff on port 80, but there isn't necessarily anything running on it.

**Describe the bug**
So, I can't actually use urbit, even though it can bind to that address

**To Reproduce**
1. get a mac
2. install pow.cx
3. start urbit, it will bind to port 80

**Expected behavior**
urbit detects port 80 isn't usable? maybe.

Really I'd be happy if you could just specify the port in the ``urbit`` cli instead of [hardcoding to 80](https://github.com/urbit/urbit/blob/master/pkg/urbit/vere/http.c#L1606)

**Screenshots**

**System (please supply the following information, if relevant):**
 - OS: macOS
 - v0.10.4-darawn
 - 0vv.f2us6.8jmr3.7j210.fcjlo.mked1.ginbl.aeg9n.dcsqm.bhmo1.h6m4a

**Comment by ohAitch** [comment]
It looks like -P puts urbit in "proxy" mode, which puts it on 8080 instead
(or the next available
<https://github.com/urbit/urbit/blob/master/pkg/urbit/vere/http.c#L1223>
higher port); I think this also applies for 80 actually, but trying to bind
81 82 etc is presumably less effective.

**Comment by joemfb** [comment]
@ohAitch, `-P` enables sample-based profiling (as opposed to -j, which is trace-based profiling `chrome://tracing`-compatible json output). `-p` lets you set the ames UDP port.

The TCP proxying around the HTTP servers is obsolete (written for old ames) and will be removed. The HTTP port-finding logic is static: try 80, then 8080, then increment 'till you find an open port.

The issue here is that pow.cx configures the firewall to redirect from port 80, but it doesn't actually bind it, so vere thinks it's available.

**Comment by matildepark** [comment]
@joemfb I know there's probably a prioritisation for the solutions here, but this could just be considered a dupe of #1268. You know more here, though, so I defer.

**Comment by joemfb** [comment]
That looks right. (FWIW, king-haskell at least nominally supports specifying the http-port, and it'll be soft-released with ipc-redux.)
