### ISSUE TITLE
New moon does not inherit planet memberships in landscape

### ISSUE THREAD

**Issue by robert-sherwood** [urbit/urbit#2870]
**Describe the bug**
When creating a new moon from a planet, chat messages appear in dojo for all chats of which the planet is a member, but no subscriptions are listed in landscape.

**To Reproduce**
1. Spawn moon
2. Start moon
3. Observe chat messages in moon's dojo
4. Connect to moon's landscape
5. Observe no chats/notebooks/links etc. listed

**Expected behavior**
Expect to see subscriptions from Planet on moon

**Desktop (please complete the following information):**
 - OS:  MacOS 10.15.3, fedora 32
 - Browser: chrome, safari, firefox
 - Base hash of your urbit ship. 0vj.57gf5.1qk6u.r75oq.dlvm4.mkj21.ufv0v.7cor6.pu1b9.cmib5.ontk0

**Comment by matildepark** [comment]
@loganallenc @Fang- why does chat-cli not use the chat-store's inbox here?

**Comment by loganallenc** [comment]
Chat-cli is an application that needs to be rewritten. Mark is currently doing so I believe, at my continued urging.

**Comment by matildepark** [comment]
I mean the two solutions are a) rewrite chat-cli so moons don't inherit these subscriptions or b) make it so chat-store does inherit these subscriptions, though honestly I haven't looked at the back-end here. It seems like we have competing stories about what moons are for; and honestly, I prefer starting with the simplest one.

@urcades Do you have any offhand thoughts on moons coincidentally?

**Comment by Fang-** [comment]
> why does chat-cli not use the chat-store's inbox here?

chat-cli has historically considered the planet as the canonical data store, and interacts with it instead of the local chat suite.

If we want to make moons completely independent instead of inheriting their planet's chat state, the quick-and-dirty is to change this to always produce `our.bowl`, I believe.

https://github.com/urbit/urbit/blob/69b6495d3d4c8cd3d81c5842a2cc90bf8059d63c/pkg/arvo/app/chat-cli.hoon#L250

The previous behavior might still be simulated by cross-ship linking, once #2867 makes it in, and chat-cli stores cli state by subscriber.

> Chat-cli is an application that needs to be rewritten.

Again, I don't think a full rewrite is necessary or wise. The specific change you requested lives on [m/chat-cli-unselect](https://github.com/urbit/urbit/commit/cb01ff2a01cd3e3d42338893a21f46bd2cea45d5).

**Comment by loganallenc** [comment]
Looks like it’s almost done! Exciting.

**Comment by robert-sherwood** [comment]
I am aware that I am not a developer, and I do not get a vote, but I will cast a symbolic ballot for some way to synchronize all planet memberships to moons. I would like to have a moon running on every device that I interact with directly, and leave my planet running on the headless box in the basement. I have the server in the basement, but I am connecting to it over http right now to get to my primary directory.

There are many interesting potential use cases for moons, but that's the one I have in mind right now. I agree that some of the other use cases I've heard (e.g. sensor device feeding data to your planet) do not require the moon to mirror the planet, but I would hate to have a situation where I need to have each moon independently subscribed to all the planet's groups.

**Comment by matildepark** [comment]
@robert-sherwood it's tricky; moons are a "theoretical cool thing" that have not been thought through in the Landscape app suite whatsoever, in userspace everything treats them differently or was not considering them at all; I would prefer to do them properly everywhere instead of this "depending how eager the developer is, they decided to consider that moons exist" approach, even if we just go back to blank slate, "they're a fresh ship," approach.

**Comment by Fang-** [comment]
Gonna pick this up (and probably try to get multi-linking in) after opening the debug dashboard PR, eta on which is end of day.

**Comment by Fang-** [comment]
Closed as of #2901.
