### ISSUE TITLE
chat: image load borks scroll position

### ISSUE THREAD

**Issue by liam-fitzgerald** [urbit/urbit#2883]
**Describe the bug**
In chat, images loading in on slow connections bork the scroll position

**To Reproduce**
1. Open an image heavy chat on a mobile device
2. As the images load in, your scroll position will be disrupted

**Expected behavior**
Scroll position should be stable as images load in.

**Comment by matildepark** [comment]
I guess what we want is to wait until everything is 100% loaded before processing scroll behaviour?

**Comment by matildepark** [comment]
Turns out this is specifically a Safari issue because [scroll anchoring](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring) generally is on by default and prevents content reflow outside the viewport. [Status is unclear](https://bugs.webkit.org/show_bug.cgi?id=171099).
