### ISSUE TITLE
Ford automatically builds from non-%home desks

### ISSUE THREAD

**Issue by jtobin** [urbit/urbit#2886]
**Describe the bug**
Ford automatically builds from desks that it shouldn't (i.e., non-%home desks).

**To Reproduce**
Steps to reproduce the behaviour:
1. Boot a fakezod
2. Init a new desk: `|merge %foo our %home`
3. Commit some changes to e.g. gall on `%foo`
4. Wait a while, observe `%arvo-assembly` and `%arvo-assembled` (i.e., something is being built)

**Expected behaviour**
No automatic build should occur (see [this urbit-dev thread](https://groups.google.com/a/urbit.org/forum/#!topic/dev/QAPh9Tq0mSc)).

**System:**
Vere v0.10.4

cc @belisarius222 @philipcmonk

**Comment by belisarius222** [comment]
Semantically, for most builds, Ford always builds the standard library.  In practice, it's usually cached.  It can fall out of the cache, though, especially around updates to /sys, which I believe currently cause Ford to clear its caches.

This stuff works very differently in Ford Fusion, and it's an area of active development.  I suspect we will prioritize deploying Fusion rather than fixing this.

**Comment by jtobin** [comment]
Not an issue as of urbit-os-v1.0.24.
