### ISSUE TITLE
I have a hunch: moons interfering with planet communications

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#2961]
Hi there. discard this if it's nonsensical, but here's my story that gave rise to an "I wonder if there is an issue?" hypothesis:

I enjoyed quite a while of uber-stable communications which came to a close immediately after I launched a moon and had it running for a while.  I launched the moon to install the Canvas app (didn't get far and did not install it), but shortly thereafter, ~somlus-savlev started to have trouble with certain planets.  I have heard a bit from other users about communication problems from their planets, once moons are launched.  In the past I did use moons a lot, but have not done that in a while because I now use fake ships when I need a spare dojo.

This might be nothing, but I am wondering, since moons are not receiving all of the attention that planets are in terms of development and stability, and moons are sharing in quite a bit of planet communications, is there a chance that a moon can actually impair a planet's connections to other planets or other elements of the network?

**Comment by philipcmonk** [comment]
Hmm, I doubt it.  Only thing I can think of is that when you start up a moon, it downloads the latest OTA from the planet (actually all previous OTAs, about 100MB), which can take quite a while and may slow down the planet until it's done.  This could make you drop some subscriptions because you don't respond fast enough, but they should all restart.

**Comment by matildepark** [comment]
Not an issue.
