### ISSUE TITLE
chat: All unreads getting cleared occasionally

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#3080]
**Describe the bug**
I saw this once during the Ford Fusion upgrade and once for sure this morning, a couple more times I think so but I'm not sure.  It affects all chats, and my best guess is that it's a side-effect of chat-trim-store

**To Reproduce**
1. Chat for a while
2. On refresh (not sure if you need refresh) sometimes all unread markers go away.

**Comment by ryjm** [comment]
I've also been seeing this.

**Comment by matildepark** [comment]
Our hypothesis, IIRC, was that this was due to the automatic chat-store trim — part of its behaviour was that it set all messages as read. After #3083 I wouldn’t expect this. (Although #3091 hasn’t gone out yet...)

I’m unsure when we get messages vs. message such that the trim may still happen occasionally and reset counts.

**Comment by loganallenc** [comment]
As soon as the aforementioned PR is live, this will no longer be an issue. (Mark fixed the %messages case)

**Comment by loganallenc** [comment]
Fixed by https://github.com/urbit/urbit/pull/3083
