### ISSUE TITLE
planet keeps crashing on launch

### ISSUE THREAD

**Issue by somlus-savlev** [urbit/urbit#3094]
Hello,

my planet ~somlus-savlev is not at about 45GB in size and keeps crashing on launch.  Here is a pastebin of the launch-crash sequence and messaging:

https://pastebin.com/B15qhnrE

In a prior crash it seems like I got an error that reported it had reached the 'end of the loom' or something like that.   in a possibly (?) related issue I was trying to launch a new ship as a workaround to getting back on the network and I got a report of a not-working mainnet link:

urbit 0.10.7
boot: home is /home/scott/urbit-v0.10.7-linux64/follec-fotnus
loom: mapped 2048MB
lite: arvo formula 297b51b3
lite: core 12b850ec
lite: final state 12b850ec
boot: downloading pill https://bootstrap.urbit.org/urbit-v0.10.7.pill
boot: retrieving latest block
error fetching http://eth-mainnet.urbit.org:8545: HTTP 503

Not sure if the two are related or not.  Any ideas as to how I might be able to put the ~somlus ship in the ICU and get some help?

**Comment by frunjik** [comment]
FWIW 
I have the same experience -
urbit just ends with:

`work: fail: end of file Killed
`

**Comment by vvisigoth** [comment]
We'll take a look at the infura node!

**Comment by philipcmonk** [comment]
@somlus-savlev Those seem like two separate issues.  I'll restart our ethereum proxy, sometimes that seems to get stuck.

The bail: meme error is because even though you're using 900MB out of 2GB, you only have 42MB of contiguous free space, so anything except very small events can't succeed.  Last week I wrote a memory compaction algorithm that doesn't use the heap, which *should* get you out of this.  I need to test it just a little bit more, but it seems to work and hopefully I can have a draft PR by tomorrow, and then I'll ask you to try it on a -L copy of your ship.  If it works, that should resolve ~somlus's problem.

**Comment by dclelland** [comment]
Suspect I'm running into a similar issue - my planet runs for only a wee bit before I hit 

```
bail: meme
bailing out
pier: work error: end of file
pier: work exit: status 0, signal 6

```

Full log: https://pastebin.com/JL8aYpPP

Would I be able to try out that PR?

**Comment by dclelland** [comment]
Oh, I found it, assume it's ready to go?

https://github.com/urbit/urbit/pull/3099

**Comment by dclelland** [comment]
I ran your new binary and my planet is still launching and crashing after a short while; here's the log: https://pastebin.com/nrtDwX6T

**Comment by philipcmonk** [comment]
Hmm, it looks to me like you did the right thing, can you run |mass now?

**Comment by dclelland** [comment]
I made the mistake of attempting to run `|pack` last night, and now it crashes consistently on startup, and additionally renames `north.bin` and `south.bin` to `north.bin.bak` and `south.bin.bak`.

https://pastebin.com/GhDpGvw3

`north.bin` is quite big, for the record.

```
daniel@urbit: ~/urbit/pier % ls -lh lanrus-rinfep/.urb/chk
total 1.9G
-rw-rw-r-- 1 daniel daniel 1.9G Jul 21 11:23 north.bin
-rw-rw-r-- 1 daniel daniel  16K Jul 21 11:23 south.bin
```

Time to try replaying the event log with `ipc-redux-replay-recovery` perhaps...

**Comment by philipcmonk** [comment]
You shouldn't have to replay if you have the .bak files.  What you're going to want to do is rename the .bak files to not have ".bak" in the name and then disable |pack in the binary you're running.  I think this binary will work for you since it redefines `|pack` to do something less aggressive and much safer:

MacOS: https://bootstrap.urbit.org/a580f964166cd41bd618529a5982b8d84c2ac4e6-darwin.tgz
Linux: https://bootstrap.urbit.org/a580f964166cd41bd618529a5982b8d84c2ac4e6-linux64.tgz

**Comment by dclelland** [comment]
Oh wow, thanks a lot Philip. Looks like that got me past the inadvertent `|pack` call.

Results from `|mass`: https://pastebin.com/7zsiWQp9

**Comment by philipcmonk** [comment]
Okay, it looks like you've got 1GB contiguous free space now, which is a
lot. It should run without crashing now.

**Comment by philipcmonk** [comment]
Looks like this is working for everyone now

**Comment by gilletteonmeheleparim** [comment]
I still have `failed to fetch http://eth-mainnet.urbit.org:8545: Couldn't connect to server` after I booted a fresh comet
