### ISSUE TITLE
Chat channels formerly within specific groups now appear under Direct Messages

### ISSUE THREAD

**Issue by jalehman** [urbit/urbit#3161]
**Describe the bug**
The channel `~darrux-landes/general` was formerly listed under the **Urbit Community** group, as it should be. After the Groups refactor (current base hash is `3p5fi`) it now appears under the Direct Messages section. 

There were a few other chat channels that had appeared under Direct Messages from groups I'd left in the past, but I left them before thinking to file this report. If I remember correctly, there was an old Urbit Community General channel also in this list leftover from a previous host (the _old_ Urbit Community). That may have something to do with it.

**To Reproduce**
Uncertain.

**Expected behavior**
Would expect UC General to still be under the Urbit Community group.

**Screenshots**
<img width="1111" alt="Screen Shot 2020-07-23 at 9 14 12 AM" src="https://user-images.githubusercontent.com/550978/88311538-da38ca80-ccc5-11ea-8ed7-785cb67dc372.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-66-generic x86_64)
 - Browser: Firefox
 - Base hash of your urbit ship: `3p5fi`

**Comment by matildepark** [comment]
> If I remember correctly, there was an old Urbit Community General channel also in this list leftover from a previous host (the old Urbit Community). That may have something to do with it.

You may be right on this — the case as I've heard it recorded so far:
- The users were in the old UC before it migrated from ~dopzod to ~bitbet-bolbel
- The only chat this is happening to in any report is this General chat

My hypothesis without knowing your inbox state and your associations state is that the migration case dropped the Chat because it placed it in the old UC? What I would try:

1. Leave General.
2. Leave Urbit Community.
3. Run `:metadata-store [%cleanup /~dopzod/urbit-community]`
4. Rejoin Urbit Community by clicking join group, `~bitbet-bolbel/urbit-community`.
5. See if General propagates in its channels list.

If still nothing, you might have to try this again with `:metadata-store [%cleanup /~bitbet-bolbel/urbit-community]` (that is, leaving and rejoining), but I'm hesitant to recommend that as I'm afraid to make the problem worse by potentially nuking all the group channels!

**Comment by risruc-habteb** [comment]
I had this behavior, followed direction above.

Upon rejoining UC, I saw the normal/full list of channels(including General).

I rejoined all chat channels, but General still shows up under DM's.

Also, 'General' now does not show up under the group's channels (it did when I first rejoined.)

**Comment by matildepark** [comment]
@galenwp @risruc-habteb Curious if this is now resolved for you. You may have to leave and rejoin UC again.

**Comment by matildepark** [comment]
> I rejoined all chat channels, but General still shows up under DM's.
> Also, 'General' now does not show up under the group's channels (it did when I first rejoined.)

General shows up if you leave UC and rejoin.

If you join General, it sets its metadata outside of UC.

@liam-fitzgerald Ideas? Is this relegated to the host of the chat or cached metadata?

**Comment by liam-fitzgerald** [comment]
does it persist after a `:metadata-store [%cleanup /~bitbet-bolbel/urbit-community]` ? Working theory is that this is a mug ordering issue, involving duplicate metadata.

**Comment by liam-fitzgerald** [comment]
for those affected, please run
```
:metadata-store [%cleanup /ship/~dopzod/urbit-community]
:metadata-store [%cleanup /~bitbet-bolbel/urbit-community]
```
and then leave and rejoin urbit-community.

**Comment by jalehman** [comment]
@liam-fitzgerald this did in fact clear up the issue for me.

**Comment by jalehman** [comment]
Thanks all for the help!
