### ISSUE TITLE
Chat: Linkification of urls adds \n's, ignores backticks and breaks multiline messages

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#3195]
**Describe the bug**
If you write the message `test http://example.com test` in chat it'll convert it to:

>test
>[http://example.com](http://example.com)
>test

and it turns a multiline message like:

```
test http://example.com
test
```
into:

>test
>[http://example.com test](http://example.comtest)

that is, it appends the first word of the second line to the end of the url

additionally, it linkifies urls regardless of whether they're in backticks and so breaks formatting of code blocks

**To Reproduce**
1. Try the above examples in chat

**Expected behavior**
It'd be preferable if:
a) urls were linkified inline rather than adding \n's
b) multiline messages should not produce broken urls or have their formatting altered
c) urls in codeblocks should not be linkified

**Desktop (please complete the following information):**
 - OS: arch linux 64-bit
 - Browser: qutebrowser
 - Base hash: jp5fi

**Comment by matildepark** [comment]
You can see the logic here:

https://github.com/urbit/urbit/blob/c96705e755f424e90887c656c452ada28797806b/pkg/interface/src/apps/chat/components/lib/chat-input.js#L212-L235

As you say:

> a) urls were linkified inline rather than adding \n's

Why do we do it that way? Well, we have to be cross-compatible. Chat, and its predecessors, have message types. It isn't all strings that we render on FE, it's stuff like text, or URL, or 'me' for actions. Before we introduced this logic, in order to have a URL message the message's content would have to be deliberately cut up, by you, to be just the URL.

> b) multiline messages should not produce broken urls or have their formatting altered

I'm unsure why the present logic appends 'test' with the blank space when it separates the messages by spaces. That itself is a bug worth fixing...

> c) urls in codeblocks should not be linkified

This is true, and it should probably have a catch to check for backticks or triple backticks before cutting it up ...

**Comment by tylershuster** [comment]
I’m happy to fix b and c. For a, what if it replaced the urls in the original message with the base URL and then sent messages with the full (typed) URL as separate messages, in order, after the original message?

**Comment by mike-cr** [comment]
interesting I assumed it was just FE stuff like bold, italics etc. What is the reasoning behind a url type?

**Comment by Fang-** [comment]
> interesting I assumed it was just FE stuff like bold, italics etc. What is the reasoning behind a url type?

I know there's prior discussion on this out there somewhere, but couldn't find it. To briefly rehash:

Your urbit is (among other things) a data store. "Data" is vague and not very useful, so we store "typed data" instead. In this context, instead of saying "all messages are strings", we have [a message type](https://github.com/urbit/urbit/blob/4d288f2e4e38ed0a483345d77dee34ebde8a1364/pkg/arvo/sur/chat-store.hoon#L5-L10) that messages must conform to.

Having a specific message type for URLs (or hoon expressions, or `/me` actions etc) gives very useful metadata about a message's contents. Clients/interfaces, bots, and other utilities can easily know a URL when they see one (by its type), without _needing_ to re-implement URL parsing logic or other such things.

(The "bold, italics etc" lightly break away from this by saying "a `%text` message may contain markdown" without including that in the type. But precisely _because_ there's no type or other metadata for it, (the logic for it living only in Landscape,) other clients don't _need_ to know about markdown. It's more of a rendering nicety than a part of the chat protocol.)

**Comment by matildepark** [comment]
> I’m happy to fix b and c. For a, what if it replaced the urls in the original message with the base URL and then sent messages with the full (typed) URL as separate messages, in order, after the original message? For example:
> 
> > Hello please visit https://example.com for wonderful examples of https://product.xyz/check/out
> 
> becomes
> 
> > Hello please visit (example.com) for wonderful examples of (product.xyz)
> > https://example.com
> > https://product.xyz/check/out

I dig this but I also feel like modifying people's messages would feel capital-W Weird. What if we sent the full message, uncut, but sent any URLs we detect separately ... *unless* it's in a code snippet?

@Fang- @tylershuster

**Comment by Fang-** [comment]
I agree that seems a little too... bespoke. Fixing (b) and (c) from above would make this whole situation feel a lot better. (a) could still be considered afterwards, but I'm hesitant to endorse changes on that scope before the current thing even behaves as intended.

**Comment by matildepark** [comment]
Explain "from above" here?

**Comment by tylershuster** [comment]
Ok, I can take b and c if @matildepark wants me to/doesn't mind and ignore issue a. 

I agree that my original suggestion feels Weird. Is this something that can be mediated with graph-store? For example, the two URL messages would be child nodes of the first message? That preserves the parentage of the data instead of just pitting it in a line, but it doesn't quite solve the Weirdness of altering the actual content of the message. Although the system *does* currently alter their message content.

**Comment by Fang-** [comment]
> Explain "from above" here?

> a) urls were linkified inline rather than adding \n's
> b) multiline messages should not produce broken urls or have their formatting altered
> c) urls in codeblocks should not be linkified

**Comment by tylershuster** [comment]
Issue b was caused by splitting on spaces, meaning content following a newline gets glommed onto `each`
