### ISSUE TITLE
Remove SSE3 dependency

### ISSUE THREAD

**Issue by sokoow** [urbit/urbit#322]
All,

This code is very promising, but it's not portable enough - you're relying on sse3 a bit too much at the moment, is this really necessary? By getting rid of this dependecy, you'll be opening to compile urbit on variety of more portable platforms - raspberry, chip PC and so on.

Could somebody comment please?

**Comment by cgyarvin** [comment]
Yes, it would be nice to get rid of this dependency!  It is not high
priority sadly.

**Comment by galenwp** [comment]
Where would one start to attack this? Would also fix https://github.com/urbit/urbit/issues/164 which would be great.

**Comment by cgyarvin** [comment]
I should have expanded on this at more length.  Essentially the floating
point core (++rd) is the problem.  It is not much more than a stub, and not
used by anything significant at present.

We are not actually using SSE instructions for bigint vector calculations -
we are just using the Intel SSE3 library to configure floating-point
modes.  You could ifdef this out and run on the Pi, etc, without obvious
ill consequences.

But - deterministic computing places a serious burden on FP code.  Most FP
users seem to think of floating-point calculation as a sort of fuzzy analog
thing in which close enough is good enough.  This is not viable in urbit.
The consensus is that you *can* get FP determinism, but you have to work
pretty hard to do so.  A good collection of resources is:

http://gafferongames.com/networking-for-game-programmers/floating-point-determinism/

Max Greer is rumored to be rewriting our FP code, a rumor that if true is
extremely welcome.  But certainly, nothing will go wrong if you ifdef out
the MM calls in main.c and, for safety, also disable the ++rd jets on
non-Intel platforms.

**Comment by sokoow** [comment]
Well I've used patch for armhf that @kingdonb provided (https://github.com/yebyen/urbit-deb/blob/master/urbit-armhf.diff), and it works like a charm on my armhfs now.

**Comment by kingdonb** [comment]
Cool. I was having build failures on armhf, so glad to hear it. Must be my
environment.

**Comment by sokoow** [comment]
Well it actually meant that it compiles, shows the console and I can do 'something' with it on my chromebook 2. There's still a lot cpu/disk thrashing that I can't understand yet though :)

**Comment by kingdonb** [comment]
That is normal. I have build failures because of commonmark that I haven't
been able to explain yet. That's what I am talking about.

**Comment by cgyarvin** [comment]
I believe that there's cpu/disk thrashing!  In particular, the
checkpointing code is exceedingly crude and blocks urbit while we write out
the checkpoint, which is quite unnecessary.  Copy-on-write is the right way
to do checkpointing, in theory via fork(), but last time I looked at this
there were some bad interactions between libuv and fork().

But you could get a considerable improvement just by putting the memory
blocks to be checkpointed in buffers and writing those asychronously.  In
general the state of urbit optimization is that we optimize stuff when we
find it's really slowing down our development process, which doesn't result
in a good experience for people not using dev-level hardware.

Speaking of commonmark, my general feeling is that we made a bit of a
mistake in jumping on the commonmark bandwagon.  Speaking of jet
inconsistency, it would take a lot more work to make sure that our markdown
parser is bug-for-bug compatible with the CM C code that implements it.
 markdown is of course insanely complex.  For perfect consistency, you'd
want to basically translate the C code into hoon, rather than implementing
the English spec in hoon.  An ugly task to say the least.

**Comment by kingdonb** [comment]
Is that why it segfaults? Because of jet inconsistency? Cause that would be
awesome.
I think that's not it though, mostly because I have only observed that
failure on one arch. The failure I saw happens during cmake.

We should make the build fail if jets are not bug for bug compatible,
optionally, if possible.

**Comment by cgyarvin** [comment]
Ha!  No, I doubt very much that it segfaults because of that.  I'd like to
see the actual crash.  But I only have a mac...

**Comment by kingdonb** [comment]
It says it produces a core, but it might be related to a new version of
ChromeOS rather than a change in urbit. If I power wash my chromebook and
install the chroot again, and still get the core trying to build urbit, I
will send it along happily. My machine is a first gen Samsung chromebook.
Xe303c12-A01US

**Comment by cgyarvin** [comment]
Weird.  The best thing is always a stack trace with -g, of course.  I can't
do much with a core from another architecture...

**Comment by kingdonb** [comment]
Well, I'm not sure what changed from yesterday to today, but this era it
seems to build fine.  Cool.

--Kingdon

**Comment by cgyarvin** [comment]
No, I'm just describing an improvement to u3e_save() in n/e.c.
 _ce_patch_sync(), _ce_patch_verify() and _ce_patch_apply() could and
should run on a separate thread, and not block computing while the
checkpoint is being written to disk.  If copy-on-write was to be done
properly, u3e_save() would in fact fork().  (But libuv doesn't have fork,
because windows doesn't have fork and one of libuv's goals was to support
windows.)

**Comment by jhance** [comment]
To be truthful the reason SSE3 is used is because I didn't want to deal with denormed FPs at the time I wrote all of that, and just wanted to get on with more important things

**Comment by juped** [comment]
Max should set the record straight on this one, since the current FP code is his.

**Comment by cgyarvin** [comment]
I think we're bound to the soft FP library Max imported, which is fine for
the moment.  We can probably take SSE3 out of the build?

**Comment by max19** [comment]
I could replace the SSE SHA256 in the scrypt I imported with the non-SSE, then it would be good as far as I know.
The new library doesn't rely at all on FPU flags.

**Comment by cgyarvin** [comment]
That'd be awesome.  It'd be nice to get back to using hardware FP at some point, but you gotta walk before you run...
