### ISSUE TITLE
clay: Compilation triggered by |commit misses some new files if previous |commit resulted in build failure

### ISSUE THREAD

**Issue by cmarcelo** [urbit/urbit#3240]
**Describe the bug**

Compilation triggered by commit seems to miss files that were changed in a previous commit that had a compilation fail.  See steps below:

**To Reproduce**

1. Add an extra note `[%another-case ~]` to eyre notes in zuse.hoon
2. `|commit`, this will result in a `mint-lost` failure, as expected.
3. Handle the new note in eyre.hoon (just do whatever %vega does or !!).
4. `|commit`, this will fail with `mint-vain` as if the new case in zuse did not exist

**Expected behaviour**

In step 4, I've expected it to compile correctly.

A workaround is to change BOTH files, that will force both to be recompiled, resulting in correct compilation.

**Additional context**

Making a new change to zuse, and doing another |commit results in the first `mint-lost` error, which suggests the old eyre source is being used.

It seems Clay is taking only the latest committed changes plus the latest correctly built state.

**Comment by Fang-** [comment]
For the record, this is probably `urbit/vere/io/unix.c` rather than clay. It hasn't learned to account for the fact that commits to clay can fail now, and so its internal representation goes out of sync. I think it just sends clay what (it thinks is) the diff, rather than the full file state, but doesn't revert that diff in its own representation when that fails.

**Comment by Fang-** [comment]
This is still annoying. I briefly looked into patching this some time ago, but it wasn't clear to me how to detect the "failed to apply" case. Anyone have thoughts on implementation of a fix here? @joemfb, @philipcmonk?

**Comment by belisarius222** [comment]
I've been meaning to write a proposal for how this should work.  I think it should work roughly like this:

- On each process restart and for each Unix mountpoint, Vere's first %into should be full (absolute).  Then Vere needs to wait for acknowledgment from Arvo that the first %into event has succeeded before switching from sending absolute (full) %into events to relative (diff) %into events; otherwise Vere's next %into should also be relative.  Similarly, if any %into event crashes, Vere should switch back into absolute mode so that the next %into will resynchronize.

- In keeping with the principle that the Arvo state should encompass all persistent data, Clay should be the unambiguous source of truth about Unix filesystem mounts; Vere should defer to Clay in case of conflict.  Not sure if this will come up in practice, but I think if we can maintain this invariant, it will be clarifying.

I have some concerns around deletions not being picked up by Vere — if Clay deletes a file, writes the deletion event to disk, then crashes before performing the effect that deletes the file from the Unix filesystem, then after restart, the next %into will add the file back into Clay.  This clearly isn't what the user wanted.  One thing we could do is perform a full resynchronization of all mountpoints on restart, where the previous Unix filesystem state would be ignored and replaced by a read of the Clay state.  This would ignore changes to mountpoints made while the ship was offline, but I think it's a coherent system that would be relatively easy to reason about.

—
~rovnys-ricfer
https://urbit.org

**Comment by Fang-** [comment]
> On each process restart and for each Unix mountpoint, Vere's first %into should be full (absolute).

> One thing we could do is perform a full resynchronization of all mountpoints on restart, where the previous Unix filesystem state would be ignored and replaced by a read of the Clay state.

Considering my first reaction to auto-commit on-boot was "oh no", I'd vastly prefer the latter, yeah. Getting flashbacks to doing ops on ~zod, rebooting it, and having it load in heavily outdated files... Re-setting mountpoint on-boot seems very much in line with having Clay be canonical.

**Comment by philipcmonk** [comment]
Clay already sends much more than an acknowledgment, it sends exactly the diff that it understood.  IMO the change should simply be from "update my cache with what I sent to clay in %into" to "update my cache with what clay sent me in %ergo".  I suspect it has to do something like that anyway for changes that originate in clay, so it might be as simple as removing the cache updates on %into.

IMO it's very convenient to be able to edit files while the ship is off, then commit them when it turns back on.  This is especially useful when you're trying to fix ships that are constantly crashing, and you need to commit a fix before it crashes again.  I would be satisfied with a flag that says "don't resync unix on boot", but I'd be wary of making the change without that.

**Comment by ohAitch** [comment]
On a philosophical level, if your ship turned off without successfully
syncing clay to unix, it probably crashed, and if your ship crashed, it's
fairly likely you want its clay to contain something other than what it
currently does. Perhaps in a manner where you cannot reliably access dojo.
I would have the flag be opt-in "send a commit along with the boot event"
however, unless we're talking about literal |autocommit

**Comment by philipcmonk** [comment]
Looking at the code, it seems like it already stores `mug_w` and `gum_w` as the mug of the last %into and %ergo, respectively.  We check against both, so it might be as simple as removing the `mug_w` check in `_unix_update_file`.

**Comment by philipcmonk** [comment]
Obviously, King Haskell should be reviewed for this as well.

**Comment by belisarius222** [comment]
> Clay already sends much more than an acknowledgment, it sends exactly the diff that it understood. IMO the change should simply be from "update my cache with what I sent to clay in %into" to "update my cache with what clay sent me in %ergo". I suspect it has to do something like that anyway for changes that originate in clay, so it might be as simple as removing the cache updates on %into.

I think this is a good solution.

> I would have the flag be opt-in "send a commit along with the boot event"

I agree.  I think it's conceptually cleanest to use the Clay state as the single ground source of truth unless manually overridden.  If my ship is having problems and I want to force it to run an %into immediately on restart, I think it's better to use an opt-in command-line argument to indicate that.  In addition to being conceptually cleaner, it has better properties in case of user error: if I forget to add the flag, my ship will just crash again, which has probably happened a couple times already.  I can then remedy the problem by adding the flag.  This would help with ~palfun's PTSD.

We probably need to fix the bug where |commit syncs all desks in order to get this all to work right.  I suspect the command-line flag to opt into a force-commit should take in a desk name as an argument, since there's no canonical ordering among desks -- if you try to force-commit two desks in one event, I think you'd have unpredictable ordering, which could cause further bugs.

**Comment by ohAitch** [comment]
Maybe have the command-line flag take a path, even, so the into is just "in this mount in this subdirectory commit the tree looking like this, otherwise keep whatever". (Esp if that is easy to express using current partial diffs)

Re: commit bug, are you saying the current state of things is `|commit` takes a desk dojo argument but then discards/ignores it?

**Comment by philipcmonk** [comment]
> Re: commit bug, are you saying the current state of things is `|commit` takes a desk dojo argument but then discards/ignores it?

Precisely.  Specifically it passes it to unix.c, which discards it.  This bug has existed for the entire existence of `|commit` as far as I can tell, but people rarely stumble upon it because they rarely have two desks mounted at the same time, or if they do they're only changing one of them so they don't notice the other commit.  Once in a while it bites you though!  I forget if this is fixed on King Haskell.

**Comment by ohAitch** [comment]
Ah, is unix.c responsible for desk<->mount mapping and not clay itself?

**Comment by philipcmonk** [comment]
No, it's reflected in Clay as well, which handles it correctly, including complaining if that mount point doesn't exist.  The existence of the bug is clear from this, which handles `|commit`, with `mon` as the name of the mount point specified.

https://github.com/urbit/urbit/blob/8d0cfd13b7e2d8c551fb008482309d29a188562d/pkg/urbit/vere/io/unix.c#L608-L614

**Comment by ohAitch** [comment]
Hm, as long as that's the only actually implemented action, can we make the mount-name argument optional? 😇

So that plain `|commit` means "just sync all active mountpoints".
