### ISSUE TITLE
Assertion '0' failed in noun/events.c:332

### ISSUE THREAD

**Issue by Zaphod101010** [urbit/urbit#3254]
Computer crashed while Urbit was running.  After a reboot, my star now fails to boot.
```

$ ./urbit namlyd
~
urbit 0.10.8
boot: home is /Users/namlyd/namlyd
loom: mapped 2048MB
lite: arvo formula 50147a8a
lite: core 590c9d56
lite: final state 590c9d56
loom: mapped 2048MB
loom: patch mug mismatch 62/0; (28ce51fb, 458707bf)
Assertion '0' failed in noun/events.c:332

bail: oops
bailing out
Assertion failed: (0), function u3m_bail, file noun/manage.c, line 677.
pier: serf error: end of file
```

**Comment by joemfb** [comment]
@Zaphod101010, this looks like memory corruption in the snapshot system.

Changes to the persistent state since the last snapshot are written into a patch (`control.bin` and `memory.bin` in `$pier/.urb/chk/`) , which is verified and implied to the snapshot (`north.bin` and `south.bin` in the same directory). Patches are normally applied synchronously, as soon as they're written. But if they exist on startup, they're also applied then. It appears you have a corrupted patch file, preventing patch application on startup.

Your urbit state is a pure function of the event log. If your snapshot is behind on startup, it's brought up-to-date by recomputing the relevant events as stored in the log -- event log replay. If there's no snapshot at all, the entire log is replayed.

So this should be an easy fix; removing the corrupted patch files should allow you to start with a stale snapshot, which will then be made current through log replay. To do this, simply remove `control.bin` and `memory.bin` from `$pier/.urb/chk/` (stash them elsewhere on the off chance that we need to debug further), and restart you ship.

**Comment by Zaphod101010** [comment]
removing control.bin and memory.bin seems to have solved the issue.  Thanks!
