### ISSUE TITLE
Chat doesn't load properly if the amount of new messages is greater than the screen height

### ISSUE THREAD

**Issue by bazfum** [urbit/urbit#3299]
**Describe the bug**
Chat doesn't load properly if the amount of new messages is greater than the screen height. In Firefox it will scroll to the top of the window and  show a few messages past the last read message. If you keep trying to scroll up it will eventually load more. The unread marker is absent. This has been going on for some time but seems to be worse with the last few updates. In safari, it does the same thing but the window is blank as well. The only fix is to scroll all the way to the bottom manually. This also removed the unread bar.

**To Reproduce**
1. Open a chat with many unread messages
2. Notice the window scrolls to the top and does not show all unread messages
3. In Safari, notice the window blanks after flashing the text
4. Scroll to bottom and everything is normal until you leave that chat

**Expected behavior**
The window will load all unread messages, and at least a page's worth earlier. The unread marker will show. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Base hash of your urbit ship. 0v17.6becj.i5l2t.arhhu.1mq93.1934v.g0vku.k3hhs.2tto7.s7jlb.6lba6

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12"
 - OS: 13.6
 - Browser Safari
 - Base hash of your urbit ship. 0v17.6becj.i5l2t.arhhu.1mq93.1934v.g0vku.k3hhs.2tto7.s7jlb.6lba6

**Additional context**

**Comment by bazfum** [comment]
After further testing it looks like it jumps randomly to the top of the scroll sometimes even if there aren't a large number of new messages.

**Comment by matildepark** [comment]
Oh, *iOS* Safari. Well, take note, #3298.

As for Firefox — it seemingly has traded places in terms of bugs with our old implementation. The old implementation had a constant scroll slam each message; it turns out Firefox was exempt from this. Firefox now has the scroll slam, but things generally work fine on Webkit and post-Webkit browsers. Firefox's flexbox implementation — the reason we have *two Chat implementations* — will be fixed in Firefox 81 (Sept 22), and I suspect at that time we'll rip out the Firefox-specific one, which will restore the scroll behaviour. 

I did note that a scroll up jumps to the top of the backlog page you've loaded in Firefox; I termed it an acceptable tradeoff due to the change in implementation coming in so short a time (in #3242).

**Comment by bazfum** [comment]
Loading to the top would be less of an issue if the green line for new messages was still there, these two bugs together make it hard to keep up with chats.

**Comment by matildepark** [comment]
@bazfum still encountering as of now?

**Comment by matildepark** [comment]
Chat no longer jumps at all.
