### ISSUE TITLE
Groups Membership list is not ctrl/cmd+F searchable

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#3356]
This was a lack/bug noted by Nick earlier: Basically it's hard to search for individual ships in a group's membership list because browser-searching doesn't work on that interface.

The ideal membership list is getting a redesign that directly implies the existence of a searching mechanism for a group's members, but we should fix this issue in the short term if we can.

**Comment by urcades** [comment]
Example given here: https://www.dropbox.com/s/ubgbw3tm3qz08r1/groups-searching.mp4?dl=0

A group is accessed, I navigate to its settings/member list, and I attempt to search myself in the results. The only text hit by my search is my 'root profile' ship name, the list of group members is ignored.

**Comment by tylershuster** [comment]
Yes, this is due to the list being virtualized a la #3229 

Because of this, unless the member exists in the first page of results, their text doesn't show up in the DOM hence no cmd+f.

Short-term solution is a) remove virtualization or b) the long-term solution

At the risk of stating the obvious, this affects #2983 — any affordances for search in chat or other large lists will have to be in-react, not in-browser. Of course, this is fine as we move toward OS2

**Comment by ohAitch** [comment]
Is there any way to render, like, the text without enough layout frills to slow down the browser? Something I notice about a lot of modern websites is things are "virtualized" out of existence breaking various built-in browser functionality(the largest victims by far being full-text search and scrollbar length accuracy).

I know github does it somehow, searching around https://github.com/urbit/urbit/blob/master/pkg/arvo/sys/hoon.hoon for me exhibits *blank frames* and is generally much slower than https://raw.githubusercontent.com/urbit/urbit/master/pkg/arvo/sys/hoon.hoon but does produce correct results.

**Comment by tylershuster** [comment]
I would love to know how it does this. Especially because the whole file exists in the source code of that page.

Something that I didn't try but might work is lazy-loading objects — the original problem was that loading the group page took a long time.

**Comment by liam-fitzgerald** [comment]
The bigger killer on render time with these lists are the sigils. I'm wondering whether it's worth caching sigils. Or maybe we should only render sigils if they're onscreen? To be quite honest, I'm not a huge fan of virtualising scroll unless it's absolutely necessary. I think the new groups layout will cap the list at say 100-200 and then have search builtin, so that we can comfortably check for the presence of members and so forth.

**Comment by tylershuster** [comment]
Yeah, why _aren't_ sigils memoized? That might be a huge boost right there to get them out of full components. I agree with you regarding the group list virtualization. Chat is another matter.

**Comment by matildepark** [comment]
Dope. Tagging @liam-fitzgerald since this task is superseded by new groups layout.

**Comment by tylershuster** [comment]
I wonder if it's worth adding search capability to the new virtual scroller component. I don't know exactly how it would work codewise but it would be a little search bar either at the top of, or invocable somehow on, the virtual list that searched through the text contents and scrolled to the matched place when found. It wouldn't be a full search for asynchronously loaded data, obviously, but at least it could search inside items that had been virtualized out of existence.

**Comment by liam-fitzgerald** [comment]
This is done and in `release/next-userspace

**Comment by matildepark** [comment]
Fixed in #3626.
