### ISSUE TITLE
Publish stuck in crash-loop after joining notebook

### ISSUE THREAD

**Issue by seanptmaher** [urbit/urbit#3396]
**Describe the bug**
After joining a notebook, I was met with a timeout, followed by an `%missing-subscription-in-unsubscribe`, followed by endless stack traces to the terminal. 

**To Reproduce**
I'm unsure what about the notebook is causing the problem, so I can't provide a definitive answer here, but the steps I followed were:
1. Try to join a notebook through the group interface
2. Wait a bit
3. Errors started appearing soonafter.

**Expected behavior**
Hopefully, joining the notebook, and if the notebook is unavailable, perhaps some information about why the notebook is unavailable.

**Screenshots**
These are various snippets being printed to the console:
As I boot the ship, I get:
```
[%missing-subscription-in-unsubscribe /channel/subscription/1598561228112-cc0b47/9]
```
Followed by a ton of stack traces which each look like:
```
error in %publish
%fact
! closing subscription
! /lib/resource/hoon:<[13 3].[13 29]>
! /lib/resource/hoon:<[12 3].[13 29]>
! /app/publish/hoon:<[2.111 7].[2.111 42]>
! /app/publish/hoon:<[2.110 5].[2.118 7]>
! /app/publish/hoon:<[2.108 5].[2.118 7]>
! /app/publish/hoon:<[2.106 5].[2.118 7]>
! /app/publish/hoon:<[2.089 5].[2.118 7]>
! /app/publish/hoon:<[2.087 3].[2.260 5]>
! /app/publish/hoon:<[2.086 3].[2.260 5]>
! /app/publish/hoon:<[534 11].[534 75]>
! /app/publish/hoon:<[533 9].[535 21]>
! /app/publish/hoon:<[532 9].[535 21]>
! /app/publish/hoon:<[531 9].[535 21]>
! /app/publish/hoon:<[530 9].[535 21]>
! /app/publish/hoon:<[528 7].[549 9]>
! /app/publish/hoon:<[465 5].[550 7]>
! /app/publish/hoon:<[464 5].[550 7]>
error in %publish
%fact
! closing subscription
! /lib/resource/hoon:<[13 3].[13 29]>
! /lib/resource/hoon:<[12 3].[13 29]>
! /app/publish/hoon:<[2.111 7].[2.111 42]>
! /app/publish/hoon:<[2.110 5].[2.118 7]>
! /app/publish/hoon:<[2.108 5].[2.118 7]>
! /app/publish/hoon:<[2.106 5].[2.118 7]>
! /app/publish/hoon:<[2.089 5].[2.118 7]>
! /app/publish/hoon:<[2.087 3].[2.260 5]>
[....]
```
With intermittent messages which look like:
```
%publish: received 2nd watch-ack on [[i=%~.out t=[i=~.~dasrun-fadben t=[i=~.publish t=/subscribe/~dasrun-fadben/hoon-for-lispers]]] [p=~dasrun-fadben q=%publish] /notebook/hoon-for-lispers]```
```
Here's a screenshot of failing to join the notebook -- no errors in the console, just "Unable to join the notebook". 
![image](https://user-images.githubusercontent.com/39571964/91496253-574df580-e8ab-11ea-9d4f-5d35dcbabe14.png)

**Desktop (please complete the following information):**
 - OS on which the ship is running (uname -a): `Linux 5.3.0-1032-gcp #34~18.04.1-Ubuntu SMP Tue Jul 14 22:07:36 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - OS on which browser is running (uname -a): `Linux 5.7.17_1 #1 SMP Fri Aug 21 13:33:56 UTC 2020 x86_64 GNU/Linux`
 - Browser: Chromium Version 84.0.4147.125 (Developer Build) (64-bit) 
 - Base hash: `0vo.j1ero.slhgf.9ei39.khjic.7n0kh.6dvfk.f5qas.olpv8.ct3ei.2inqt`

**Additional context**

**Comment by matildepark** [comment]
Publish in its latest incarnation times out the join request on the front-end after ten seconds; it's unclear if the back-end does the same, unlikely as sometimes the notebook just shows up much much later on a new load. 

The stack traces are a different issue, and I'm unsure what prompts those. @ixv anything spring to mind?

**Comment by jessewh** [comment]
I am having a similar issue to the above. 

Describe the bug Tried to join a group (Community) in Landscape, got spinning wheel and no eventual response on landscape followed by endless stack trace. 
To Reproduce Steps to reproduce the behaviour:
1. Tried to join group 
2. Wait 
3. Errors
Expected behaviour Join the group. Note that I have tried `|cancel` and `|cancel %force` which I expect is the reason for the `eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/1.110/5]` stack trace messages. 
Screenshots When I boot my ship I get:

`eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/1.110/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/677/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/1.101/4]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/438/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/1.186/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/497/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/595/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/1.118/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/27/4]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/457/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/1.258/5]
eyre: canceling ~[//http-server/0v1q.4l9mn/1.364/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/616/5]
eyre: no channel to cancel ~[//http-server/0v1q.4l9mn/504/5]
http: web interface live on http://localhost:80
http: loopback live on http://localhost:12321
pier (1741859): live
ames: czar feb.urbit.org: ip .34.82.25.47
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 11]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 12]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 14]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 16]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 18]
`

System:
* OS: Linux 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* urbit-v0.10.8-linux64
* 0vq.8jhrd.u7f79.leomd.9c1fr.ssc90.h1gpc.vrn1r.nej76.vq098.kprsf

Additional context: 
I have been having this issue for a while now. I breached about a month ago hoping to solve the issue. I also did try to join ~dopzod/urbit-help

**Comment by jessewh** [comment]
As an update, after another breach this seems to have sorted itself. Immediately after firing the ship up I did receive the error message: 

```[%missing-subscription-in-unsubscribe '1603773449095-a50118' 11]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 12]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 14]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 16]
[%missing-subscription-in-unsubscribe '1603773449095-a50118' 18]
```
multiple times but it is gone now (after about a day) and I can join groups again.

**Comment by matildepark** [comment]
Original problem resolved. Obsolesced by #3473.
