### ISSUE TITLE
pull doc updates and fixes

### ISSUE THREAD

**Issue by fsteinel** [urbit/urbit#346]
Please cherry-pick this to 
- add cli apps mount, unmount, fix ++dust example and add more examples to /pub/doc/hoon/library/3bh "section 3bH, names etc"
https://github.com/urbit/urbit/commit/ef3d93b506d575df943c273d3af6051b2518878e
- apply changes to cli apps docu:
https://github.com/urbit/urbit/commit/723a8c2976f1af9299eefad3d0659952d2f2f908

(A pull request shows to many changes: https://github.com/urbit/urbit/compare/master...fsteinel:master)

**Comment by philipcmonk** [comment]
I'll merge these momentarily.  The reason, by the way, that the pull request is so large is because your repo predates us rewriting history once or twice to get rid of a bunch of the pills (or rather, archive them in urbit/archaeology{,2}).  I recommend either just forking the repo anew or doing some hard resetting and force pushing to get back in sync.  I'll just cherry-pick these guys, though.
