### ISSUE TITLE
king-haskell: noun/tank printing doesn't respect termwidth

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#3488]
Imagine you print the subject in dojo by running `.`. It's a big noun, so it'll get split over multiple lines.

Evaluating `.` in vere, in a terminal that's ~50 characters wide, gets you the following output:

```
> .
[ [ our=~nut
    now=~2020.9.15..15.29.29..1337
      eny
    \/0v27t.j02u1.tiifc.3ele4.sofj3.t03uq.f6p9e.\/
      4tvkb.7n1to.o6to3.kfmr1.pk4tq.sjgu6.lf2bh.
      a2t0q.kec0e.38pm2.2r7rt.ke7ml.pberr.423oo
    \/                                          \/
  ]
  < 20.khw
    31.ezk
    9.dpx
    36.oqd
    94.zou
    247.yaz
    51.pkf
    129.ono
    41.mac
    1.ane
    $141
  >
]
```

Doing the same in king-haskell (rc5) though, still with a ~50 char wide terminal, gets you this:

```
> .
[ [ our=~nut
    now=~2020.9.15..15.31.00..faf9.b994.e1a3.f466
      eny
    \/0v1ki.4009k.ejg5t.ee9ak.tjg73.vde2s.p9ncv.o2k85.t3l75.36rcd.r1ckm.dp026\/
      .kerj6.mpdcr.ui767.h3eng.4lb7j.6catl.8290o.8bof1.qbaaj
    \/                                                                       \/
  ]
  <20.uvp 31.qbf 9.dpx 36.oqd 94.zou 247.yaz 51.pkf 129.ono 41.mac 1.ane $141>
]
```

It looks fine here on gh, but in the narrow terminal, the text gets wrapped. Not pretty! Looks like it uses an 80 character default, instead of respecting the actual width of the terminal.

https://github.com/urbit/urbit/blob/4e82588cc045fe9e9503e0ddb2b6822479d196bb/pkg/hs/urbit-king/lib/Urbit/Vere/Pier.hs#L113-L114

Curiously, using `~&` prints the noun on a single line, despite the resulting noun-text being >260 characters.

```
[[our=~nut now=~2020.9.15..15.32.40..e096.bb98.c7e2.8240 eny=0vm7.96foq.j5a0v.4gh1j.m6c0t.a66v7.va1fg.b7ohq.31ump.6e6pd.lfrsi.19477.qssg1.8h1jh.mamea.pntgb.dgeul.48l4h.8cdou.qa5ru.m1g94] <20.uvp 31.qbf 9.dpx 36.oqd 94.zou 247.yaz 51.pkf 129.ono 41.mac 1.ane $141>]
> ~&  .  42
42
```

**Comment by eglaysher** [comment]
There's a lot going on here with how the terminal system in king haskell isn't complete w.r.t. terminal size.

KH multiplexes the terminal so that, when you have a ship running on your current computer, you can just type:

```
urbit-king con ~/path/to/pier
```

and get the last several lines of scrollback and your current prompt. The problem here is that almost none of this code has a concept of terminal size and both getting and acting on that context will take a lot of work. Off the top of my head:

- Move various tank printing responsibility into the terminal driver, so that it's an internal effect instead of something that gets processed separately in `printTank`, as you mention. 

- Actually hook up terminal size detection into the terminal connection code. It does this once at startup, and is a lie on several of the paths.

- Actually have the terminal subsystem alert your Urbit of changes in the terminal size. This only happens once on startup with a hard coded event.

**Comment by eglaysher** [comment]
OK, the real two parts here are:

- The part regarding `~&`, slog handling. I plumbed the slog handling all the way into the terminal driver so `(Atom, Tank)` could be printed very locally in the rest of the output path. This doesn't matter since the current Tank rendering code in Urbit.Noun.Tank appears to be a work in progress that doesn't use the passed in width for calculating the output. Actually doing a good job of this will require actually implementing tank rendering.

- The part where we aren't sending Urbit the proper terminal sizes. Something is wrong about how we tell Urbit what its initial terminal size is, and that's what's causing the immediate thing you're seeing here.

**Comment by ohAitch** [comment]
> Actually doing a good job of this will require actually implementing tank rendering.

Does king have a u3v equivalent? Iirc c vere does this by literally calling `++wash`, which should be fairly straightforward.

**Comment by eglaysher** [comment]
It does not. There's no ivory pill equivalent.

**Comment by ohAitch** [comment]
Ah. I suppose one drawback of doing a runtime in a high-level language is it tempts you to reimplement functionality that should have just stayed in hoon, where in C this would obviously not be the simplest solution - you do need jets, but hopefully those are mostly limited to type conversions and other primitives.
I think this reduces my recommendation to "add an ivory pill equivalent, clean out all code that already exists in ivory.pill". You can of course instead transliterate, or even cleanroom reimplement by looking at the output and not the original code if you truly wish.

**Comment by joemfb** [comment]
king-haskell doesn't have a nock interpreter -- it's *just* i/o drivers and event persistence.

**Comment by ohAitch** [comment]
And this is the first instance of i/o drivers performing fundamentally urbity operations on nouns? Does it not have a `cue`, for example?
If so, this recommends moving the width logic into the process whose i/o it's driving, but if that would be awkward then sure transliteration may be warranted after all.

**Comment by joemfb** [comment]
King haskell is deprecated
