### ISSUE TITLE
publish: refreshing on notebook page gives error

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3506]
**Describe the bug**
Refreshing a notebook page gives an error "group is not defined

**To Reproduce**
1. Go to publish
2. Click on a notebook
3. Refresh the page

**Expected behavior**
The notebook loads again

**Screenshots**
<img width="900" alt="image" src="https://user-images.githubusercontent.com/3999320/93525545-12860f00-f8eb-11ea-985d-cae03b65016d.png">

**Desktop (please complete the following information):**
 - MacOS
 - Firefox
 - `naoqh`

**Comment by matildepark** [comment]
Truth be told, I've never been able to instigate this issue because my dev ship environment has #3065 -_-

**Comment by matildepark** [comment]
Oh, you know what? This may have been introduced only on release/next-userspace as of #3516? Which is weird because it comes after this issue. But you're using localhost:9000 and the only unsafe access of `group` is this:

https://github.com/urbit/urbit/blob/107cc7ab5fa84796baefb87396ee7b11d97e66f4/pkg/interface/src/views/apps/publish/components/lib/Notebook.tsx#L68-L69

Feel free to confirm on livenet. As I said, I can't actually confirm for myself on this one.

**Comment by tylershuster** [comment]
Yeah we got this on livenet, only it says `h is undefined`
