### ISSUE TITLE
Chat: Message attributed to incorrect author

### ISSUE THREAD

**Issue by sivner-figbus** [urbit/urbit#3534]
**Describe the bug**
I replied to a post in a chat, with a URL, followed by some words.

In the console, both URL and words are correctly attributed to me.

As viewed in Landscape, in the chat, the words are attributed to the previous writer.

**To Reproduce**
I cannot reproduce this on demand.

In the screenshots below, the console screenshot correctly shows the order of events:

~botter-nidnul writes
"the rumor with[...]"
I reply with the URL, and the text "is good - on[...]"

![image](https://user-images.githubusercontent.com/67953485/93680272-984dba00-faa5-11ea-9e67-22976e0d23f1.png)

![image](https://user-images.githubusercontent.com/67953485/93680713-bfa48700-faa5-11ea-9a76-af723c7a1094.png)

(images have been edited to block some text, I believe the bug remains clear)

Issue remains after a shift+reload.
Issue remains if I use an incongito mode window. 
Issue remains if I use Chrome instead.
Issue remains if I use Safari on my iphone instead.

However the chat messages display correctly in the "Ursus chat" IOS Urbit client app.

 - OS: [e.g. MacOS 10.15.5]
 - Browser [Brave 1.13.86]
 - Base hash of your urbit ship. 0v1c.o253s.lpvsm.t4fr4.en39p.mq1rj.qjnrk.tjnrl.c5t1i.o68th.naoqh

**Comment by matildepark** [comment]
> Issue remains after a shift+reload.

This is the crucial part; it’s not a quirk of banding an update, it’s consistent FE behaviour. Gut check, I think this is because the former “render message with author” logic was for, like, the backwards direction? But for whatever reason this occurs when you share a url? Or maybe this one time?

(Or perhaps the message order in chat store is weird.)

**Comment by sivner-figbus** [comment]
It's not consistent. I just tried in the Watercooler group and it behaved itself:

![image](https://user-images.githubusercontent.com/67953485/93681496-1a3de300-faa6-11ea-85e6-7cf104bba2f1.png)

**Comment by tylershuster** [comment]
Where is the original occurrence? If it's in a public group I'll take a look.

This is almost assuredly a case of mis-ordered messages in the store itself, which is a known issue. I might be able to write a patch for the current FE implementation that takes this into account.

**Comment by sivner-figbus** [comment]
![image](https://user-images.githubusercontent.com/67953485/93685538-f7143300-faa7-11ea-8651-d2d59cf87ab9.png)

In a group "~timluc-miptev/the-collapse" in chat "politics broadly defined": 
~timluc-miptev/politics--broadly-defined-5795

**Comment by tylershuster** [comment]
Ok, so there's a quick fix for this which is to sort messages by their number instead of by their sent date. This causes a problem in that some people have messages stored on their computers out of order, which is what I tried to avoid surfacing. However, leaving and rejoining the channel should fix it. It seems that this solution is preferable because it will need to be the implementation when graph-store validates message order.

**Comment by matildepark** [comment]
That one person with the backwards chats ...

**Comment by tylershuster** [comment]
I can't remember, did he leave and rejoin?

**Comment by matildepark** [comment]
I don’t think so. We should DM and maybe get them to test a fix before deploy. If I can remember I will reach out

**Comment by tylershuster** [comment]
This happened because the URL got the earlier time stamp but the later number. It displayed "as part of the previous message" because it had a later number than the text, so it displayed without the sigil. The previous timestamp however caused it to be displayed earlier in the stack￼
