### ISSUE TITLE
RFC: Channel CORS Policies

### ISSUE THREAD

**Issue by tylershuster** [urbit/urbit#3555]
Context: Typescript API Library

Urbit API ("Airlock") clients can subscribe to events on channels, on which they watch Server-Sent Events (SSE). In JavaScript this is done using the EventSource object.

My problem is that browser CORS requests are a bit restrictive, requiring the proper Access-Control-Allow-Origin headers to be sent by the server (eyre).

PUT|POST|GET requests can finagled to succeed, but EventSource is a bit more finicky.

On Landscape this isn't a problem because we have a trusted URL, from which *everything* is being served. On node, python, or other backend stacks this isn't a problem because it doesn't complain about CORSy stuff. On the browser we do have a problem, with good reason. We don't want to execute arbitrary JS in userspace. However, it means that unless I a) proxy requests through a node server or b) only run the app from the same origin, I can't write a browser app that listens back to events. 

Example: Pop-out chat client as browser extension.

I'd like input from more seasoned urbiteers on how to mitigate this problem, either by telling me I'm thinking incorrectly, or by implementing the necessary steps in eyre.

**Comment by tylershuster** [comment]
If I was just slapping this together I'd put 'Access-Control-Allow-Origin=*' on login and channel urls and call it a day but I wonder if that has security ramifications

**Comment by Fang-** [comment]
> I'd like input from more seasoned urbiteers on how to mitigate this problem ... by implementing the necessary steps in eyre.

This was on my stack at some point, but didn't have high enough priority to stay there.

CORS is fun because it ties into bigger "permission management" questions. What origins do I want to allow access to my ship? Blindly allowing anything is the MVP, but it's also a security issue.

Some time ago I wrote a thing in userspace for [tracking permitted origins](https://github.com/Fang-/suite/blob/master/app/corsac-store.hoon) and [augmenting apps with CORS handling based on that](https://github.com/Fang-/suite/blob/master/lib/corsac.hoon). This has been running on a live ship doing real things, and it's worked fine.

I imagine you ultimately want something along those lines, but with a fancy UI frontend and tighter integration with eyre. Perhaps you want to implement that entire thing in eyre, and just have a small userspace layer for making access to those knobs/toggles easier? It wouldn't be terrible, but does increase the size of the "urbit has to know about http and browser things" wart...

**Comment by Fang-** [comment]
Just posted a [cors.txt](https://github.com/urbit/urbit/files/5295683/cors.txt) to [urbit-dev](https://groups.google.com/u/1/a/urbit.org/g/dev/c/bb82dwEJGzM).

**Comment by tylershuster** [comment]
I believe "king" is what the kids are saying

**Comment by matildepark** [comment]
(Honestly, topics like this should probably just be on urbit-dev anyway?)
