### ISSUE TITLE
chat: leaping to chat always shows joining screen

### ISSUE THREAD

**Issue by matildepark** [urbit/urbit#3610]
via @galenwp. Presumably introduced after #3507? We want to redirect in cases where we have the chat, which shouldn't show the join screen at all.

**Comment by tylershuster** [comment]
I would be very surprised if that PR had anything to do with this issue. As you can see below, the links for each channel contain the `~join` parameter:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/3999320/94497995-cde15a00-01ad-11eb-99ba-e18e9b221f57.png">

#3507 may have made the problem more visible by waiting until confirmation to redirect, but the underlying behavior still existed.

**Comment by matildepark** [comment]
Of course. We use the join parameter for everything in Leap because all the join flows have a catch to redirect if we have the channel.

**Comment by tylershuster** [comment]
Ok, it's basically this line that did it:

https://github.com/urbit/urbit/pull/3507/files#diff-0b782255eebc0e802da95cbb29fb3b42

Instead of immediately pushing state, it waits to join. That could definitely be incorrect — I mean theoretically it's correct but if it gets handled properly without producing this behavior might as well revert it (but still replace instead of push).

**Comment by tylershuster** [comment]
Update: removing this behavior reverts to the previous bad behavior of "leap to a channel to which we aren't subscribed, see the URL navigate, a flash of white, then a redirect to the bare /~chat screen"

**Comment by tylershuster** [comment]
We would need a way to check if we're already subscribed while on the join page to fix this.

**Comment by matildepark** [comment]
Fixed in #3626.
