### ISSUE TITLE
chat messages don't show as pending

### ISSUE THREAD

**Issue by belisarius222** [urbit/urbit#3847]
**Describe the bug**

Report from another user:
> The chat hasn’t been working well for me, when I send messages it doesn’t show it as pending anymore, so I have no idea if it’s attempting to send or not.

**To Reproduce**
unknown

**Expected behavior**
chat message shows as pending

**Screenshots**
none

**Desktop (please complete the following information):**
unknown

**Smartphone (please complete the following information):**
unknown

**Additional context**
the chat host ship goes down sometimes; not sure if related

**Comment by tylershuster** [comment]
This is *probably* not correct. What I *expect* is happening is that the message is sending, then due to the longstanding message ordering bug the message is showing `n` numbers up in the backlog, and is showing as pending there. I see this a lot but I only know to look for it because of how much sleep I've lost over it. I expect that this will be a non-issue when graph-store fixes, and will be unfixable and unreproduceable until then.

**Comment by matildepark** [comment]
Fixed in #4058.
