### ISSUE TITLE
dms: after deleting a DM, can't start a new one with same participants

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#3926]
**Describe the bug**
Let's say there's a DM between ~zod and ~nec, hosted on ~zod. ~zod deletes the DM, ~nec gets booted with a spinner (different issue). Then ~nec tries to make another DM with ~zod and it will just hang.

**To Reproduce**
See above

**Expected behavior**
DMs should clean up completely on deletion.

**Base**
`tdo1o`

**Comment by matildepark** [comment]
I encountered this doing tests on ~dabben-larbet and it's super annoying. Say ~haddef breached. Not only would that DM not clean up, but if I made a fresh one, or *if either of us make a fresh one*, the UX is just permanently broken. It'll dig up the chatlog from the first version but the other party won't get any messages.

This behaviour is because chat-hook doesn't delete resources ever, full stop, as per conversations around "preserving archived content", but it has no way of handling archived content.

@liam-fitzgerald Would the graph-store's archive functionality help us here?

**Comment by matildepark** [comment]
Talked with @liam-fitzgerald in 1:1 for upcoming graph-store migration. I suggested:

- When migrating chats to graph-store, if there was nobody in the chat, migrate it as an archived graph;
- Facilitate some basic delineation of archived content in the sidebar;
- Add a catch in our "create or redirect to the DM" logic to check for `archived: false`

**Comment by matildepark** [comment]
I guess, additionally, we'll want to have left or deleted chats be thrown into that archive story as well.

**Comment by matildepark** [comment]
OK so, checked in with @liam-fitzgerald. We thought about how to solve this for everyone, but the main clincher is that it affects import/export logic and we don't want to touch that while it's in test mode. What we think we should do is

- If you leave or delete a chat, because we have no conception of `archive` in chat-store, we should remove it from chat-hook, chat-store, etc. and write it to disk as json (that you can format fairly easily with a script, etc. etc.).
- We'd add an on-load to process this for all chats without subscribers, prompting immediate archives of all broken chats, alleviating all current users with issues.

We're basically blocked on the breach in this regard, and we still expect the Chat migration to be ready for the following OTA after breach. If it's still tied up, we can write this solution within a day. For now, it would mean we'd have to edit the import/export code that isn't merged yet and deploy it alongside the import/export code, which is a lot of variables in a very tenuous situation...

**Comment by vvisigoth** [comment]
Thanks all.
—
~poldec-tonteg
http://urbit.org

**Comment by matildepark** [comment]
Fixed in #4058. If you delete a DM, you can now create a DM with the same participant.
