### ISSUE TITLE
OTA 1.0.71 Fails

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#3952]
**Describe the bug**
OTA compiles kernel, then fails with:
```
crud: %drip-fail event failed
drip failed
[%poke p=%wake]
%leap
[%feck p=%lyra]
vega: ruin
[%no-cast-from %publish-info %mime]
[%error-building-cast %publish-info %mime]
[%error-building-mark %publish-info]
[ %validate-page-fail
  /app/publish/notebooks/collapse-open-blog/publish-info
  %from
  %publish-info
]
[%error-validating /app/publish/notebooks/collapse-open-blog/publish-info]
```
**System (please supply the following information, if relevant):**
 - OS: Ubuntu 18.04
 - Urbit 1.0.70
 - hash: `tdolo`

**Comment by joemfb** [comment]
I ran into this, as did @philipcmonk. It looks like it was a latent issue caused by the publish migration (#3473). The `%publish-info` mark was "tombstoned", but files of that mark remained in %clay.

The file is obsolete as far as `:publish` is concerned, so you can just delete it:

```
> |rm %/app/publish/notebooks/collapse-open-blog/publish-info
```

And then manually trigger the merge:

```
|merge %home (sein:title our now our) %kids
```

Those steps worked for me, anyway. If you were hosting multiple notebooks, you may need delete a `%publish-info` from each one.

/cc @liam-fitzgerald, @matildepark

**Comment by jfranklin9000** [comment]
Same problem.  @joemfb's solution worked for me.

**Comment by timlucmiptev** [comment]
Worked like a charm; I'll close this.

**Comment by matildepark** [comment]
I personally handled this with a force merge, and if you have no third party applications, it should be just as fine. 

```

|merge %home (sein:title our now our) %kids, =gem %only-that
```
