### ISSUE TITLE
hark: adding nodes produces multiple notifications or unreads

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#4012]
**Describe the bug**
Instead of receiving one notification per comment, I get several

**To Reproduce**
1. Post a link in a collection
2. Someone makes a comment
3. Get ~3x notifications per comment

**Expected behavior**
One comment = one notification

![Screen Shot 2020-11-24 at 2 32 00 PM](https://user-images.githubusercontent.com/1609955/100148819-e34bcb00-2e62-11eb-8d14-1c1a0942be1c.png)

**Comment by matildepark** [comment]
Somewhat separate but somewhat related to #3971.

**Comment by liam-fitzgerald** [comment]
largely sure that this a result of stale versions of landscape. just forced the ota on ~bitpyx-dildus, any other hosts known to repro this issue?

**Comment by vvisigoth** [comment]
@liam-fitzgerald  this is still an issue on ~bitpyx which is up to date

**Comment by matildepark** [comment]
As per investigations with @liam-fitzgerald overnight as we watched the deploy go out, this appears to be an issue regarding the behaviour between hark-graph-hook and the graph-store itself. 

Multiple addNode events may occur in graph-store, which no-ops; hark-graph-hook listens to graph-store for updates. The duplicate updates are not in the log, but they are in hark-graph-hook.

This has been a latent issue with graph node notifications which has, as of #4058, become a higher priority, since it leads to unreads and notifications coming in high numbers. 

@liam-fitzgerald @tacryt-socryp I would like you to consider this priority one and if we can get a band-aid fix out to prevent surfacing these duplicates soon, we should.
