### ISSUE TITLE
Newly created group, trying to invite someone, get "Invalid Integer: NaN is not a valid exponent"

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#4053]

**Comment by matildepark** [comment]
Need more information. This is from the landing page of the group? Because can't replicate.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/20846414/100789252-3209df80-33e4-11eb-812e-963d9d888d38.png">

Are you clogged on OTAs? You're describing something quite similar to #4001, which we patched and released recently.

**Comment by tacryt-socryp** [comment]
Turns out my branch was 57 commits behind. All good.
