### ISSUE TITLE
~bolbex-fogdys `%hark-graph-hook` subscription close issue

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#4148]
<img width="1536" alt="Screen Shot 2020-12-12 at 3 27 38 PM" src="https://user-images.githubusercontent.com/1377557/101995306-a66b3b00-3c8e-11eb-83a6-0899260ecbfd.png">

It's saying it received a 2nd watch-ack, unsure why. It's constantly spinning with this issue. Could this be a `%gall` level issue? Seems most likely...

What do you think @liam-fitzgerald ?

**Comment by philipcmonk** [comment]
Is ~bolbex subscribed to the bulletin board? Seems like it shouldn't be

**Comment by matildepark** [comment]
@philipcmonk @tacryt-socryp Did you figure this one out? I recall a group session between you two happening.

**Comment by tacryt-socryp** [comment]
Didn't figure it out! Pairing session was for a different bug

**Comment by liam-fitzgerald** [comment]
....? The stack trace points to a simple `~&` statement, so I'm absolutely baffled as to how that could crash. Perhaps a crash in the pretty printer?

**Comment by matildepark** [comment]
Did you rewind to December 12, 2020's version of that  hook

**Comment by liam-fitzgerald** [comment]
yep

**Comment by liam-fitzgerald** [comment]
oh nvm, it was even earlier. This is now fixed because we no-op if we don't have a group

https://github.com/urbit/urbit/blob/2d6913794f611093feefc8895294dcb2d07ec7a0/pkg/arvo/app/hark-graph-hook.hoon#L198

https://github.com/urbit/urbit/blob/3f224b13b7198f89ef4dbc537182207ee74ccce6/pkg/arvo/app/hark-graph-hook.hoon#L197
