### ISSUE TITLE
Channel deletion does not get pushed to members

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#4160]
Created a channel in a group by mistake. Deleted it, and it disappeared from the sidebar on the host of the group & channel. But for members of the group, the channel remains in the sidebar.

**Comment by matildepark** [comment]
This is actually specifically a metadata-store issue — can you confirm this wasn't just delayed propagation? Is the channel still there for everyone?

**Comment by Fang-** [comment]
Can confirm it's still there.

**Comment by tacryt-socryp** [comment]
Okay, sounds good. I believed that this was fixed, but I'll work on a repro.

**Comment by tacryt-socryp** [comment]
The normal flow is the following: group host sends a `%remove-group` action to their own ship's store, which causes a fact to be sent to the `%group-push-hook`. This fact runs through `+take-update` to send out side effects for various facts, where the side effects are sent out after the original update. The host ship sends out a `%remove-group` fact to all subscribers, and the card immediately after that sends a `%kick` to all subscribers. The `%group-on-leave` thread is triggered and cleans up all group-associated data both on the host and all the client ships.

Within my explanation above of the code execution path, this issue cannot occur. I must be mistaken in some way, so I'll step through each part to determine what the root cause is.

**Comment by tacryt-socryp** [comment]
I've fixed it. Simple issue with the `%graph-delete` thread.
