### ISSUE TITLE
DMs: Post-network breach + personal breach, unable to send messages to previously-DMed ships, but can receive

### ISSUE THREAD

**Issue by urcades** [urbit/urbit#4177]
**Describe the bug**
Ship context: I am a hosted ship, and weathered the network breach roughly, and ended up needing to personal breach, which reset everything as expected.

I have been able to join old groups and channels with no issues, but when I have attempted to DM ships I had previously been in contact with, my messages don't appear to reach the other party. I have needed to ask them via a group to send me a DM, which apparently goes through, and is an extension of the previous DM they had with me pre-breach.

In some cases, as demonstrated in the below convo, DMs don't seem to work at all:

<img width="549" alt="Screen Shot 2020-12-16 at 10 41 42 AM" src="https://user-images.githubusercontent.com/1195363/102371092-d31f9b00-3f8b-11eb-9173-dcad6f3a46b3.png">

<img width="600" alt="Screen Shot 2020-12-16 at 10 43 43 AM" src="https://user-images.githubusercontent.com/1195363/102371106-d6b32200-3f8b-11eb-82b5-5ccfc8e66df8.png">

<img width="599" alt="Screen Shot 2020-12-16 at 10 44 51 AM" src="https://user-images.githubusercontent.com/1195363/102371120-d9157c00-3f8b-11eb-87a6-1a19cf7d1170.png">

The only visible error I appear to receive in my devtools is the following:

<img width="452" alt="Screen Shot 2020-12-16 at 10 34 53 AM" src="https://user-images.githubusercontent.com/1195363/102371208-f1859680-3f8b-11eb-9a7a-b0e41f5d490a.png">

I will supply more context as I try out DMing other people.

**To Reproduce**
I'm not quite sure — this seems to be an issue I'm encountering when I send DMs to others I have previously DMed, but I can apparently receive DMs and accept them just fine.

**Expected behavior**
I expect to be able to send DMs to people and have them work as expected.

**Desktop (please complete the following information):**
 - OS: macOS Version 11.1 (Build 20C69)
 - Browser: 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64)
- +trouble:

```
[ [ %base-hash
    ~[0v1i.m17tc.thht3.60qpc.bmknd.npdqk.8h3f1.luqj9.7k8ls.knqfs.u8adu]
  ]
  [%sour-hash 0v1i.m17tc.thht3.60qpc.bmknd.npdqk.8h3f1.luqj9.7k8ls.knqfs.u8adu]
  [%home-hash 0vd.h6bti.hr352.u95m1.quger.c84jq.k0c5u.t6ogv.vo7kl.ft4b6.bcpvp]
  [%kids-hash 0vd.h6bti.hr352.u95m1.quger.c84jq.k0c5u.t6ogv.vo7kl.ft4b6.bcpvp]
  [%glob-hash 0v5.bo337.25di9.mg5d5.i9vun.5qaqe %done]
  [%our ship=~fabled-faster point='2055146934' life=[~ 7] rift=[~ 5]]
  [%sponsor ship=~sabbus point='3510' life=[~ 3] rift=[~ 2]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Comment by vvisigoth** [comment]
cc @tacryt-socryp @liam-fitzgerald not sure what the new logic inserted into dead DMs is, can you take a look at this and let's talk EOD at meeting.

**Comment by vvisigoth** [comment]
OK I tried this with Jared and it seems to happen when the original DM was
hosted on a ship which personal breached. If the party that breached has to
recreate the DM, it fails in the ways outlined here.

Here is what happened to me

1. ~nidsut-tomdun breached
2. ~nidsut-tomdun tried to reinvite ~poldec-tonteg to a DM (they previously
had one, hosted on ~nidsut-tomdun before breach)
3. An invite appears on ~poldec-tonteg
4. Accepting invite has no effect
5. Attempting to leap to DM with ~nidsut-tomdun gives me a join screen
which, when clicked, gives me an eternal spinner
6. ~nidsut-tomdun deletes our existing, dead DM on his ship
7. ~poldec-tonteg initiates a DM with ~nidsut-tomdun and it works as
expected
—
~poldec-tonteg
http://urbit.org

**Comment by liam-fitzgerald** [comment]
ok have tracked down the cause: when we rewatch after a kick due to breach, this new watch will go out against the old life of the breached ship and thus will forever dangle, preventing us from cleaning up after the expected watch-nack. This actually works fine when the host deletes the chat but does not breach.

**Comment by liam-fitzgerald** [comment]
cc: @belisarius222 @philipcmonk

**Comment by vvisigoth** [comment]
wait wat
—
~poldec-tonteg
http://urbit.org

**Comment by belisarius222** [comment]
Just read Gall's `+mo-breach` and `+ap-breach`.  Gall cancels incoming and outgoing `%watch` subscriptions, but it doesn't track un-acked `%poke`s or do anything about them when a peer breaches.  It seems to me that Gall should track outgoing foreign `%poke`s and auto-nack all of them on breach.

**Comment by vvisigoth** [comment]
Ah, OK can you just throw that info into another issue for gall?
—
~poldec-tonteg
http://urbit.org

**Comment by belisarius222** [comment]
Oh, no, I was wrong, you're talking about `%watch`es.  Well, Gall should cancel all of those when a peer breaches, both incoming and outgoing.  When the app retries the `%watch`, Ames should try that at the peer's new life -- unless there's a race condition where Gall is doing this before Ames hears about the breach.

**Comment by belisarius222** [comment]
Ames and Gall both subscribe to Jael's `%public-keys` notifications for ships they're communicating with.  Those notifications aren't sent to any particular vane first; the gifts are given in mug order.  If Ames gets it first, it will clear its messaging state with the peer, then Gall will adjust the app's state and notify it of the kick, engendering a resubscribe, which Ames then correctly enqueues and begins sending over the wire.

However, if Gall gets the breach notification before Ames, it will ask Ames to retry, *and then* Ames will clear its state, including the outbound retry `%watch` message (which might have already been enqueued to go out to Vere, but even if it did, it would be sent to the peer's old life).  In this case, there's effectively no retry.

This makes me think Jael should tell Ames about the breach, and then Ames should tell Gall.  That way there's no ordering ambiguity, and vanes still don't have to know which other vane has subscribed to it.  I also think Gall should track outgoing `%poke`s so that it can generate a nack for them if the peer breaches before responding.

Long-term, to me this all adds support for the idea that we might want to refactor Ames to speak the Gall `%poke`/`%watch` protocol instead of (or maybe in addition to) the Arvo `%pass`/`%give` protocol.

**Comment by belisarius222** [comment]
Sorry, didn't mean to click the "close" button.

**Comment by tacryt-socryp** [comment]
Is this a kernel-level bug?

**Comment by belisarius222** [comment]
I think so, yes.

**Comment by tacryt-socryp** [comment]
Okay. Am interested in learning more if you're free to talk today or tomorrow.

**Comment by joemfb** [comment]
I agree that breach notifications should go through %ames to anything else that needs them.

**Comment by philipcmonk** [comment]
Heh, someone want to guess the problem:

https://github.com/urbit/urbit/blob/6499eb5fe0bd81c91f12d6f9ebcc6843b2ca7ac7/pkg/arvo/sys/vane/jael.hoon#L675-L684

This was super confusing to me because I *knew* we solved this problem a while back, until I remembered we solved it with that naughty trick of inspecting the wires...

While this should be properly solved eventually, for now we should just make +sorter either use a specific ordering or sort by first letter.

**Comment by vvisigoth** [comment]
Any way we can get a fix into taht /sys OTA that is "about" to happen?
—
~poldec-tonteg
http://urbit.org

**Comment by philipcmonk** [comment]
Yeah, for sure.  I can write a quick fix.  @liam-fitzgerald or someone else, do you have a convenient way to test it?  Usually I would never touch this stuff without Aqua available, which is why we shouldn't try a more disruptive fix right now, but just restoring the previous behavior should be safe enough if we can verify it fixes this issue.

**Comment by liam-fitzgerald** [comment]
#4181 + the necessary pill shenanigans + cloning bridge and running npm run pilot + mapping the necessary galaxy domains in your /etc/hosts (zod.example.com, etc. ) is enough to get urbit working on a local eth chain

**Comment by belisarius222** [comment]
> we solved it with that naughty trick of inspecting the ducts

inspecting ducts is definitely not Santa-approved

**Comment by philipcmonk** [comment]
If you've got an environment set up, can you give #4184 a quick whirl?  Otherwise I can give it a shot in a little bit

**Comment by belisarius222** [comment]
> someone want to guess the problem

Is it that we switched to whole vane names in wires, and `(lth %ames %gall)` is `%.n`?

**Comment by philipcmonk** [comment]
Yep, little endian strings...
