### ISSUE TITLE
Unable to archive notifications

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#4187]
**Describe the bug**
Archiving a notification fails on a js error. The urbit-side update seems to happen, but something breaks in the ui.

**To Reproduce**
1. Go to Notifications
2. Click on Archive
3. See error

**Expected behavior**
Clicking archive and it, uh, archiving

**Screenshots**
<img width="1083" alt="Screen Shot 2020-12-18 at 9 10 03 AM" src="https://user-images.githubusercontent.com/1467211/102641473-fcb5ff00-4110-11eb-9451-d4ebb64902d7.png">

**Comment by vvisigoth** [comment]
cc @tacryt-socryp can you take a look at this and fix if it's simple. don't know when ~hastuc will be back online.

**Comment by tacryt-socryp** [comment]
Sure, will take a look momentarily.

**Comment by galenwp** [comment]
Thanks!

**Comment by tacryt-socryp** [comment]
This is a reducer issue, figuring out how to resolve it and once we've verified it's fixed, will cut a new release.

**Comment by vvisigoth** [comment]
thanks
—
~poldec-tonteg
http://urbit.org

**Comment by tacryt-socryp** [comment]
I've fixed the issue. The issue was that the reducer had been partially updated to no longer handle the "archive" view, but not all the way, and the UI still expected "archivedNotifications" and an "archiveBox" to exist. By removing those lingering properties and removing the "archived" view in notifications, the UI now works as expected.
