### ISSUE TITLE
Ship won't boot after v1.1 urbit-king. Assertion 'c3y == u3r_safe_chub(lan, &lan_d)'

### ISSUE THREAD

**Issue by mguidetti** [urbit/urbit#4346]
**Describe the bug**
After briefly trying out the new v1.1 haskell urbit-king binary, I'm now unable to boot my ship with either ./urbit-king or or ./urbit.

My first run on urbit-king seemed to go fine, but I shut it down after noticing the web ui wasn't running on the port I wanted (it was on 8080 instead of 80). 

When I try to boot again with urbit-king, I now receive this error and am spit back out to the terminal prompt. 
`libnuma: Warning: Unable to determine max cpu (sched_getaffinity: Function not implemented); guessing...`

And when I try to boot with the normal urbit binary, I get this after `playback complete`
```
vere: checking version compatibility
ames: live on 59785
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (946502): live
ames: czar ten.urbit.org: ip .104.196.239.18
Assertion 'c3y == u3r_safe_chub(lan, &lan_d)' failed in vere/io/ames.c:408

bail: oops
bailing out
serf: pier unexpectedly shut down
Aborted (core dumped)
```

**System (please supply the following information, if relevant):**
 - Ubuntu 20.04.2 (Digitalocean droplet) 
 - Urbit v1.1
 - ~mirmus-dozryx

I'm not very educated on the inner-workings of Urbit yet, but I'm happy to provide any other info needed. Thanks very much!

**Comment by philipcmonk** [comment]
Are you able to run it with the old urbit-v1.0 binary?

**Comment by mguidetti** [comment]
Ah sorry I forgot to mention that I did try this afterwards with the 1.0 binary, but still received the same errors I pasted above.

**Comment by mguidetti** [comment]
Ah, I actually had tried v1.0 before and forgot to mention it. I did try it and was receiving the same error. 

However I just tried again with v1.0 and after first receiving the same error again, I tried a few more times and now it seems to be booting correctly, but then aborting with the same assertion message as before after a few minutes.  

I did receive this new message about eth-watchter once on one of my retries of its helpful? 

```
---------------- playback starting ----------------
pier: replaying events 946521-946536
spider got sign for non-existent ~.eth-watcher--0v3n2.i43me.foldl.gfni2.5l576.rbkth.54s2n.6epth.nkck4.p09bf.27uov.ivoqr.gfkod.hfmaa.oqn1b.eiu7c.ehk54.i7edp.u5n34.8ratd.dq46e
pier: (946536): play: done
---------------- playback complete ----------------
```

**Comment by philipcmonk** [comment]
Sounds like a malformed lane is getting stored somewhere, hmm.  Shouldn't be too hard to track down, I might give you some binaries with extra logging available.

In the meantime, do you have any logs in `~/.cache/urbit` ?  Could you check if there's any errors at the end of the most recent one?

**Comment by philipcmonk** [comment]
Also, just to verify: you were running on v1.0 until today, right?

**Comment by mguidetti** [comment]
Yes, until today I was running v1.0 
I couldn't resist the curiosity of a new version number and now look what I've done, lol.

I have a number of logs in ~/.cache, all prefixed with king- 

the most recent has just this line: 
`Unable to acquire lock file: "mirmus-dozryx//.vere.lock": mirmus-dozryx/`

**Comment by mguidetti** [comment]
there are a number of identical logs with just that line, the most recent that doesn't match says this 

```
Resuming ship
pier: mirmus-dozryx/
running serf in: mirmus-dozryx/
Beginning event log replay
Last event in event log is #946388
Replaying up to event #946388
Will replay 0 in total.
eyre: canceling ~[//http-server/0v3p.1f1kt/1618568180377422261/1]
("EYRE","Failed to open port.",80)
("EYRE","Failed to open port.",80)
("EYRE","Failed to open port.",80)
("EYRE","Failed to open port.",80)
("EYRE","Failed to open port.",80)
("EYRE","Failed to open port.",80)
("EYRE","Failed to open port.",80)
mirmus-dozryx/ shutdown requested
("EYRE","Failed to open port.",80)
Asking serf to shut down
Serf went down when asked.
mirmus-dozryx/ terminated.
```

**Comment by philipcmonk** [comment]
That line suggests you were trying to run it while it was already running, though it's possible the lockfile was left over from the crash.  If you run `cat mirmus-dozryx/.vere.lock` it'll give you a process ID.  Check if that process is running, and if it's not you can remove the file and then try running urbit-king again.  Try running it with `--no-ames` to see if that makes it avoid crashing at least.

**Comment by mguidetti** [comment]
the pid in .vere.lock wasnt running so I removed the file as you suggested.
booted up with `urbit-king run --no-ames mirmus-dozryx` and it seems to be working!

It's still on 8080 but I can live with that for now, hah.

**Comment by philipcmonk** [comment]
What happens if you boot it without `--no-ames`?  That flag turns off networking.

**Comment by philipcmonk** [comment]
For port 80 you probably need `sudo setcap 'cap_net_bind_service=+ep' ./urbit-king`

**Comment by mguidetti** [comment]
Ah yes I didn't think to do that for the new binary, my mistake. 
And things seem to be ok after removing the `--no-ames` I can access channels and all that in landscape like normal

**Comment by philipcmonk** [comment]
Ah, I've just reproduced this locally.  It seems to be specifically an issue when switching from `urbit-king` to `urbit`.  As long as you stay on urbit-king you should be fine going forward.  If you use `urbit` it'll crash and you'll have to delete the lockfile again.  I'll try to track down the root issue.

**Comment by mguidetti** [comment]
Okay great. I'll stay put on `urbit-king`. 

Thank you for your help. I hope this leads to some useful urbit dev, and wasn't just a waste of time fixing my clumsiness! 
Best of luck.

**Comment by philipcmonk** [comment]
Yes, there's a real bug here.  @pilfer-pandex and I have identified the issue and we're quite confident there's no long-term damage.  We'll work on a solution, but it may be a couple days until it can be released.

To summarize:

If you run a ship on `urbit-king`, then if you later run it on `urbit`, it'll crash with `'c3y == u3r_safe_chub(lan, &lan_d)'`.  The workaround is:

- Ensure you're not still running urbit in another terminal and run `rm pier/.vere.lock`.  If you're not completely sure whether it's running in an other terminal, you can `cat pier/.vere.lock` to get the process ID and then `ps -e | grep 12345` to check whether that process is running (where 12345 is the process ID).
- Start up again using King Haskell, until our next release.

**Comment by pilfer-pandex** [comment]
Thanks @mguidetti and @philipcmonk. Here's a brief account of what's going on:

There are two formats for representing addresses in ames: AmesAddress, pair of ipv4 and port which is (or should be) encoded as a 6 byte atom, and AmesDest, an (each @pgalaxy @uxaddrr) where the @uxaddr is the 6 bytes from before. The problem arose because I continued to use AD in the events sent to arvo rather than switching to AA. Since these values are handled opaquely by arvo but still stored there, this isn't a problem unless you switch to the other king. When the other king reads such a value back out, it'll get something it doesn't understand.

Action items:
- Change AmesEvHear to use an AmesAddress rather than an AmesDest
- Change the From/ToNouns of AmesAddress to code as a 6 byte atom, rather than as a cell
- Check whether NewtEfSend still uses AmesDest (I think so?)
- Add compatibility code in both kh and vere to handle the invalid values discussed above, or find some way to purge these from the state.
- Discuss the above with @belisarius222
- Add a stderr if we try to start and the lockfile exists, rather than quitting silently.
