### ISSUE TITLE
Ship won't start after successful replay and pier shutdown

### ISSUE THREAD

**Issue by sethfork** [urbit/urbit#4605]
**Description**
Ship won't start. Tried meld & pack, which didn't work. Then tried replaying events. No dice. When I replay, I get this after an hour or so

<img width="516" alt="Screen Shot 2021-03-13 at 2 54 05 PM" src="https://user-images.githubusercontent.com/7088679/111042565-f5e71180-840b-11eb-91de-726581767abd.png">

**System**
 - macOS 10.15.7

**Comment by joemfb** [comment]
The replay completed successfully, at which point a snapshot is taken, so there shouldn't be any replay needed if you restart. Does this crash reoccur if you try? And is it the same output when it crashes (`address 0x28dc2400a out of loom!`)?

What platform are you running on?

**Comment by sethfork** [comment]
Thanks for the reply @joemfb - yes, I get the same thing - `address 0x28dc2400a out of loom!`

I'm running this locally on macOS 10.15.7 - iTerm2 in a zsh shell

<img width="636" alt="Screen Shot 2021-03-13 at 7 31 00 PM" src="https://user-images.githubusercontent.com/7088679/111053547-a7993900-8432-11eb-8f01-5d9cbdce672c.png">

**Comment by joemfb** [comment]
@sethfork this is a segfault. Normally you'd be able to get some crash details from console.app, but we have a SIGSEGV handler installed for the userspace paging implemented for our memory arena (the "loom"). When we get a segfault we can't handle (the memory address is question is outside of the "loom")  we just `abort()`, so crash reports won't be helpful.

This segfault is occurring early in the startup process, at a deterministic address. I've only seen a couple other crash reports like this, and only been able to debug one pier in this state: that one had a corrupted LMDB event log. In that case, the database metadata reported more pages of data than the file contained, suggesting either truncation or an unreported failure to sync the database to disk.

We don't (yet) have any LMDB diagnostic tooling in the urbit binary. But if you happen to have homebrew installed, it's pretty easy to check:

```
brew install lmdb
mdb_stat -a -e path/to/pier/.urb/log/
```

If you're able to run that, please post the output here.

---

It's possible that this is not log corruption -- you were able to read database metadata and events during replay. If that's the case, I don't know why we're crashing and will need to help you get a more detailed crash report. (Long story short, `lldb -- ./urbit -t -L ./myBackupStuffThing`, then `proc run`, the `bt all` once it crashes.)

If this is a corrupt event log, I don't have a straightforward fix. If there was data loss, the only safe option would be to individually breach. Any lost event might have initiated new outbound network messages, and associated network packets were actually delivered, any further communication on that data flow would be impossible (ie, a loss of continuity). If only the metadata was corrupted, it may be possible to reconstruct the database.

I'm currently working on (intentional!) log truncation; once that feature is done, we could use it  to start a new log -- given a completely up-to-date snapshot.

---

LMDB is supposed to be completely crash safe by construction. Our usage patterns are very straightforward: we don't apply any effects before the event that caused them is written to the log and committed. Both write and commit failures are fatal, so our invariants should always be maintained.

The only example of such an issue on the LMDB mailing list is here: https://www.openldap.org/lists/openldap-bugs/201809/msg00010.html. Those symptoms match the crash I observed in the pier I debugged (once a disabled the segfault handler). Notably, that crash also occurs on MacOS.

My best guess as to the underlying cause of such an issue is the somewhat notorious behavior of `fsync()` on MacOS (see the notes about `F_FULLSYNC` in the manpage: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html). LMDB calls fsync on all platforms

If this is actually the issue, we should be able to patch those calls in our MacOS build. In the meantime, the only safe platform for urbit right now would be Linux. But this is all conjecture on my part. We've used LMDB for a couple years now, and lots of people run urbit on MacOS. These recent reports are the only such issues I'm aware of.

I'm sorry for the trouble! We'll get to the bottom of this as soon as we can.

**Comment by sethfork** [comment]
Thanks @joemfb - here's the output from `mdb_stat -a -e path/to/pier/.urb/log/`


<img width="437" alt="Screen Shot 2021-03-15 at 2 35 20 PM" src="https://user-images.githubusercontent.com/7088679/111203680-ae8f8b00-859b-11eb-94de-f0727ab7f440.png">

**Comment by joemfb** [comment]
@sethfork thanks! One more thing: could you `ls -l ./myBackupStuffThing/.urb/log/` and post that as well. The file size of `data.mdb` should be `Page-size * number-of-pages-used` (`230838272` in this case). If it's smaller than that, we do the database has been corrupted.

**Comment by sethfork** [comment]
@joemfb Looks like it's smaller
<img width="462" alt="Screen Shot 2021-03-16 at 8 47 23 PM" src="https://user-images.githubusercontent.com/7088679/111397944-d1539980-8698-11eb-815e-6ae7bfdd0953.png">

**Comment by vvisigoth** [comment]
Hey @sethfork can you drop us an email at support@urbit.org ? I have some more details on remediation options.

**Comment by sethfork** [comment]
@vvisigoth Sent an email, thanks!

**Comment by joemfb** [comment]
The issue reported here was fixed in #4615
