### ISSUE TITLE
urbit.org displays incorrect path

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#511]
I typed in an incorrect url http://urbit.org/docs/quickstart (it should have been /start). I was correctly redirected to http://urbit.org/docs, even though the url tab still displayed /quickstart.

Then, when I clicked on the 'user doc' link, I was redirected to http://urbit.org/docs/docs/user and displayed the same page (what should have been urbit.org/docs).

Attached is a screenshot providing evidence.

![screen shot 2015-11-03 at 1 37 05 pm 2](https://cloud.githubusercontent.com/assets/6663732/10922596/d9977cf0-8230-11e5-8b67-4b6687f36d32.png)

**Comment by ault011** [comment]
edit: the correct initial url I should have typed in was http://urbit.org/docs/user/start

**Comment by ohAitch** [comment]
@cgyarvin something something ford interface changes?

**Comment by daveloyall** [comment]
Yeah, I encountered this today.

**Comment by galenwp** [comment]
@cgyarvin @ohAitch let's turn the discussion on this topic into a more focussed bug?

**Comment by ohAitch** [comment]
The primary issue is that if you ask ford for `%html /=home=/pub/valid/file/junk/suffix`, where `/=home=/pub/valid/file/md` is what's in clay, it will give you a page with broken relative links: `./sibling` will be preserved as the href, now pointing at `valid/file/junk/sibling` instead of `valid/file`. This functionality is supported by ford to faciliate FCGI: eyre requests approximately `%html /=home=/pub/valid/file/~088vvv0data0vvv88/web`, where `~088vvv0data0vvv88` is a url-syntax literal of the requesting ship, query string, etc. This can then be inspected any `valid/file/*/hook`, or in the case of the literal `valid/file/md`, summarily ignored.

@cgyarvin mentioned the possibility of (re?)moving this functionality as part of larger changes to the ford request interface. Presumably, the result would be `/=home=/pub/valid/file/junk/suffix` failing in ford, and being converted to a 404 by eyre.

**Comment by galenwp** [comment]
This appears to properly 404 now.
