### ISSUE TITLE
`+azimuth-block` out of date after changing system time

### ISSUE THREAD

**Issue by xovlov** [urbit/urbit#5247]
My `+azimuth-block` was quite out of date (it was `11.901.423`), and presumably causing networking problems. It has been suggested this happened because I changed the clock time on the machine my planet was running on. 

To try and fix it, I ran:
```
|fade %eth-watcher
|fade %azimuth-tracker
|start %eth-watcher
|start %azimuth-tracker
:azimuth-tracker %listen
:azimuth-tracker %watch
```

Unfortunately, now `+azimuth-block` bails:

```
>+azimuth-block
 
bail: 4
! 
  / gx
    ~tocrex-holpen
    eth-watcher
    ~2021.9.23..15.06.38..b957
    block
    azimuth-tracker
    noun
[%dojo-lame %arvo-response]
```
Additionally, I can no longer `|fade %azimuth-tracker`:

```
>|fade %azimuth-tracker
 
crud: %belt event failed
[%poke %belt]
wire=/azimuth-tracker
  bar-stack
~[
  ~[/dill //term/1]
  ~[
    /gall/use/hood/0w2.~o6~V/~tocrex-holpen/drum/fade/azimuth-tracker
    /dill
    //term/1
  ]
  ~[
    /gall/use/dojo/0w2.~o6~V/out/~tocrex-holpen/hood/drum_~tocrex-holpen/poke
    /dill
    //term/1
  ]
  ~[/dill //term/1]
  ~[
    / gall
      use
      dojo
      0w2.~o6~V
      ~tocrex-holpen
      drum_~tocrex-holpen
      hand
      gen
      hood
      fade
    /dill
    //term/1
  ]
  ~[
    / gall
      use
      hood
      0w2.~o6~V
      out
      ~tocrex-holpen
      dojo
      drum
      phat
      ~tocrex-holpen
      dojo
    /dill
    //term/1
  ]
  ~[/dill //term/1]
  ~[//term/1]
]
take: failed
/sys/vane/jael/hoon:<[1.250 3].[1.255 13]>
/sys/vane/jael/hoon:<[1.251 3].[1.255 13]>
/sys/vane/jael/hoon:<[1.254 3].[1.255 13]>
/sys/vane/jael/hoon:<[1.254 17].[1.254 60]>
/sys/vane/jael/hoon:<[1.254 22].[1.254 60]>
/sys/vane/jael/hoon:<[528 5].[587 7]>
/sys/vane/jael/hoon:<[529 5].[587 7]>
/sys/vane/jael/hoon:<[566 7].[586 9]>
/sys/vane/jael/hoon:<[567 22].[567 60]>
[%jael-unexpected-quit /azimuth-tracker %gall %unto p=[%kick ~]]
/sys/vane/jael/hoon:<[567 57].[567 59]>
```

**Comment by Fang-** [comment]
When you `|start`ed these apps back up, did they start successfully or produce errors?

Alternatively, can you check the result of this command: `.^(? %gu /=azimuth-tracker=)`  
A `%.y` result means it is running.

> `%jael-unexpected-quit`

Jael doesn't like having its subscription kicked by azimuth-tracker, because it depends on it. Fading the app makes it close its incoming subscriptions, triggering the jael crash.  
The fact that you didn't get this when you tried fading for the first time suggests the subscription had gotten dropped somehow.

For future reference: `|fade` is pretty aggressive as far as debugging an app goes. `:azimuth-tracker|kick`, among perhaps other things, should've been attempted first. Certainly also worth trying in the current state!

**Comment by xovlov** [comment]
Both of the apps are running. 

That said, `:azimuth-tracker|kick` seems to have gotten things working. My azimuth-block is now output as `13.288.752`. Thanks!
