### ISSUE TITLE
http://randominvalidplanetname.urbit.org/ should 404

### ISSUE THREAD

**Issue by daveloyall** [urbit/urbit#528]
http://randominvalidplanetname.urbit.org/

That url, as of right now, returns something like this:

```
%exit

\//~lodted-sivnyr-micwyx-bissud--patsud-habrun-mictud-hilleg/home/~2015.10.30.\/
  .23.07.28..e199/arvo/eyre/:<[1.104 9].[1.106 38]>
\/                                                                            \/

[%bad-beam %index]

\//~lodted-sivnyr-micwyx-bissud--patsud-habrun-mictud-hilleg/home/~2015.10.30.\/
  .23.07.28..e199/arvo/eyre/:<[1.103 9].[1.106 38]>
\/                                                                            \/
```

Probably it should not resolve, or should show a friendly error page.  Either of those options would help users know when they simply made a typo vs they hit the correct resource but there was an error.

Cheers,
--libwyl-fannec

**Comment by galenwp** [comment]
+1 'friendly error page'

That's actually basically a 404 on `~doznec` which is trying to proxy for you.

**Comment by ohAitch** [comment]
Well, it's a 404 because doznec tried to serve `/` which was not at the time a valid url; the actual task here is how to distinguish between "my.hostname.com", where the subdomain doesn't matter, and "err.urbit.org", where doznec should throw an error instead of assuming the request was meant for itself.

I suppose just hardcoding `[%| [%org %urbit *]]` works fine, since it's already present as the `.^(hart %e /(scot %p her)/host=)` default.

**Comment by Fang-** [comment]
Moved to urbit/arvo#555.
