### ISSUE TITLE
Issue Installing OTA

### ISSUE THREAD

**Issue by LingonberryLabs** [urbit/urbit#5584]
Hi Urbit Friends!

I am having some issues installing the most recent OTA. This is the message I am getting when I try to install the OTA

```
kiln: %base resuming updates
kiln: resetting tracking for %base from [~zod %kids]
kiln: activated install into %base from [~zod %kids]
kiln: downloading update for %base from [~zod %kids]
kiln: finished downloading update for %base from [~zod %kids]
error in %hood
%arvo-response
! /cu/~[my-ship]/group-view/~2022.2.5..18.52.45..ac8d/sys/kelvin
```

Anyone know what is going on?

**Comment by belisarius222** [comment]
Huh, this looks strange.  A `%cu` scry is failling, probably in Kiln, and probably because a desk is missing a `/sys/kelvin` file.  What I don't get is why there would be a `%group-view` desk.  

@LingonberryLabs if you created a desk called `%group-view` and ran `|install` on it or tried to install it through the web UI, and it was missing the `/sys/kelvin` file, then I think that could cause this.

You could try running `|uninstall %group-view` and then try to rerun the kernel update by running `|install ~my-sponsor %kids, =local %base`.

**Comment by LingonberryLabs** [comment]
Honestly, it could be because of this issue I had with Landscape a while back. 

https://github.com/urbit/landscape/issues/1311

I just tried and it looks like it is working!!!!! Thank you so much! :)
