### ISSUE TITLE
L2 ship +code is wrong for some time after booting

### ISSUE THREAD

**Issue by mrdomino** [urbit/urbit#5592]
**Describe the bug**
A freshly booted L2 planet will show the wrong +code after it is booted. The +code will work at first, but after some time, it will stop working, and +code will report something different. Guessing that this is due to +code being synced to L2 state and not noticing that the state is out of date, so it misses the planet spawn transaction.

**To Reproduce**
Steps to reproduce the behaviour:
1. spawn a planet on L2
2. set up a docker instance for it
3. run `docker container exec sampel-palnet /bin/get-urbit-code` against the running container after it finishes booting
4. try logging in after some time, and the code doesn't work
5. run `get-urbit-code` again, seeing a different code

(This is what happened in my case; I have not tested to see what happens with the console `+code` but imagine it would do the same thing.)

**Expected behaviour**
`/bin/get-urbit-code` should wait until the L2 state is synced.

**Comment by Fang-** [comment]
> Guessing that this is due to +code being synced to L2 state

Close. The code is based off the current networking keys. L2 ships start with both "current" and "next" keys injected into jael, so that they may automatically move on to the next keys once the relevant L2 transaction gets confirmed. We do this because the L2 transaction that updates the keys may be waiting for a rollup to happen, which may take up to a day depending on roller behavior.

iow, this is behaving as intended, though I do realize it's not ideal. I suppose we could consider generating the `+code` off the highest known networking keypair? Not sure what the other options are here...
