### ISSUE TITLE
Assertion '0' failed in noun/events.c:420

### ISSUE THREAD

**Issue by tacryt-socryp** [urbit/urbit#5615]
~
urbit 1.8
boot: home is /home/urb/livenet/tacryt-socryp
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: GB/1.316.896.768
boot: installed 348 jets
---------------- playback starting ----------------
pier: replaying events 26171040-26171160
pier: (26171160): play: done
---------------- playback complete ----------------
vere: checking version compatibility
Assertion '0' failed in noun/events.c:420
home: bailing out
pier: serf unexpectedly shut down

@joemfb

**Comment by joemfb** [comment]
That's a snapshot patch write failure: 

https://github.com/urbit/urbit/blob/c4bc9b342831c78dba8c7c2af389dce4e311f84c/pkg/urbit/noun/events.c#L407-L422

We need better error printfs there. It's possible that it was a partial/interrupted write (or otherwise ephemeral error), in which case we could also retry the write. For now, I'd check to make sure you have sufficient disk space.

**Comment by tacryt-socryp** [comment]
It looks like I didn't have enough disk space. Fixed that, and now everything is good. Thanks!
