### ISSUE TITLE
cd needs to be fixed

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#565]
Firstly, the docs on cd are incorrect because it's changed several times in the past week.  As a matter of course, I think I should stop accepting pull requests like that until they have the appropriate doc changes in them.

I believe cd only really work at the desk level, anyway.  In particular, this is now the canonical way to change to another desk:

```
=% /=other-desk
```

and changing to, say, `/=home=/try` locks to the current time (as does `%/try`).  `/=home/0/try` works of course, but that's stupid.

**Comment by juped** [comment]
/=path= needs to be /~sampel-sipnym/path/0 unless you already changed away from 0, given the ostensible meaning of = as "complete from the current path". The half-baked change should be made fully baked.

**Comment by cgyarvin** [comment]
Unfortunately this doesn't really work, since 0 is intercepted at the dojo layer when we process the %=.  All other uses of path expressions would have no idea what 0 meant.

I think 0 is the wrong sentinel; I want to revert the change.  But its defenders have arguments too...

**Comment by galenwp** [comment]
Can the defenders chime in?  This seems like something we want to resolve quickly.

**Comment by juped** [comment]
Why is this done at the dojo layer? It can't be done at the actual nock 11 level because of the referential transparency of the arvo namespace, presumably, but shouldn't it still be provided by something lower-level than apps themselves?

**Comment by cgyarvin** [comment]
Because this is actually a dojo feature.

Every time we parse Hoon, we tell the parser to bind a path to %.  This
path is the location of the source file for code in a file.  For an
expression in the dojo, the path is the dojo "current directory."  It's
also the =dir variable in the dojo.

Like everything, this path needs a ship, desk and case.  By default, the
ship is our, the desk is %home, and the case is now.  In the dojo, this
path also drives where generators are loaded from, etc.

By far the most common change to % is changing the desk.  Less often, we
set a spur (the rest of the path), or change the desk and case.  What's
tricky is that we need a way internally to store the state that says "as
the time changes, use the current time for the case."  This sentinel value
used to be now and is now 0, leading to the confusion.

The advantage is that 0 is not a valid case.  The disadvantage is that 0 is
not a valid case.  When now is the sentinel value, there is no way to lock
the =dir time to the present time.  But you can set it to (scot %da (dec
now)) or similar.

In the present codebase, you write =dir /=sandbox to change the desk to the
sandbox.  The dojo detects that you're writing a special variable and that
[our %sandbox ~] is not enough information, and adds the 0.  This is
perhaps excessively magical.

I concur in preferring the old behavior.  But I have to have this argument
with Anton, who is sick.

**Comment by ohAitch** [comment]
Yep that is definitely broken, the problem was that in switching to `=%` I made it use the "general hoon expression" parser and not the "valid new path" one, the former of which uses a `%` with "activated" sentinel. The correct thing is probably to go back to the latter parser for `=%` (but not generic `=dir`, if that can be documented satisfactorily.)

Though I would like to partially dispute lack of appropriate doc changes: e6e6548, the commit in question, contains a dojo.mdy change, if perhaps one that could be elaborated further. Or is there other doc I should be aware of?

**Comment by juped** [comment]
I believe Curtis was just confused that the bug might have been intentional - I had to defend your honor on talk while you were absent...

**Comment by ohAitch** [comment]
Completely unintentional, I'm with him entirely on `=% %/foo` doing the obvious thing.
