### ISSUE TITLE
gall: dozing agents drop instead of enqueue some events

### ISSUE THREAD

**Issue by Fang-** [urbit/urbit#5807]
> `gall: %some-agent dozing, dropping %wake`

Compare this to the behavior for agents that haven't been started at all yet:

> `gall: not running %some-agent yet, got %leave`

In the latter case, the agent will eventually receive the event, and can process it accordingly. In the former case, events get dropped and the agent is not informed, potentially killing any flows that rely on events in those flows to stay alive.  
This seems clearly wrong to me.

As per @philipcmonk:
> probably expediency of implementation. That hasn't been revisited since it was first implemented

Upon closer inspection of the current gall, we don't seem to drop _all_ events, and do enqueue some... That's even stranger!

**Comment by zalberico** [comment]
It sounds like the action for this one is that gall should enqueue rather than drop (all?) events from dozing agents?

**Comment by philipcmonk** [comment]
We enqueue %agent moves and drop %arvo moves.  This isn't obviously correct, but no other solutions are either.  We can't commit to giving you everything you missed, because that's a commitment to an unbounded queue.  OTOH, dropping everything is immediately awkward.  I suspect there's a very deep tradeoff here, and my instinctual reaction is to back away slowly.

**Comment by zalberico** [comment]
> Upon closer inspection of the current gall, we don't seem to drop all events, and do enqueue some... That's even stranger!

This makes sense in that context then - looks like we are trying to balance that tradeoff. Sounds like we should probably close this unless we have some reason to think the current state of the tradeoff we're making is wrong.
