### ISSUE TITLE
"prep" command requires a tty (for no good reason) and does not accept "--no-tty"

### ISSUE THREAD

**Issue by midlyx-hatrys** [urbit/urbit#5924]
**Describe the bug**
So it looks like Vere 1.10 has stricter error checking.  This is a good thing, but it broke my point systemd services because those services start with "{last-used-vere} prep {pier}", and "prep" now bails out because there's no tty (actually it complained about no tty in 1.9 too, but it used to ignore this and now does not).

So there are two bugs exposed by the improved error checking:
- "prep" wants to be interactive by default (why?)
- there is no way to change that default

Wrapping the "prep" part in screen works around this, so nothing urgent.

**Notify maintainers**
@joemfb

**Comment by joemfb** [comment]
Thanks, this was my mistake. The obvious problem (no reason for these kinds of commands to ever require interactivity) is fixed in #5928.

The fact that `--no--tty` didn't work is irritating, and is because each sub-command intentionally has it's own set of arguments. A lot of the arguments only make sense in specific contexts, but some could reasonably be shared. Not sure how to handle that tension besides being more careful and considerate.

It's also worth noting that the `prep` implementation (also part of `next`) is pretty hacky -- it just runs the pier normally, short-circuiting after any replay/snapshot update. If our event-loop and ipc modules were better factored, it would be practical for it to explicitly use only what it needs (and #5596 gets us a lot closer). As is, it's very easy for it to inherit all kinds of irrelevant functionality since it (briefly) goes thru the main pier loop.

**Comment by midlyx-hatrys** [comment]
Thank you!  Yeah, calling the fact that `--no-tty` doesn't work with `prep` a bug was an exaggeration on my part.
