### ISSUE TITLE
? +<:(ream 'a=1') prints the world like ??

### ISSUE THREAD

**Issue by dhaffey** [urbit/urbit#596]
My understanding is that ? in dojo is the "safer" version of ?? that uses a custom type printer to avoid spraying kernel guts everywhere. If so, `+<:(ream 'a=1')` thwarts it. Note that the actual noun in question is just `%a`, not some massive core.

**Comment by chc4** [comment]
Seeing how `+<:(ream 'a=1')` gets the `i=%a` face automagically, it's probably somehow being hinted as a `++list`. Since it's a core, it includes the entire kernel.

I'm really not sure _how_ it's being hinted as that, though. `++ream` returns a `++twig`, and the %ktts case is `[%ktts p=toga q=twig]` - toga is pretty complex, but doing `? *toga` prints out perfectly fine.

**Comment by chc4** [comment]
Ok, I'm now convinced that something terrible is happening.

The return type of `++ream` is a `++tile`. Getting the tail of that should just be same type as the tail of all the fork case - this is actually what happens if you do something like `? +:*$&([%a @ud] [%b @tas])`, which gives the correct type of `@ud @tas`. Somehow, the compile is just throwing up and giving the type of +:a to either a raw atom (which crashes when it tries to print, due to the cores in some cases of ++twig) or something else entirely. I honestly can't figure out how in the world `+<:a` would *ever* get the `i=%a` face, for example, since it's only used in a couple places in the stdlib: `++list` and two cases of `++type`, neither of which should be possible.
```
=a (ream 'a=1')
? ?+(a ~ [%ktts *] +<:a) -> p=p=%a, what *should* be printed
+<:a -> i=%a, no clue how it gets this. At best it should just be a raw atom, like +:a is printed as.
```

The only way I can imagine it getting the `i=%a` face is it somehow being transmuted to the type from %smdq, (list beer), which obviously shouldn't happen.

**Comment by ohAitch** [comment]
Of relevance: the way the printer handles forks is trying to print values as the various types until one sticks. What I expect is happening here is its going through the rune-tails until it hits e.g. `+<:[%cnzy wing]`, which is an `i=term`, succeeds at rendering %a as that, and calls it good.
In conclusion, try to have things you're printing not be a fork of 100 options you've lost the ability to discriminate between :P

**Comment by juped** [comment]
This works now - prints the span of twig which is long but reasonable and doesn't crash
