### ISSUE TITLE
gall: unsubscribing from alien ship causes crash

### ISSUE THREAD

**Issue by tinnus-napbus** [urbit/urbit#6032]
**Describe the bug**

You can subscribe to an alien ship just fine. However, if you then try to unsubscribe it will crash.

**To Reproduce**

Here is an agent that does nothing but subscribe and unsubscribe:

```hoon
/+  default-agent, dbug
%-  agent:dbug
=+  ~
|_  =bowl:gall
+*  this  .
    def  ~(. (default-agent this %.n) bowl)
++  on-init  on-init:def
++  on-load  on-load:def
++  on-save  on-save:def
++  on-poke
  |=  [=mark =vase]
  ^-  (quip card:agent:gall _this)
  =+  !<([=ship sub=?] vase)
  :: if not .sub, unsubscribe from .ship
  ?.  sub
    :_  this
    [%pass /wire %agent [ship %foobar] %leave ~]~
  :: if .sub, subscribe to .ship
  :_  this
  [%pass /wire %agent [ship %foobar] %watch /foo/bar]~
++  on-watch  on-watch:def
++  on-agent  on-agent:def
++  on-leave  on-leave:def
++  on-arvo  on-arvo:def
++  on-fail  on-fail:def
++  on-peek  on-peek:def
--
```

I subscribe to an alien ship:

```
> :xxx [~sampel &]
```

it appears in wex as unacked:

```
[p=[wire=/wire ship=~sampel term=%foobar] q=[acked=%.n path=/foo/bar]]
```

I then try unsubscribing:

```
> :xxx [~sampel |]
crud: %belt event failed
[%poke %belt]
  bar-stack
~[
  ~[
    /gall/sys/way/~sampel/foobar
    /gall/use/xxx/0w1.5tK8e/out/~sampel/foobar/7/wire
    /dill
    //term/1
  ]
  ~[/gall/use/xxx/0w1.5tK8e/out/~sampel/foobar/7/wire /dill //term/1]
  ~[
    /gall/use/dojo/0w3.KSbZF/out/~tinnus-napbus/xxx/drum_~tinnus-napbus/poke
    /dill
    //term/1
  ]
  ~[
    / gall
      use
      hood
      0w3.KSbZF
      out
      ~tinnus-napbus
      dojo
      drum
      phat
      ~tinnus-napbus
      dojo
    /dill
    //term/1
  ]
  ~[/dill //term/1]
  ~[//term/1]
]
call: failed
/sys/vane/ames/hoon:<[1.082 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.084 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.085 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.087 3].[1.113 20]>
/sys/vane/ames/hoon:<[1.088 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.091 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.097 5].[1.111 7]>
/sys/vane/ames/hoon:<[1.110 14].[1.110 44]>
/sys/vane/ames/hoon:<[1.779 5].[1.795 71]>
/sys/vane/ames/hoon:<[1.780 5].[1.795 71]>
/sys/vane/ames/hoon:<[1.782 5].[1.795 71]>
```

It is also impossible to nuke this agent

Note this can't be reproduced on a fake ship, only live

**Expected behaviour**

Should be possible to unsubscribe from aliens

**Notify maintainers**

@Fang- @philipcmonk

**Comment by philipcmonk** [comment]
@belisarius222 This is crashing in +on-cork, because we assert that we can only cork to %known ships.  This is a regression, and kind of important, because we need to be able to nuke any app.

Can we solve this by just not corking if they're %alien?

**Comment by belisarius222** [comment]
If we didn't cork, the flow wouldn't get closed, leaving a space leak. Instead of crashing, I think Ames should allow a cork to be enqueued and sent later once the other ship is %known.

Another alternative would be to filter the alien queue and delete other enqueued messages on the same duct as the cork. This would avoid unneeded network traffic. It seems a little
more invasive to me, but I'm not opposed to it, especially if it turns out to be simpler than enqueueing an alien todo.

—
~rovnys-ricfer
https://tlon.io

**Comment by ryjm** [comment]
just ran into this in %groups - when searching for groups we subscribe to an index of that ship's groups, which lead to a nasty bug preventing @jamesacklin from being able to uninstall the %groups agent. it also prevents you from nuking an agent since drum will attempt to unsubscribe from the agent's subscriptions.

![image](https://user-images.githubusercontent.com/2065299/200424093-9e74f8b0-8c3c-4468-a603-ab7a3ee04951.png)
