### ISSUE TITLE
curl: failed https://bootstrap.urbit.org/urbit-v1.10.pill: Couldn't resolve host name

### ISSUE THREAD

**Issue by skilo83** [urbit/urbit#6034]
Get this error when trying to boot my new planet: curl: failed https://bootstrap.urbit.org/urbit-v1.10.pill: Couldn't resolve host name

I pulled the pill file down manually with the curl installed on my Linux system and forced urbit to boot it with the -B flag. Then i get another curl error:  curl: cant resolve roller.urbit.org/v1/azimuth.

Since the version of curl that comes installed on Linux Mint worked and whatever method the urbit binary uses doesn't, this leads me to believe the problem is in the way the urbit binary is trying to resolve the hostname.

I recommend implementing a fallback method that calls the system install version of curl, or perhaps even wget for extra fallback protection.

My system:
Linux Mint 21 x64

**Comment by joemfb** [comment]
We distribute static binaries for linux, and use libcurl (statically linked into the binary) for these http requests. Using the system curl would not be straightforward, but I'll make a note to investigate libcurls dns resolution behavior when it's built as a static library.

**Comment by skilo83** [comment]
If it's C, just do something like this:

// call the system version
system("curl https://bootstrap.urbit.org/urbit-v1.10.pill");
FILE *fp;
// check if it actually downloaded the file
fp = fopen("urbit-v1.10.pill", "r");
// Fallback to system wget
if (fp == NULL) {
    system("wget https://bootstrap.urbit.org/urbit-v1.10.pill);
}
// if all things failed handle the error.
if (fp == NULL) {
    return -1;
}

**Comment by lycurgus** [comment]
Not sure if it's helpful but I just ran into something that seems similar - I couldn't resolve `bootstrap.urbit.org`, downloaded the pill directly and then got stuck on `comet-stars.jam`.

It turned out the issue was my `/etc/resolv.conf` was empty; I'm using `systemd-resolved` and by default it apparently doesn't update the file? (it just exposes some kind of hook for programs to query things; so firefox worked fine but `nslookup` was unhappy). I got urbit up and running after symlinking `/run/systemd/resolve/resolv.conf -> /etc/resolv.conf` and rebooting.

Hopefully that helps others in future, or helps pin down what libcurl might be doing differently to the rest of the system in this sort of setup :)
