### ISSUE TITLE
just call ape app

### ISSUE THREAD

**Issue by ault011** [urbit/urbit#604]
app is three letters so it fits the pattern. ape has the potential to be confusing and its counterparts cat and dog are gone. There's no need to be cute here.

**Comment by ohAitch** [comment]
+1

**Comment by juped** [comment]
Merging cat/dog, was, of course, a mistake. This needs to be on the public record. Otherwise, +1.

**Comment by ohAitch** [comment]
I think the tradeoff there of "you now only have to look in one place to
find out what |foo does" was worth it, but perhaps something like
cat/hood/foo/hoon -> gen/hood/foo/cat/hoon would have been better than the
current :- solution. In general, this seems to be an argument towards a
tag-based and not hierarchical file system structure :P

**Comment by juped** [comment]
I mean, we do have hymn.hook as precedent. And as anti-precedent, mar, lib, and sur. I just think it's weird to specify it as boilerplate. I did kinda like separate dojo sigils for them.

**Comment by chc4** [comment]
Sadly, urbit is a bit too invested into 90s filesystem layout to switch over to a tag based system :(
I was a fan of the separate dog/cats too, BTW. It makes sense from a security standpoint where compatabilies are known when you run the command instead of having to check the first cons in a source file. Definitely in favor of renaming apes, regardless.

The fact that webhooks have no only a magic file extension, but also a magic file *name* is pretty terrible. Like, really terrible.

**Comment by juped** [comment]
hymn is, of course, a mark. Whether it's a good one is another story.

**Comment by ohAitch** [comment]
Fixed in 2d565e75d0
