### ISSUE TITLE
Some interesting autosyncs

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#615]
Via @dhaffey: https://gist.github.com/dhaffey/065f479ef6fbe9e6c1e9

Probably interesting to @philipcmonk.

**Comment by juped** [comment]
This is just a normal conflict, but it happened a bunch of times because for some reason one of the larger syncs ended up as several revisions in clay, and also because @dhaffey had conflicts in both examples and home. You can either resolve the conflict in the scratch desk as instructed, or, if you don't care that much about keeping your changes, add `, =gem %that` to the end of your merge command to just use the "take theirs" merge strategy.

The stack trace in ford at the end could be more interesting, but it's probably just having a weird intermediate partially-synced state.

**Comment by dhaffey** [comment]
I almost ran with `, =gem %that` afterwards, but wanted to hold off until I was sure I wasn't blowing away some interesting state for debugging.

For the %base merge I didn't actually have the option of resolving in the scratch desk, presumably because the %swim-call-vane crash nerfed the event that was setting it up? I saw `done setting up scratch space in %home-scratch`, but `+ls /=home-scratch=` didn't turn anything up afterward.

**Comment by dhaffey** [comment]
Well...

    merged with strategy %that
    [%tang /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/zuse ~toctyr-bilbyt]
    [%vega-start /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/hoon]
    %vega-parsed
    [%vega-compiled %163 163]
    %hoon-load
    [%tang /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/zuse ~toctyr-bilbyt]
    [%vane %a /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/ames ~wismyl-fabfyr]
    %ames-reload
    [%vane %b /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/behn ~nattug-sathex]
    [%vane %c /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/clay ~misrev-parsef]
    [%vane %d /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/dill ~wicmun-pasheb]
    [%vane %e /~ladhut-docfyn/home/~2015.12.2..20.13.04..86cf/arvo/eyre ~latnec-nompeg]
    exit
    load-lost
    type-fail

Was that update a load-lost for others too, or is ~ladhut-docfyn damaged goods at this point?

**Comment by juped** [comment]
We're in the middle of a classic @ohAitch bug at the moment, give us a bit and then reset...

**Comment by ohAitch** [comment]
Eh, classic me bugs aren't usually documentation bugs.

(Lack of "this pull request contains a zuse card type change, reload things in order because the autoreload system is broken" is a documentation bug)

**Comment by cgyarvin** [comment]
Is this resolved?  Can ~ladhut-docfyn |reset now?

Is there an issue that describes exactly what's wrong with the autoreload
system?

**Comment by juped** [comment]
~ladhut-docfyn can reset. It will probably work fine.

**Comment by juped** [comment]
Presuming resolved. :)
