### ISSUE TITLE
ci: Need to download runtime

### ISSUE THREAD

**Issue by philipcmonk** [urbit/urbit#6208]
The runtime has moved into [a new repo](https://github.com/urbit/vere), but I believe that CI here continues to build the binary out of this repository.  This stops working as soon as we have a kelvin update where the binary changes aren't reflected here (yesterday, on next/arvo).

Two solutions that come to mind are including a version identifier in this repo (eg a commit hash, vere version number, or kelvin) or just unconditionally downloading edge.  The latter seems easier and will work for most things.

**Comment by zalberico** [comment]
I like the idea of pulling edge because when we're shipping releases that require vere changes it means we always have the up to date commits, but the risk is for releases where we don't require vere changes.

In the case where we're shipping arvo work that doesn't touch vere, then pulling edge could make things more difficult. That said, the expectation is that develop should remain operable at all times so committing to this is probably a good thing. I think we should probably just do this and if we recognize that vere edge is broken quickly that'll be good (and we can then fix it early).

**Comment by zalberico** [comment]
@belisarius222 tagging you on this - it'd be good to handle this from the foundation side.

**Comment by belisarius222** [comment]
CC'ing @jalehman

**Comment by philipcmonk** [comment]
The main downside of pulling exclusively edge is that if you're doing a kelvin release, your ci won't work until the binary changes hit edge.

I think the right answer is to refer to a specific version of urbit/vere.  It should only need to change every kelvin version anyway, and it gives you the most flexiblity.  That would be something like:
- Here, include a vere-version that includes something like `/edge/v1.17-ed12e552cb`
- Here, download that binary instead of building from this repo
- In urbit/vere, add a manual Github Actions workflow so that you can deploy a specific dev commit

**Comment by zalberico** [comment]
Thanks - that makes sense to me.

**Comment by philipcmonk** [comment]
Fixed by #6210
