### ISSUE TITLE
we don't detect duplicate arms in a core

### ISSUE THREAD

**Issue by cgyarvin** [urbit/urbit#622]
|%  ++  a  42  ++  a  43  -- 

compiles and shouldn't.

**Comment by chc4** [comment]
I tried hacking up a fix for this, but there are two snags:
* zuse.hoon has a few duplicate arms (`++cone`,`++chum`,`++coal`,`++code`), so making it a compile error also needs to remove it - but it appears that has to be a seperate vega reset event *before* the hoon.hoon change, or else when it tries to load in the new kernel it fails when compiling old zuse panics.
(It looks like %dill also has a duplicate arm, `++sign-gall`...is dill entirely dead code now, with dojo?)
* It's pretty darn hard to get a proper stack trace for duplicate arms. Getting all the arms is done in `++wisp` through `(most muck boog)`, but I wasn't able to add a cache check to the parser since even wrapping `boog` in a `cook` to *check* against a set doesn't let you *update* the set, due to parser combinators being pure. Most I could do is check for duplicates in the `cook` over the returned list for `most`...which is just a plain panic with "[%taken-name p=%cone]" and what file it is, not what line or column. 3647d80c62984a7381ce8a77f08303b922faa463

I'm not sure what a proper fix would entitle - is there an idiom already existing for threading state in parser combinators? Or would it require writing up a replacement of `++most` in `++wisp` that checks the result of each parse, which is above me.

**Comment by juped** [comment]
We have duplicate arms? How embarassing. The lesson is that this is a pretty important compiler bug.

**Comment by juped** [comment]
Now a parse error
