### ISSUE TITLE
%kids desks are out of sync with %base desks on most ships

### ISSUE THREAD

**Issue by pkova** [urbit/urbit#6244]
This can most clearly been seen from the network explorer: https://network.urbit.org/?chart=kidsHash

Another way to verify is to run something like `-read [%z ~dinleb-rambep %kids da+now /]` from the dojo. Note that affected ships have the most up to date `%base` desk but are one commit behind on the `%kids` desk.

@philipcmonk is looking into this.

**Comment by philipcmonk** [comment]
I've verified that:
- pushing another update to their parent works correctly: their %base gets it, and their %kids gets fully up-to-date
- changing spider or zuse is not sufficient to trigger the bug

I still don't know what could cause this, other than a crash on merging to %kids, and I don't know why that would be so widespread.

**Comment by pkova** [comment]
Could it have something to do with [this PR](https://github.com/urbit/urbit/pull/6093)? If the frontend was doing `%kiln-sync` instead of `%kiln-install` earlier it seems like that would skip the special case here: https://github.com/urbit/urbit/blob/0750c3f8ce1af96134ded7a80ae266b9af0001a1/pkg/arvo/lib/hood/kiln.hoon#L711-L712

**Comment by philipcmonk** [comment]
That would have caused this problem, but that wasn't ever deployed, and also we see this on ships that never used the frontend, and where `|syncs` shows correctly `from %kids on ~ship to %base then %kids`

I'm testing a theory now that it has to do with blocked kelvin updates.  The logic is supposed to be "merge their %kids to %base, then merge their %kids to %kids`, but if the first merge blocks on a kelvin update, then we don't have any obvious way to trigger the merge %kids.

**Comment by philipcmonk** [comment]
I've confirmed this is the issue.  Not sure how to fix it yet.  An important constraint (I think) is that we don't want the merge to %kids to happen until %base is actually updated.  If so, we don't really have a mechanism for that kind of notification.  Some options:

- Record that a pending update is from a merge and send the `%mere` (merge ack) after the pending update goes through.  I don't like this because it's quite finicky.  Eg what happens if you merge commit becomes pending, but is then overwritten by another commit, and later that's applied?
- Listen to %base, and when it changes, run the %kids->%kids merge.  You'll get some false positives when you make local changes to %base, and it's profoundly weird.
- Recognize specifically when a kelvin update happens, and execute all %kids merges at that time.  This will need to be updated when userspace permissions drops, because that introduces another way that a commit can be held back.
- When we recognize that "remote is identical, skipping", we could check if our %kids is also identical, and if not, kick off the %kids merge.  This relies on the current behavior that when spider reloads, all our syncs restart, which is a little bit incidental, but we can replicate this behavior if it ever changes.  If this works, I think it's the cleanest.
