### ISSUE TITLE
Connectivity issues on Landscape

### ISSUE THREAD

**Issue by Ayel91** [urbit/urbit#6440]
Hi, I opened an issue the other day on Bridge but I haven't gotten a response on how to address it. I am new to Urbit and I don't know if this is the right place to ask. I'll post the link to the original issue in hopes to get a response.

The gist of it is that I haven't used Landscape in a while to connect to my ship until just recently. Now my ship runs but it cannot connect nor download apps or chat with people like it is supposed to, I was told that I need to do a factory reset. Should I do a factory reset? More info in detail is in the link below.

https://github.com/urbit/bridge/issues/1102

**Comment by jalehman** [comment]
The proper place to reach out for help about this is support@urbit.org, although I can offer a bit of advice here.

Based on what you've shown here, the issue is that your ship is way behind on updates. There are two kinds of updates you need to be concerned with:

1. Updates to the runtime, which is the program that runs Urbit from a command line, and
2. Over-the-air updates (OTAs), which are received automatically when your runtime is up-to-date.

Start with step (1) above by following [these instructions](https://operators.urbit.org/manual/os/updates#runtime-updates) and, if you're still having issues, reach out to the support email above. Be aware that after updating the runtime and booting your ship back up it'll take a while (up to an hour) to bring everything up to date.
