### ISSUE TITLE
Eyre `%set-response` crashes after unbinding a path

### ISSUE THREAD

**Issue by tadad** [urbit/urbit#6582]
To reproduce
`|pass [%e %set-response '/new' ~]`
Then try to access `https://fake-nec.com/new` and you will see in the dojo:
```
~nec:dojo> home: bailing out
zsh: abort      ./nec/.run
```
this makes `%set-response` unusable for `%blog` since people are unbinding paths very often

**Comment by lukechampine** [comment]
I'm having trouble building vere right now, but I think this is happening because Eyre returns `[~ ~]` when you scry for an unbound path. I guess `u3_pier_peek_last` just crashes if it gets `[~ ~]`?

If there's a way to gracefully handle `[~ ~]` scries in vere, then we can have it delete its cache entry when that happens. Otherwise, we'll need Eyre to return something else from the scry.

**Comment by joemfb** [comment]
The crash will be in `_http_cache_respond()`, specifically due to `u3t(u3t(nun))`. `nun` there is a `(unit (cask))`, and needs null checks.
