### ISSUE TITLE
Json-to-json tube doesn't work

### ISSUE THREAD

**Issue by ixv** [urbit/urbit#6587]
```
> =json-tube .^(tube:clay %cc /=base=/json/json)
> (json-tube !>(s+'foobar'))
-find.$.+2
dojo: hoon expression failed
```

As far as I can tell this only affects identity tubes for the json mark.
For example, this works fine:
```
> =ship-tube .^(tube:clay %cc /=base=/ship/ship)
> (ship-tube !>(~zod))
[#t/@p q=0]
```

This is on base version `0v19.lu2ua.0tfl3.v6nek.5oog0.9obm0.3fsdl.8gj4d.rrkg0.ur2ts.f0rjg`

**Comment by joemfb** [comment]
I've added some tracing to %clay to track this down. It's running `ship:grab` against the ship mark via `+slap`, which finds the `$ship` mold. That should probably use `+slob` to check for an arm in the core, instead of accidentally working as it does now. In any case, we should shortcircuit identity.
