### ISSUE TITLE
Urbit fails to map 2048MB of memory on OpenBSD

### ISSUE THREAD

**Issue by ix** [urbit/urbit#749]
```
λ bin/urbit -c test                                  
~
urbit: home is test
boot: mapping 2048MB failed
see urbit.org/docs/user/install for adding swap space
λ echo $(($(vmstat | awk 'END{printf $5}') / 1024)) # free memory
5662
λ echo $(($(sysctl -n hw.physmem) / 1024 / 1024)) # all memory   
8064
λ echo $((8064 - 5662)) # used memory                            
2402
λ # (all in MB)
```

As you can see, I have enough memory, however Urbit isn't aware of this...?

I'm running OpenBSD current (6.0), June 2 amd64 snapshot.

**Comment by cgyarvin** [comment]
Sorry, I just sent in a PR for this.

You have enough memory -- but we are trying to map at a fixed address,
because we don't want an extra add when we dereference internal pointers.
The fixed address in the code doesn't seem to work for OpenBSD.  Not super
surprising.

Change 4e24a9a on cgyarvin/remap restores the old behavior, which was to
mmap at address 0 and print the value the OS gives us -- thus suggesting a
good place to map 2GB.  You can then send in your own PR with the correct
ifdef.

**Comment by juped** [comment]
I think you have to let the kernel decide where your pages are on OpenBSD, given default ASLR.

**Comment by cgyarvin** [comment]
Hm, that would make sense.  (I actually wrote one of the earliest ASLR papers.). It certainly wouldn't be *that* hard to patch Urbit to use a dynamic loom base...

**Comment by juped** [comment]
This is in

**Comment by ramrunner** [comment]
adding to this that you need to be in a group where it allows you to map enough mem with MAP_ANON. so add your user to a group (i use staff) that has
staff:\
        :datasize-cur=2560M:\
        :datasize-max=infinity:\
...
run cap_mkdb /etc/login.conf; 
and relogin
