### ISSUE TITLE
Porting Urbit to android and memory requirement

### ISSUE THREAD

**Issue by mparaniak** [urbit/urbit#877]
Hi,
I have a question regarding the memory requirement that urbit has: mapping 2GB on start up. 
Is this something that could be relaxed, and if yes, what would be the usability implications. 

Today's smartphones usually ship with at most 3GB, 4GB of memory, with around 1GB or less available to the user. So realistically we are looking at urbit running on 100MB ~ 300MB of available ram. 

The other solution would be actually enable swap file on rooted phones, but then we constrain available userbase significantly, as not all kernels will support swap, and even if  they do, then we won't ever get to 'urbit on appstore' experience.

While of course the 'urbit on appstore' is not exactly desirable right now, so maybe treat the question as really "Do we need 2GB and why, what if we don't?"

**Comment by chc4** [comment]
We allocate 2GB of memory so that we have a contiguous slab of memory to use for Nock allocations. There is actually a header define that says how much memory to use; https://github.com/urbit/urbit/blob/maint-0.4/include/c/portable.h#L77

Dropping the size of the slab will be perfectly fine, until it's not. In normal use, urbit doesn't actually use 2GB and the OS never even maps the pages, but if it does need more than allocated it will panic the event with an out-of-memory bail since it can't grow the slab at runtime (unless, like, we realloc and fix up all the pointers which we don't)

The most egregious memory use is the initial sync of the kernel from ~zod on first boot, which I think should be a lot lighter with the new plastic boot process. I seem to remember someone getting urbit working on an RPi just fine, and maybe even a phone before, but they probably setup at least some swap...

**Comment by cgyarvin** [comment]
It should certainly be possible to try.  I think Urbit on startup "only" takes 30MB or so, so there is plenty of headroom.

I think the u3 doc and headers for the address space layout are pretty straightforward...
