### ISSUE TITLE
Dojo making disk access on every key press - slow console

### ISSUE THREAD

**Issue by mparaniak** [urbit/urbit#878]
Running urbit on my laptop I noticed there is a disk activity every key press. I know the console validates 
input on the fly, and I am not that knowledgeable to know what exactly happens in urbit every time I type something. The point is, the delay is noticeable and makes typing in dojo an unpleasant experience.

My urbit is running on i7, 8GB RAM machine, so if there are any bottlenecks it is definitely not my hardware.

**Comment by cgyarvin** [comment]
The disk activity is normal, because Urbit is a database and can't change
its state until it has committed. Every event is a transaction.

If your laptop has a rotating drive, this may be part of the problem.  I
think it is reasonable these days to design for SSD, though.  Normally the
slight key lag is not due to disk latency, though, but (a) bad event
scheduling and (b) an unoptimized console flow.  We tend to optimize things
until they are not painful for us, then leave them for later work.
Premature optimization etc.

**Comment by mparaniak** [comment]
I (still) do have rotating disk, guess it is time to ditch it. 
As a side note, I run another urbit on a remote VPS with SSD and the delay is less noticeable, even though there is a network lag, which makes sense.
