### ISSUE TITLE
epur parsing localhost as secure regardless of scheme in URL

### ISSUE THREAD

**Issue by asssaf** [urbit/urbit#882]
```
> (epur 'http://localhost')
[~ [p=[p=%.y q=~ r=[%.y p=<|localhost|>]] q=[p=~ q=<||>] r=~]]
```
Workaround: use localhost.localdomain (provided it's defined in `/etc/hosts`):
```
> (epur 'http://localhost.localdomain')
[~ [p=[p=%.n q=~ r=[%.y p=<|localdomain localhost|>]] q=[p=~ q=<||>] r=~]]
```

Surprisingly, this doesn't occur when using `+url` in the dojo (but it does with `+curl url`).

**Comment by joemfb** [comment]
This is explicitly coded in [`++auri`](https://github.com/urbit/arvo/blob/maint-20170614/arvo/zuse.hoon#L1971) ([`++hoke`](https://github.com/urbit/arvo/blob/maint-20170614/arvo/zuse.hoon#L2403) is localhost or loopback). It's the same on master, where `++epur` is now [`++de-purl`](https://github.com/urbit/arvo/blob/master/sys/zuse.hoon#L4033).

The `:dojo` doesn't have this behavior because [it uses `++auru`](https://github.com/urbit/arvo/blob/master/app/dojo.hoon#L253) instead of `++auri`.

/cc @ohAitch
