### ISSUE TITLE
Learning Hoon - first read nock

### ISSUE THREAD

**Issue by mikolajpp** [urbit/urbit#883]
Hi,
So somehow I ended up reading the nock docs.
A couple of thoughts:
1- The nock docs are very good, much better that hoon in terms of linearity and clarity.
2- Suddenly a lot of concepts become much clearer if you even read just read the nock docs

It just a suggestion, that maybe actually we should stop talking about nock as an assembler (this word is scary; nock is nothing like an earth assembler. Nock is simple and elegant, I think with a couple of pictures even complete beginner to programming could understand it).

Talking on stream, I am not the first person who eventually went to  learn about nock, after several attempts to understand hoon through hoon tutorials. 

We need a new martian word for nock. I think it is a mistake to outwardly call it an assembler, as it prevents a lot of people from reading about it first, especially if they ever saw a real assembler (as in my case). 
Maybe just call it a 'basic language' of urbit, with 'basic' evoking association such as 'simple', 'easy to learn' etc. 

Best,

**Comment by cgyarvin** [comment]
Thanks, that's a good point!  This was my original approach -- but I don't
think I carried it out well the first time.

**Comment by chc4** [comment]
Reading about Nock for Hoon is like reading about the lambda calculus for Haskell. It explains the underlaying design decisions, but doesn't actually matter if you just want to write some code. It also requires some meditiation on the consequences of the underlaying theory (complete with the heavens enlightening your mind in a flash of beauty), which if someone is bearish on Urbit they probably won't take the time to do. At most I think the Hoon docs should link to the Nock in aside over "there are some very good reason for this design decision, see x".

Really, it's the same problem Hoon has always had - some people want to learn the language from the top down, and some from the bottom up. And I think most of the people that you need to target so that more programmers build urbit apps are the "top down" sort.

**Comment by galenwp** [comment]
My feeling about this is that there are basically three ways to go about learning about how to build on Urbit:

- From the bottom up, by starting with Nock
- From the middle out, by starting with Hoon
- From the top down, by just running examples and modifying them

If it were something that could be done easily, I'd reorganize the docs to this end.  Each path should be really linear and have clear steps.  Doing that is a pretty big undertaking, of course.  We don't really have the resources to take it on right now — but it's definitely worthwhile to be having this discussion.

As an aside, `~taglux-nidsep` (@joshuareagan) has been working on some Nock tutorial videos that I think are quite good.  He has probably written more raw Nock than anyone in the world, and is convinced it's simple and easy to understand.  

You can find some of this work in these fora threads:

https://urbit.org/fora/posts/~2017.5.26..23.35.22..9faa~/
https://urbit.org/fora/posts/~2017.5.31..04.21.49..654b~/

**Comment by joshuareagan** [comment]
Those fora threads are for the Hoon versions of the program.  Here are some Nock programs:

https://urbit.org/fora/posts/~2017.3.5..03.25.27..f42e~/
https://urbit.org/fora/posts/~2017.3.12..05.37.44..7d5e~/

I have some doc thoughts but I'll share those when they're a bit more polished.

**Comment by keatondunsford** [comment]
This is a great thread. We'll get on it. Thanks @mikolajpp!

**Comment by mikolajpp** [comment]
Thanks. In the meantime, I have started a blog at http://urbietorbi.org/
It took me some warm-up, but now I have just started a series on bottom-up urbit, which 
is focused on have-never-programmed-before users, though obviously we require console for now.
