### ISSUE TITLE
-s doesn't walk history for an existing pill, tries to boot 403 error result

### ISSUE THREAD

**Issue by ohAitch** [urbit/urbit#895]
e.g. on current master, a `-s` fakezod aborts on loading `zod/.urb/urbit.pill`, which in turn contains

```
<?xml version='1.0' encoding='UTF-8'?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access denied.</Message>
    <Details>Anonymous users does not have storage.objects.get access to bootstrap.urbit.org/d7b2ddf87be1f231cd4cdedc7c44c356b9f7d61a-master.pill.</Details>
</Error>
```

Expected behavior: walk the git history to find a change that touched `sys/`, or try curling all first-parent commits in sequence, or at *least* detect and report the 403 error in some way.

**Comment by keatondunsford** [comment]
I'm not sure how we plan to handle this generally, but we need to come up with and document a system for uploading pills when changes to `/sys` on master happens. This should be automated somehow, since a pill should always exist for the latest commit that changes `/sys`, and it seems like the process of one of us uploading pills by hand after we PR is bound to break at some point.

Also, the discrepancy between the `-master` and `-maint` tags at the end of the pills is confusing, I feel. Are we appending this by hand, or automatically based on the Arvo branch name?

**Comment by belisarius222** [comment]
This should definitely at least produce a relevant error message. I'm not sure it should search backward through the git history for previous commits, though. I think we might be better off keeping that logic dumb and doing as @keatondunsford suggested: automating pill upload for commits to the master branch. I think we'd be better off doing it that way rather than having it only produce certain builds, at least as a first step.

@keatondunsford we're switching to naming pills by Arvo branch name, but I don't think we've started to get rigorous about it yet, which is probably related to how this issue came up in the first place.

**Comment by galenwp** [comment]
Just hit this. Agree that it doesn't need to walk backwards — the first step is to just produce a better error.
